### ISSUE TITLE
New-MgTrustFrameworkPolicy: how to use it

### ISSUE THREAD

**Issue by erionpc** [microsoftgraph/msgraph-sdk-powershell#1188] opened 2022-04-03 17:19 UTC
Hi. I've started to use Microsoft.Graph on Powershell 7.2.2.
I'm not sure how to use this function to create a new policy. The documentation isn't very helpful. 
[New-MgTrustFrameworkPolicy](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/new-mgtrustframeworkpolicy?view=graph-powershell-beta)

I've tried the following:
```
New-MgTrustFrameworkPolicy -Id "B2C_1A_mypolicy"
```
```
New-MgTrustFrameworkPolicy -BodyParameter @{trustFrameworkPolicy = "B2C_1A_mypolicy"}
```
```
New-MgTrustFrameworkPolicy -BodyParameter @{trustFrameworkPolicy = "<?xml version='1.0' encoding='utf-8' ?><TrustFrameworkPolicy ...'/>"}
```
```
New-MgTrustFrameworkPolicy -BodyParameter @{trustFrameworkPolicy = "<policy file path>"}
```

For all 4 attempts I got the same error back:

_New-MgTrustFrameworkPolicy_Create: The policy being uploaded is not XML or is not correctly formatted: Data at the root level is invalid. Line 1, position 1._

I'm able to update the policy content if I upload the policy manually (through the Azure Portal) and then use:
```
Set-MgTrustFrameworkPolicyContent -TrustFrameworkPolicyId "B2C_1A_mypolicy" -InFile "<policy file path>"
```

It's obvious that this is still a work in progress and the documentation has been auto-generated. I would greatly appreciate some indication on how to upload a new policy using the SDK.

**Comment by peombwa** [comment] 2022-05-02 17:20
Sorry for the delayed response. This appears to be an issue with the API. The API expects a request payload with a content-type of `application/xml`, which goes against the service. I'll follow up with the workload.

API reference https://docs.microsoft.com/en-us/graph/api/trustframework-post-trustframeworkpolicy?view=graph-rest-beta.

**Comment by peombwa** [comment] 2022-05-02 18:35
As a workaround, you can use `Invoke-MgGraphRequest` to send the request body as `XML`.
``` xml
Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/beta/trustFramework/policies" -Body $XmlContent -ContentType "application/xml" -Debug
```

**Comment by chixcancode** [comment] 2022-06-05 13:30
Hi there, do we have any ETA when this will be resolved?

**Comment by timayabi2020** [comment] 2022-07-21 18:48
@peombwa based on what we have on the metadata, whatever the workload owner is describing is not accurate. The description is that it's a navigation property. Since we are sending a stream, we either need a "/content" or a "$value" appended at the end i.e ``POST /trustFramework/policies/$value`` or ``POST /trustFramework/policies/content``.
@darrelmiller what would be the best way to go about this issue?

**Comment by dmitriyse** [comment] 2022-10-13 00:15
Looks like it expected to have two steps:
1) New-MgTrustFrameworkPolicy -Id "B2C_1A_mypolicy"
2) Set-MgTrustFrameworkPolicyContent -TrustFrameworkPolicyId "B2C_1A_mypolicy" -InFile "myPolicy.xml"

**Comment by peombwa** [comment] 2023-08-02 19:14
Duplicate of https://github.com/microsoftgraph/msgraph-metadata/issues/197. The service metadata issue is being tracked at https://github.com/microsoftgraph/msgraph-metadata/issues/197. See **available workaround** at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1188#issuecomment-1115229820.

**Closed by peombwa** 2023-08-02 19:14 UTC
Labels: Service issue, Dependency: metadata-issue

**Comment by YoinMarcusMelberg** [comment] 2024-10-07 11:47
For anyone else that arrives from a miserable trail and error process around this (where the documentation is fundamentally missleading): As of version 2.24 (most likely earlier as well) it is possible to handle both create and update scenarion with 

`Set-MgTrustFrameworkPolicyContent -TrustFrameworkPolicyId "B2C_1A_mypolicy" -InFile "myPolicy.xml"`

If not present it will be created. 

New-MgTrustFrameworkPolicyContent  cmdlet does not work at all in any form-
