### ISSUE TITLE
Get-MgGroupDelta @odata.nextLink is not accessible

### ISSUE THREAD

**Issue by AdrianStefaniak** [microsoftgraph/msgraph-sdk-powershell#2238] opened 2023-08-10 12:22 UTC
Hello, 

I am trying to get delta changes to the group using Get-MggroupDelta and following 
https://learn.microsoft.com/en-us/graph/delta-query-groups?tabs=powershell

**Describe the bug**
As mentioned in the title, Get-MggroupDelta does not return @odata.nextlink

**To Reproduce**
Run 
 $members = Get-MgGroupDelta -Filter "id eq '$id'" -Property "displayName,description,members" 
$members.ToJsonString()

**Expected behavior**
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/131452324/8e99d1fd-ddfa-4ddf-88aa-8ea0cec32fdb)

Above are visible when running this command in graph explorer

**Debug Output**
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/131452324/a407fc12-f132-4309-aafb-d58e127fdefd)

Running the -debug show that it's also returned

**Module Version**
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/131452324/ae35d41f-c878-4028-a24b-b79b2bf73837)

**Environment Data**
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/131452324/74e9dea9-859e-4fe8-a600-a759eb175a0e)

**Screenshots**
Running in debug mode returns the desired value

**Additional context**
I need it for Get-MgGroupDelta -skiptoken <token>

**Comment by peombwa** [comment] 2023-08-10 18:59
Thanks for bringing this to our attention. We are tracking deltaLink support at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2062.

You should be able to get all the changes to the resource by using `Get-MgGroupDelta -All`. `@odata.nextLink` is meant to be opaque to SDK users since you can call the command with `-All` to automatically follow the next link to last page. What's currently missing is the ability to retrieve the `deltalink` from the last page (for future change tracking) and pass it back to the delta command. See https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2062#issuecomment-1644768630 for more details.

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2062.

**Closed by peombwa** 2023-08-10 18:59 UTC
