### ISSUE TITLE
Get-MgUserMessage: -CountVariable and -All return different counts

### ISSUE THREAD

**Issue by wk7804** [microsoftgraph/msgraph-sdk-powershell#1444] opened 2022-08-08 21:25 UTC
If I execute the following, the 'Count' variable will be assigned a value of '420':
`Get-MgUserMessage -UserId $FromUserEmailAddress -CountVariable Count`

However, if I execute the version below, the size of the resulting array is '270':
`$Messages = Get-MgUserMessage -UserId $FromUserEmailAddress -Property "sender,subject" -All`

I would expect the numbers to match (but it is possible that I've misunderstood something...)

As background - my original goal was to use the SDK to iterate through all available messages a page at a time, like is possible using MS Graph SDK's for other languages. While attempting to figure that out, I stumbled across the `-All` parameter.

I knew from using other SDK's how many messages were available to be retrieved, which agrees with the results of the `-CountVariable` parameter.

My goals would be met if I was able to either process each individual page (ideally based on the value of `@odata.nextLink` like is possible in Graph SDK's for other languages) or be confident that the `-All` parameter will indeed return all available messages.

**Comment by peombwa** [comment] 2022-08-11 23:31
Running the command with `-Debug`, I can see that the command follows the `@odata.nextLink` as expected until no nextLink is returned. So, `-All` works as intended.

It appears that the issue is with the message count returned by the [API](https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http) when you specify `-CountVariable Count` (`$count=true`). See related issue at https://github.com/microsoftgraph/microsoft-graph-docs/issues/17875. 

The issue can even be preproduced by manually following the nextLink using `Invoke-MgGraphRequest`:
``` powershell
$messages = @()
$uri = "/v1.0/users/$fromUserEmailAddress/messages?$select=sender,subject"
do {
    $result = Invoke-MgGraphRequest -Method GET -uri $uri
    $messages += $result.value
    $uri = $result.'@odata.nextLink'
} until ($null -eq $result.'@odata.nextLink')
# This count does not match the $count=true value.
Write-Host $messages.Count
```

As this is a service issue, I'd recommend you open a ticket/question at https://developer.microsoft.com/en-us/graph/support to have this resolved by the API owner. I'll also follow up with the API owner internally to surface this is a service issue.

**Comment by peombwa** [comment] 2022-08-11 23:50
It does appear that this is a known issue with `$count` for `/users/{user-id}/messages` as described in https://stackoverflow.com/questions/58482131/how-do-i-get-the-count-of-messages-in-the-mailbox.

Please open a question/ticket at https://developer.microsoft.com/en-us/graph/support to have this resolved by the workload owner.

Closing as a service issue.

**Closed by peombwa** 2022-08-11 23:50 UTC
Labels: Service issue
