### ISSUE TITLE
The v2 SDK don't support sovereign cloud (like China)?

### ISSUE THREAD

**Issue by chenxizhang** [microsoftgraph/msgraph-sdk-powershell#2255] opened 2023-08-18 10:03 UTC
Hi team, 

Thanks for the good work and I am excited to see the better version of powershell sdk for msgraph. 

I've done some tests and most of them worked as expect. But I found the supporting for sovereign cloud (like China) might be broken. 

When I try the cmdlet `Connect-MgGraph -Environment China` and input the username and password, I got the below error message.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/1996954/7e32f437-52b7-424b-be58-1ffcb76d4406)

**Comment by peombwa** [comment] 2023-08-18 21:43
Thanks for following up on this.

You'll need to register your own app in your tenant and use it when connecting to the SDK via `-ClientId`. Globally registered apps don't replicate to some sovereign cloud like Azure China. This is mentioned at [auth documentation](https://learn.microsoft.com/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#using-get-mgenvironment).
> Globally registered apps don't replicate to Azure China. You'll need to register your own applications in Azure China and use them when connecting to Microsoft Graph.

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/802.

**Closed by peombwa** 2023-08-18 21:43 UTC
