### ISSUE TITLE
Connect-Graph - Running any command after connected will reprompt for authentication

### ISSUE THREAD

**Issue by o-l-a-v** [microsoftgraph/msgraph-sdk-powershell#359] opened 2020-09-02 15:06 UTC
In PowerShell 5.1 (not using ISE, because of #247, #289), straight after running ```Connect-Graph``` and trying to run any command, ```Microsoft.Graph``` asks for reauthentication.

Code to reproduce

```powershell
PS C:\Users\OlavRønnestadBirkela> Microsoft.Graph.Authentication\Connect-Graph -TenantId '<some_verified_domain>' -Scopes (
>>     'User.Read.All',
>>     'Group.Read.All',
>>     'Policy.Read.All'
>> )
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <removed> to authenticate.
Welcome To Microsoft Graph!
PS C:\Users\OlavRønnestadBirkela> Microsoft.Graph.Identity.ConditionalAccess\Get-MgIdentityConditionalAccessNamedLocation
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <removed> to authenticate.

Id                                   CreatedDateTime DisplayName ModifiedDateTime
--                                   --------------- ----------- ----------------
<removed results>


PS C:\Users\OlavRønnestadBirkela>
```

$PSVersionTable

```powershell
PS C:\Users\OlavRønnestadBirkela> $PSVersionTable | Format-Table -Force

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Get-Module -Name 'Microsoft.Graph.*'

```powershell
PS C:\Users\OlavRønnestadBirkela> Get-Module -Name 'Microsoft.Graph.*' | Select-Object -Property 'Name','Version'

Name                                       Version
----                                       -------
Microsoft.Graph.Authentication             0.9.1
Microsoft.Graph.Identity.ConditionalAccess 0.9.1
```

**Comment by o-l-a-v** [comment] 2020-09-02 15:13
FYI, I get asked for reauth every time I run a commandlet. Wtf is this. Do you even test this?

**Comment by finsharp** [comment] 2020-09-02 16:03
@o-l-a-v Would I be right in assuming your `TenantId` is a GUID, you have the rights within that tenant to access the specified scopes and they are consented to?

**Comment by o-l-a-v** [comment] 2020-09-02 16:11
> @o-l-a-v Would I be right in assuming your `TenantId` is a GUID, you have the rights within that tenant to access the specified scopes and they are consented to? 

TenantId is any verified domain within said tenant, using Global Admin in said tenant. Might have used AOBO, but don't remember exactly.

**Comment by finsharp** [comment] 2020-09-02 16:17
I could not reproduce your error, kindly share the Debug log by passing `-Debug` to the cmdlet you are calling

`Get-MgIdentityConditionalAccessNamedLocation -Debug`

**Comment by o-l-a-v** [comment] 2020-09-21 13:08
Hi, sorry late reply. Heres two times running ```Get-MgIdentityConditionalAccessNamedLocation -Debug``` using PowerShell 7.1 beta 7, using global admin that is member in the tenant in question.

![image](https://user-images.githubusercontent.com/6450056/93770232-3794bd80-fc1c-11ea-977d-6ffc85bc7ac5.png)

**Comment by finsharp** [comment] 2020-09-24 14:22
@o-l-a-v Are you running as Administrator (Elevated Shell)?

Please attempt to run the commands using a Non-Admin Windows user account (Non Elevated Shell).

**Comment by o-l-a-v** [comment] 2020-09-24 14:26
@finsharp 
No, not running as admin.

**Comment by finsharp** [comment] 2020-09-24 16:20
We suspect a Token caching issue where your token cache is in an invalid state, try calling `Disconnect-Graph` then retry.

**Comment by o-l-a-v** [comment] 2020-10-05 09:14
Trying again today with new version of this module.

Module info

```powershell
```

PWSH 7.0.2 (MSI)

```powershell
PS C:\Users\OlavRønnestadBirkela> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\OlavRønnestadBirkela>
```

PWSH 7.1.0-rc1 (Microsoft Store)

```powershell
PS C:\Windows\System32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0-rc.1
PSEdition                      Core
GitCommitId                    7.1.0-rc.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Windows\System32>
```

It seems to work as expected now. Will come back here if I experience similar problems again.

**Comment by finsharp** [comment] 2020-10-14 08:58
@o-l-a-v Thank you for the update. I'll close the issue for now.

**Closed by finsharp** 2020-10-14 08:58 UTC
