### ISSUE TITLE
Unable to use on AzureUSGovernment Cloud

### ISSUE THREAD

**Issue by mrpullen** [microsoftgraph/msgraph-sdk-powershell#283] opened 2020-07-08 15:22 UTC
It doesn't look like I can connect to the AzureUSGovernment cloud -- receiving the following error.

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '14d82eec-204b-4c2f-b7e8-296a70dab67e'.

Thanks

**Comment by MIchaelMainer** [comment] 2020-07-09 20:13
This scenario is currently not supported. We plan to add support for sovereign clouds after our GA release for the public cloud.

**Comment by MIchaelMainer** [comment] 2020-07-09 20:14
Duplicate of #93

**Closed by MIchaelMainer** 2020-07-09 20:14 UTC
