### ISSUE TITLE
New-MgSiteListItem Fields

### ISSUE THREAD

**Issue by K-rocker** [microsoftgraph/msgraph-sdk-powershell#303] opened 2020-07-28 19:58 UTC
On New-MgSiteListItem I am not able to pass in the body parameter Fields.

This object seems to only have Id property from it's base:
IMicrosoftGraphFieldValueSet: IMicrosoftGraphEntity

This sends the Fields in the graph request:
New-MgSiteListItem -SiteId $siteId -ListId $listId -Fields @{ "Id"="0" } 

This doesn't send the Fields object at all:
New-MgsiteListItem -SiteId $siteId -ListId $listId -Fields @{ "Title"="Hello" }

**Comment by peombwa** [comment] 2020-08-05 00:33
This is a client bug, and we need to fix it on our end. We currently don't support OpenTypes.

Duplicate of #87 .

**Closed** 2020-08-06 01:01 UTC
Labels: Bug: Client, duplicate
