### ISSUE TITLE
Unable to set AccountEnabled to False with Update-MgUser

### ISSUE THREAD

**Issue by creature124** [microsoftgraph/msgraph-sdk-powershell#1264] opened 2022-05-15 22:35 UTC
It appears that Update-MgUser -AccountEnabled does not take an input, and therefore cannot set this property to false to disable an account.

> PS C:\Users\Greg> Update-Mguser -UserId $user.id -AccountEnabled $false
> Update-MgUser : A positional parameter cannot be found that accepts argument 'False'.
> At line:1 char:1
> + Update-Mguser -UserId $user.id -AccountEnabled $false
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Update-MgUser], ParameterBindingException
>     + FullyQualifiedErrorId : PositionalParameterNotFound,Update-MgUser

The docs appear to bear this out, declaring the parameter's type to be SwitchParameter with no default value, meaning that this command can enable an account, but it cannot disable them.
https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.users/update-mguser?view=graph-powershell-1.0#:~:text=False-,%2DAccountEnabled,-true%20if%20the

Is this intended? If it is, I think the docs needs to be updated to make this explicit, since this property can be set to false with a manual call via Invoke-MgGraphRequest.

**Comment by peombwa** [comment] 2022-06-08 22:54
`-AccountEnabled` is a switchParameter and not a boolean. You can explicitly set values to SwitchParameters as shown below:
``` powershelll
Update-Mguser -UserId $user.id -AccountEnabled:$false
```

We plan to move away from switchParameters as described in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/931 since this makes it difficult for customers to set boolean properties to false.

**Comment by peombwa** [comment] 2022-06-08 22:55
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/931.

**Closed by peombwa** 2022-06-08 22:55 UTC
Labels: Needs: Author Feedback
