### ISSUE TITLE
Get-MgSite on Graph SDK is not searching personal sites unless broadly requested. 

### ISSUE THREAD

**Issue by Asaurdiff-Tillamook** [microsoftgraph/msgraph-sdk-powershell#544] opened 2021-02-06 00:10 UTC
I am trying to use the SDK to pull up users My-Site urls by using 
`Get-MgSite -Search "<UserName>"` 
This does not find any site even if I have verified with the broad search of:
`Get-MgSite -All | Select DisplayName,WebUrl,SiteId | Sort DisppayName | Format-list`
To verify the search is working I have done a search for a standard Sharepoint site and it does pull. Like the example shown for "sites". 
`Get-MgSite -Search "Marketing"` 
This does pull siteId's up. 

Any explanation why this would be happening. The application authentication I am using has Sites.Manage.All permissions 
[AB#8025](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8025)

**Comment by peombwa** [comment] 2021-02-09 22:14
This looks like a service bug. Are you able to search sites in your tenant using [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer/preview)?

**Comment by Asaurdiff-Tillamook** [comment] 2021-02-09 23:22
Hello @peombwa ,
When I do a <https://graph.microsoft.com/v1.0/sites?search=*> on Graph Explorer I return all sites, none seem to be displaying mysite and not all options. With Graph explorer I am forced to use my Sharepoint Admin account, but different results. 

also, I was able to identify the mysites using MGGraph. This is the schema 
`Get-MgSite -All | Where-Object {$_.Name -eq "<userName>"}`
 I also noticed that filter only works for "Created Date" which is limiting and of course 'Search' should search UserName if possible. 

You tell me if this is a good enough solution or would you like to continue with the bug fix?

**Comment by maisarissi** [comment] 2022-02-21 22:54
Hi @peombwa 

Using Graph Explorer, I was able to successfully retrieve the right information by searching for "hotels". 

![image](https://user-images.githubusercontent.com/22648831/155034305-9749fca6-fed6-41ff-a58f-77b9034adebc.png)


The SDK on the other hand, seems to be sending the right URL, but the response is empty.

![image](https://user-images.githubusercontent.com/22648831/155034094-c7b68e09-b60c-4ba5-a6e4-ebee6e10e37f.png)


Debug information:
```powershell
@maisarissi ➜ ~ Get-MgSite -Search "hotels" -Debug
DEBUG: [CmdletBeginProcessing]: - Get-MgSite begin processing with parameterSet 'List1'.
DEBUG: [Authentication]: - AuthType: 'Delegated', AuthProviderType: 'InteractiveAuthenticationProvider', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph PowerShell'.
DEBUG: [Authentication]: - Scopes: [Application.ReadWrite.All, AuditLog.Read.All, DeviceManagementConfiguration.Read.All, Directory.Read.All, eDiscovery.Read.All, eDiscovery.ReadWrite.All, Files.ReadWrite.All, Group.ReadWrite.All, openid, Policy.Read.All, profile, Reports.Read.All, SecurityActions.ReadWrite.All, SecurityEvents.ReadWrite.All, ServiceHealth.Read.All, User.Read, User.Read.All, email, Sites.Manage.All].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/sites?$search="hotels"

Headers:
SdkVersion                    : graph-powershell/1.9.2,Graph-dotnet-1.25.1
FeatureFlag                   : 00000047
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.22000; en-US),PowerShell/7.1.4,Get-MgSite_List1
Accept-Encoding               : gzip

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : db7744e9-e615-491e-9c2b-3cabfe654621
client-request-id             : db7744e9-e615-491e-9c2b-3cabfe654621
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Brazil South","Slice":"E","Ring":"3","ScaleUnit":"002","RoleInstance":"CP1PEPF00002E4B"}}
X-SearchPlatform              : Substrate
OData-Version                 : 4.0
Date                          : Mon, 21 Feb 2022 22:37:09 GMT

Body:



DEBUG: [CmdletEndProcessing]: - Get-MgSite end processing.
```

I couldn't get it to work using Ivoke-MgGraph either:

```powershell
@maisarissi ➜ ~ Invoke-MgGraphRequest -Method GET -Uri "https://graph.microsoft.com/v1.0/sites?search=hotels" -Debug
VERBOSE: GET https://graph.microsoft.com/v1.0/sites?search=hotels with 0-byte payload

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a
DEBUG: GET /v1.0/sites?search=hotels HTTP/1.1
HTTP: graph.microsoft.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.22000; en-US) PowerShell/7.1.4 Invoke-MgGraphRequest


VERBOSE: received 80-byte response of content type application/json
DEBUG: GET https://graph.microsoft.com/v1.0/sites?$search=hotels
HTTP/1.1 200 OK
Cache-Control: no-cache
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: cf141af7-5dc8-46b5-8ccd-6191928e8edc
client-request-id: cf141af7-5dc8-46b5-8ccd-6191928e8edc
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Brazil South","Slice":"E","Ring":"3","ScaleUnit":"000","RoleInstance":"CP1PEPF00001A68"}}
X-SearchPlatform: Substrate
OData-Version: 4.0
Date: Mon, 21 Feb 2022 22:45:08 GMT
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; IEEE754Compatible=false; charset=utf-8
Content-Encoding: gzip

{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#sites","value":[]}

Name                           Value
----                           -----
@odata.context                 https://graph.microsoft.com/v1.0/$metadata#sites
value                          {}
```

Needs investigation.

**Comment by peombwa** [comment] 2022-02-22 18:59
@Asaurdiff-Tillamook, from my testing, it looks like you cannot search for personal sites using `$Search (-Search)`, even with the recommended permission of `Sites.Read.All and Sites.ReadWrite.All`. I suggest you open a support ticket/question at https://developer.microsoft.com/en-us/graph/support to have the workload owners investigate this.

@maisarissi, personal sites (mySite) can only be accessed via app-only calls. See https://github.com/microsoftgraph/microsoft-graph-docs/issues/14387#issuecomment-930432150.

**Comment by maisarissi** [comment] 2022-02-22 19:55
Thanks @peombwa .

One question though. I'm using Graph Explorer (logged as a demo admin account) and PowerShell SDK (using the in-built appId connecting to the same admin account).
Why am I not getting the same response from /sites?search="" and running Get-MgSite -Search?

Not related to mySite (personal site) as I understood it's not supported using delegated permissions. But why does all sites 'search' work in GE but the response is empty in the SDK?

**Comment by peombwa** [comment] 2022-02-22 22:01
@maisarissi, from the scopes in your logs, it looks like you haven't granted the PowerShell app the necessary permission(s) to `$search` on `/sites`. You [need to consent](https://docs.microsoft.com/en-us/graph/api/site-search?view=graph-rest-1.0&tabs=http#permissions) to either `Sites.Read.All` or `Sites.ReadWrite.All` to use `$search`.

Scopes in your logs:
``` powershell
DEBUG: [Authentication]: - Scopes: [Application.ReadWrite.All, AuditLog.Read.All, DeviceManagementConfiguration.Read.All, Directory.Read.All, eDiscovery.Read.All, eDiscovery.ReadWrite.All, Files.ReadWrite.All, Group.ReadWrite.All, openid, Policy.Read.All, profile, Reports.Read.All, SecurityActions.ReadWrite.All, SecurityEvents.ReadWrite.All, ServiceHealth.Read.All, User.Read, User.Read.All, email, Sites.Manage.All].
```

This could be why it is not working for you, as I cannot reproduce it on my end with the correct permission. I'm only able to repro the API issue mentioned by @Asaurdiff-Tillamook above.

**Comment by peombwa** [comment] 2022-05-13 00:39
Closing as this is a service issue, and no action is needed from the SDK. Service-related issues should be channeled to https://developer.microsoft.com/en-us/graph/support for the workload owners to investigate.

**Closed by peombwa** 2022-05-13 00:39 UTC
Labels: Service issue
