### ISSUE TITLE
Built-in retry handler is not working

### ISSUE THREAD

**Issue by keisuwa** [microsoftgraph/msgraph-sdk-powershell#1459] opened 2022-08-15 07:33 UTC
### Summary
According to the issue #281, MS Graph PowerShell has a retry handler. However, when I intentionally return the following response which is described in [the article](https://docs.microsoft.com/en-us/graph/throttling), MS Graph PowerShell doesn't seem to properly handle the 429 error.

```json

HTTP/1.1 429 Too Many Requests
Content-Type: application/json
Retry-After: 10

{
  "error": {
    "code": "TooManyRequests",
    "innerError": {
      "code": "429",
      "date": "2022-08-15T11:25:51",
      "message": "Please retry after",
      "request-id": "94fb3b52-452a-4535-a601-69e0a90e3aa2",
      "status": "429"
    },
    "message": "Please retry again later."
  }
}
```

### Repro steps
1. Make the following settings in Fiddler's AutoResponder
  ・URL Pattern : https://graph.microsoft.com/v1.0/users?$top=1
  ・Respone : Specify a dat file containing the above response
   ![image](https://user-images.githubusercontent.com/111256204/184587842-2b9eaf99-cbc2-43c1-bb79-615ddcfeb33b.png)

	
2. Run "Connect-MgGraph" in PowerShell
3. Run "Get-MgUser -Top 1" in PowerShell

### Results
![image](https://user-images.githubusercontent.com/111256204/184587920-ce053e52-06d1-499f-ad55-dc252d5cd939.png)
Even After waiting the time specified in the Retry-After header, MS Graph PowerShell stops at all and throws no error, as shown in the above image.

**Comment by peombwa** [comment] 2022-08-22 23:38
@keisuwa, the built-in retry handler is working as expected when you are throttled by the service.

The issue is with the repro steps above. It looks like Fiddler's AutoResponder is not returning the response to the caller (PowerShell process). You can repro the behavior same using:
``` powershell
Invoke-RestMethod -Method Get "https://graph.microsoft.com/v1.0/users?`$top=1" -Debug
```

**Comment by peombwa** [comment] 2022-08-24 18:35
@keisuwa That's great! I'll go ahead and close the issue.

**Closed by peombwa** 2022-08-24 18:35 UTC
Labels: Question: SDK, Needs: Attention :wave:
