### ISSUE TITLE
Documentation for New-MgPolicyClaimMappingPolicy commandlet is wrong

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/msgraph-sdk-powershell#2345] opened 2023-10-05 22:55 UTC
https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8602
report documentation bug issue here per advice from the above

**Comment by peombwa** [comment] 2023-10-11 17:55
Thanks for bringing this to our attention.

This is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2272#issuecomment-1699646229 and https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/1929#issuecomment-1679033877. This is a service issue as description is a property of `claimsMappingPolicy` that's inherited from [stsPolicy](https://learn.microsoft.com/en-us/graph/api/resources/policybase?view=graph-rest-1.0) resource type.

Please open a service ticket at https://developer.microsoft.com/graph/support to surface this to the API team that owns the API.

As a workaround, you can choose to ignore the parameter until the service description is fixed.

**Comment by peombwa** [comment] 2023-10-11 17:56
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2272#issuecomment-1699646229

**Closed by peombwa** 2023-10-11 17:56 UTC
