### ISSUE TITLE
Results from Get-MgUser can't be piped to other MgUser functions

### ISSUE THREAD

**Issue by EmeraldFlame** [microsoftgraph/msgraph-sdk-powershell#1182] opened 2022-03-31 02:58 UTC
# Problem
Currently it looks like UserId is not a pipeline enabled field
Additionally, when you run Get-MgUser it returns the user object with the User's ID in a property named "Id". Other user functions however (such as Remove-MgUser, Update-MgUserSetting, and nearly all other user fucntions) use the argument "UserId" instead. The functions also do not support an alias for "Id" on the "UserId" argument. This effectively means that even if UserId were a pipeline enabled field, you would still be unable to directly pipe the results of Get-MgUser to any other function.

This goes against normal conventions and best practices used in powershell as well as other 1st party modules.

# Example
## Expected Behavior
```powershell
PS C:\> Get-MgUser -Filter "UserPrincipalName eq 'test.user@example.com'" | Remove-MgUser -PassThru
True
PS C:\>
```

## Current Behavior
```powershell
PS C:\> Get-MgUser -Filter "UserPrincipalName eq 'test.user@example.com'" | Remove-MgUser -PassThru

Remove-MgUser_DeleteViaIdentity: The pipeline has been stopped.
Exception: InputObject has null value for InputObject.UserId
Remove-MgUser_DeleteViaIdentity: InputObject has null value for InputObject.UserId
PS C:\>
```

## Available Work-around
```powershell
PS C:\> Get-MgUser -Filter "UserPrincipalName eq 'test.user@example.com'" | 
>>        ForEach-Object { Remove-MgUser -UserId $_.Id -PassThru }
True
PS C:\>
```

# Solution
Enable the "UserId" argument to accept pipeline input and add an alias of "Id" in order to facilitate pipeline property name matches.

### Aside
Long term, I feel there needs to be a wider discussion around aligning function output and input naming, as this doesn't seem to be the only instance of this mis-match. That could likely lead to breaking changes though, and the alias option above at least gets the functionality there. Frankly, this feels massively overlooked and I'm somewhat shocked to see such a large departure from normal pipeline conventions in a 1st party module.

**Comment by peombwa** [comment] 2022-03-31 20:59
Thanks for taking the time to open this. This is a known issue that we are actively tracking in #906. Piping doesn't currently work due to how the path indexers are named in the OpenAPI files that the SDK is generated from. As you've highlighted above, a workaround is to loop through the output of a command. A fix will be provided by https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/840.

**Comment by peombwa** [comment] 2022-03-31 21:00
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/906.

**Closed by peombwa** 2022-03-31 21:00 UTC
Labels: OpenApiService-Dependency
