### ISSUE TITLE
Get-MGUserEvent Does not return recurring events

### ISSUE THREAD

**Issue by Clifra-Jones** [microsoftgraph/msgraph-sdk-powershell#1405] opened 2022-07-19 12:36 UTC
Get-MgUserEvents does not return recurring events. I've tried every kind of filter ans it still will not return recurring events.

**Comment by Clifra-Jones** [comment] 2022-07-19 14:06
More Info.
In further investigating it does return the original event for the recurring event. It is listed with the date the event was created.
But if your goal is to return all events for today then you will not get the recurring event scheduled for today.
The recurrence information is in the original event. It would be nice to have these recurring events listed in the events date range you are filtering by.

**Comment by Clifra-Jones** [comment] 2022-07-19 19:26
OK, I tried to do the above and found out there is an issue with Get-MgUserEventInstances
See: https://github.com/microsoftgraph/msgraph-metadata/issues/120
Basically this command does notwork. The API call requires a start and end date but there is no way to provide that in the Powershell Command and trying to apply it in a filter does not work.

**Comment by peombwa** [comment] 2022-07-25 18:04
Thanks for following up on this.

You are right, this is related to https://github.com/microsoftgraph/msgraph-metadata/issues/120. The metadata used to generate the module is missing the required query parameters. This will have to be fixed in the metadata for us to generate accurate commands.

We are tracking the missing query parameter in https://github.com/microsoftgraph/msgraph-metadata/issues/120.

**Comment by peombwa** [comment] 2022-07-25 18:06
Closing as duplicate of https://github.com/microsoftgraph/msgraph-metadata/issues/120.

Please use `Invoke-MgGraphRequest` in the meantime to call the API. See https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-mailbag-a-deeper-look-into-the-microsoft-graph-powershell-sdk/#manual-requests for more details.

**Closed by peombwa** 2022-07-25 18:06 UTC
Labels: ToTriage

**Comment by terrencemcbride** [comment] 2023-03-29 21:10
If anyone comes here like me trying to find and handle recurrences of events, do yourself a favor and try a different endpoint. I hit CalendarView and have had great success:
"https://graph.microsoft.com/v1.0/users/$UserID/calendarView?startDateTime=$Timestamp&endDateTime=$EndTimestamp&$select=subject,body....."
