### ISSUE TITLE
Cannot pipe Get-MgGroup to Remove-MgGroup because the interface doesn't match

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#1058] opened 2022-02-02 18:33 UTC
```ps
🏠
❯ get-mggroup -top 1 | remove-mggroup
Remove-MgGroup_DeleteViaIdentity: The pipeline has been stopped.
Exception: InputObject has null value for InputObject.GroupId
Remove-MgGroup_DeleteViaIdentity: InputObject has null value for InputObject.GroupId

🏠
💥❯ get-mggroup -top 1 |% {remove-mggroup -inputobject $_}
Remove-MgGroup_DeleteViaIdentity: The pipeline has been stopped.
Exception: InputObject has null value for InputObject.GroupId
```

**How is this not like the most basic of unit tests?!?!**
![image](https://user-images.githubusercontent.com/15258962/152215895-a019d034-c43e-49a6-a1ad-ce47d71c37a3.png)

### Workaround
`get-mggroup -top 1 |% {remove-mggroup -groupid $_.id}`

**Comment by peombwa** [comment] 2022-02-22 19:14
Thanks for surfacing this. The SDK does not currently support piping due to how the API is described in the OpenAPI document that the SDK is generated from.

We are tacking piping support in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/906, and a fix will be provided by https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/840 when we move to [v2](https://github.com/microsoftgraph/msgraph-sdk-powershell/milestone/23).

**Comment by peombwa** [comment] 2022-02-22 19:15
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/906.

**Closed by peombwa** 2022-02-22 19:15 UTC
Labels: duplicate, Enhancement: Client
