### ISSUE TITLE
New(Update)-MgDeviceAppManagementMobileAppConfiguration doesn't support custom AdditionalProperties objects 

### ISSUE THREAD

**Issue by headcra6** [microsoftgraph/msgraph-sdk-powershell#960] opened 2021-12-01 08:37 UTC
Hi all,

I faced an issue with mentioned functions
New-MgDeviceAppManagementMobileAppConfiguration or Update-MgDeviceAppManagementMobileAppConfiguration.
The issue identified in the 'settings' param which should reflect the array of [appConfigurationSettingItem](https://docs.microsoft.com/en-us/graph/api/resources/intune-apps-appconfigurationsettingitem?view=graph-rest-1.0).
If I reuse this parameter from Get-MgDeviceAppManagementMobileAppConfiguration output the appconfiguration successfully created, if I built it myself it fails with the following error:
```
Property settings in payload has a value that does not match schema.
```
I compared it by content and type, everything is equal the type is:
```
TypeName: System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.O 
bject, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
```
I converted my final body object to JSON and successfully created AppConfiguration through the Graph Explorer so the content itself is probably ok, it seems some not documented properties are available. All properties achievable by Get-Member also compared, objects are equal
What else can differ in this case? Where the schema description can be discovered to identify missing diff or improper content(besides the visible part of it)? SDK description of these functions looks like automatically generated and did not shed light on this issue.

Looking forward to the community experience/developers' help!

**Comment by peombwa** [comment] 2021-12-07 17:57
This is related to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/954. The workaround is to use `Invoke-MgGraphRequest`.

**Comment by peombwa** [comment] 2021-12-07 17:57
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/954

**Closed by peombwa** 2021-12-07 17:57 UTC
Labels: duplicate
