### ISSUE TITLE
Connect-Graph only works in an administrative PowerShell window

### ISSUE THREAD

**Issue by mmascolino** [microsoftgraph/msgraph-sdk-powershell#118] opened 2020-02-24 20:25 UTC
I installed the module using an administrative powershell window but trying to connect using a plain un-elevated window fails:

```
PS C:\ > Connect-Graph
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code E37AL5TLR to authenticate.
Connect-Graph : Access to the path 'C:\Program
Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\0.1.5\bin\userTokenCache.bin3' is denied.
At line:1 char:1
+ Connect-Graph
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-Graph], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectGraph
```

I am able to successfully connect via an elevated window.

**Comment by peombwa** [comment] 2020-02-27 00:50
@mmascolino Thanks for opening this issue.

This is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/109. The issue has already been fixed, and it will be available in the next release.

**Closed** 2020-03-15 23:34 UTC
Labels: duplicate
