### ISSUE TITLE
Permissions not returned for Find-MgGraphCommand -command Get-MgGroupCalendar (or beta)

### ISSUE THREAD

**Issue by robinmalik** [microsoftgraph/msgraph-sdk-powershell#2171] opened 2023-07-18 12:58 UTC
**Describe the bug**
> No permissions returned via Find-MgGraphCommand, so I'm unable to connect with the correct scopes to use the cmdlet.

**To Reproduce**
`Find-MgGraphCommand -command Get-MgGroupCalendar | Select -ExpandProperty Permissions`

**Expected behavior**
> The required scopes are returned

**Debug Output**

```
   APIVersion: v1.0

Command             Module   Method URI                         OutputType              Permissions Variants           
-------             ------   ------ ---                         ----------              ----------- --------           
Get-MgGroupCalendar Calendar GET    /groups/{group-id}/calendar IMicrosoftGraphCalendar {}          {Get, GetViaIden...


   APIVersion: beta

Command                 Module        Method URI                         OutputType              Permissions Variants  
-------                 ------        ------ ---                         ----------              ----------- --------  
Get-MgBetaGroupCalendar Beta.Calendar GET    /groups/{group-id}/calendar IMicrosoftGraphCalendar {}          {Get, G...
```

**Module Version**
```
ModuleType Version Name                            
---------- ------- ----                            
    Script 2.1.0   Microsoft.Graph.Applications    
    Script 2.1.0   Microsoft.Graph.Authentication  
    Script 2.1.0   Microsoft.Graph.Bookings        
    Script 2.1.0   Microsoft.Graph.Calendar        
    Script 2.1.0   Microsoft.Graph.Groups          
    Script 2.1.0   Microsoft.Graph.Identity.SignIns
    Script 2.1.0   Microsoft.Graph.Mail            
    Script 2.1.0   Microsoft.Graph.Sites           
    Script 2.1.0   Microsoft.Graph.Teams           
    Script 2.1.0   Microsoft.Graph.Users           
```

**Environment Data**
```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.22621.1830                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.22621.1830                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

and

```
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeniorConsulting** [comment] 2023-07-18 20:42
Looks to be the same in PowerShell 5.1

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/87233d65-60f5-46dd-a231-e8eae81d39bf)

It sounds like you're stuck on permissioning, so this might help you get going while the devs work on the fix:
https://learn.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&tabs=http#permissions

**Comment by peombwa** [comment] 2023-07-25 21:38
Thanks for bringing this to our attention.

The permissions for `/groups/{group-id}/*` are missing at the source. The same behavior can be seen in tools like Graph Explorer:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/7061532/24b3dfcc-a2f8-4712-9533-ef2e54bed71a)

Please use the [API reference](https://learn.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&tabs=http#permissions) as suggested above as the team investigates the issue at https://github.com/microsoftgraph/microsoft-graph-devx-content/issues/361.

Closing as duplicate of https://github.com/microsoftgraph/microsoft-graph-devx-content/issues/361.

**Closed by peombwa** 2023-07-25 21:38 UTC
Labels: ToTriage

**Comment by ChrisPChikn** [comment] 2024-01-03 09:38
Hate to re-awaken, but this exact behaviour is also occurring for Get-MgServicePrincipalMemberOfAsGroup.
I have found the permissions in the meanwhile through a links shared here for the API permissions.

[permissions for Get-MgServicePrincipalMemberOfAsGroup](https://learn.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&tabs=http)
