### ISSUE TITLE
Set-MgEntitlementManagementAccessPackageAssignmentPolicy serialization issues

### ISSUE THREAD

**Issue by William-Francillette** [microsoftgraph/msgraph-sdk-powershell#1683] opened 2022-12-14 18:27 UTC
Hi,

I'm experiencing serialization issues with Set-MgEntitlementManagementAccessPackageAssignmentPolicy

- Not sure if that intentional but id has to be added twice 
1. as AccessPackageAssignmentPolicyId
2. as Id in the bodyParameter

This is also generated in the documentation example which is probably the reason of this duplication:                             https://learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&tabs=http#examples

AccessPackageAssignmentPolicyId should be sufficient

- The nested hashtable are not seen/serialized in BodyParameter

This is my code using Powershell 5.1

```
$string=@"
{
    "Id":  "cf691887-7f40-4a65-bff5-06ec75f9a583",
    "Description":  "",
    "RequestApprovalSettings":  {
                                    "approvalMode":  "SingleStage",
                                    "isRequestorJustificationRequired":  true,
                                    "isApprovalRequiredForExtension":  false,
                                    "approvalStages":  {
                                                           "approvalStageTimeOutInDays":  14,
                                                           "isApproverJustificationRequired":  true,
                                                           "escalationTimeInMinutes":  0,
                                                           "primaryApprovers":  [
                                                                                    {
                                                                                        "isBackup":  true,
                                                                                        "id":  "4fe9b98d-078d-4379-869d-0c673023ab81",
                                                                                        "@odata.type":  "#microsoft.graph.singleUser"
                                                                                    },
                                                                                    {
                                                                                        "isBackup":  false,
                                                                                        "managerLevel":  1,
                                                                                        "@odata.type":  "#microsoft.graph.requestorManager"
                                                                                    }
                                                                                ],
                                                           "isEscalationEnabled":  false
                                                       },
                                    "isApprovalRequired":  true
                                },
    "DurationInDays":  360,
    "DisplayName":  "policy with access review",
    "RequestorSettings":  {
                              "scopeType":  "AllExistingDirectoryMemberUsers",
                              "acceptRequests":  true
                          },
    "AccessReviewSettings":  {
                                 "isEnabled":  true,
                                 "startDateTime":  "11/22/2022 23:59:59",
                                 "isAccessRecommendationEnabled":  true,
                                 "accessReviewTimeoutBehavior":  "removeAccess",
                                 "isApprovalJustificationRequired":  true,
                                 "recurrenceType":  "quarterly",
                                 "reviewerType":  "Self",
                                 "durationInDays":  25
                             },
    "CanExtend":  false
}
"@


$json=$string|ConvertFrom-Json

function convertTo-JsonAsHashtable ($json)
{
    $hash=@{}

    foreach ($property in $json.psobject.properties)
    {
        $value=$property.Value
        if ($property.Value.gettype().Name -eq "PSCustomObject")
        {
            $value=convertTo-JsonAsHashtable $property.Value        
        }
        $hash.add($property.Name,$property.Value)
    }

    return $hash
}
$hash=convertTo-JsonAsHashtable $json 

Set-MgEntitlementManagementAccessPackageAssignmentPolicy `
    -BodyParameter $hash `
    -AccessPackageAssignmentPolicyId $hash.Id -debug
```
And here the debug trace

```
PS C:\temp\m365DSC\Backup\AADEntitlementManagementAccessPackageAssignmentPolicy> Set-MgEntitlementManagementAccessPackageAssignmentPolicy `
    -BodyParameter $hash `
    -AccessPackageAssignmentPolicyId $hash.Id -debug
DEBUG: [CmdletBeginProcessing]: - Set-MgEntitlementManagementAccessPackageAssignmentPolicy begin processing with parameterSet 'Set'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', AuthProviderType: 'ClientCredentialProvider', ContextScope: 'Process', AppName: 'M365DSC'.
DEBUG: [Authentication]: - Scopes: [Policy.Read.ConditionalAccess, DeviceManagementManagedDevices.Read.All, Policy.ReadWrite.ConditionalAccess, User.ReadWrite.All, RoleManagement.Read.Directory, Policy.ReadWrite.ApplicationConfiguration, Application.ReadWrite.All, Group.Read.All, Directory.ReadWrite.All, DeviceManag
ementServiceConfig.Read.All, Group.ReadWrite.All, Directory.Read.All, User.Read.All, Agreement.Read.All, DeviceManagementServiceConfig.ReadWrite.All, GroupMember.Read.All, Organization.ReadWrite.All, DeviceManagementConfiguration.Read.All, DeviceManagementManagedDevices.ReadWrite.All, User.ManageIdentities.All, Orga
nization.Read.All, RoleManagement.ReadWrite.Directory, GroupMember.ReadWrite.All, Policy.Read.All, DeviceManagementConfiguration.ReadWrite.All, Application.Read.All, DeviceManagementApps.ReadWrite.All, DeviceManagementApps.Read.All, EntitlementManagement.Read.All, EntitlementManagement.ReadWrite.All].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignmentPolicies/cf691887-7f40-4a65-bff5-06ec75f9a583

Headers:


Body:
{
  "id": "cf691887-7f40-4a65-bff5-06ec75f9a583",
  "description": "",
  "canExtend": false,
  "displayName": "policy with access review",
  "durationInDays": 360
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : d9742a54-1c89-4e08-9859-45f825ea742c
client-request-id             : d9742a54-1c89-4e08-9859-45f825ea742c
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"3","ScaleUnit":"000","RoleInstance":"LN2PEPF00005FB8"}}
Date                          : Wed, 14 Dec 2022 18:11:29 GMT

Body:
{
  "error": {
    "code": "ArgumentNullException",
    "message": "Value cannot be null.\r\nParameter name: Id",
    "innerError": {
      "date": "2022-12-14T18:11:29",
      "request-id": "d9742a54-1c89-4e08-9859-45f825ea742c",
      "client-request-id": "d9742a54-1c89-4e08-9859-45f825ea742c"
    }
  }
}


Set-MgEntitlementManagementAccessPackageAssignmentPolicy : Value cannot be null.
Parameter name: Id
At line:1 char:1
+ Set-MgEntitlementManagementAccessPackageAssignmentPolicy `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ AccessPackage...gnmentPolicy1 }:<>f__AnonymousType178`2) [Set-MgEntitleme...nmentPolicy_Set], RestException`1
    + FullyQualifiedErrorId : ArgumentNullException,Microsoft.Graph.PowerShell.Cmdlets.SetMgEntitlementManagementAccessPackageAssignmentPolicy_Set
DEBUG: [CmdletEndProcessing]: - Set-MgEntitlementManagementAccessPackageAssignmentPolicy end processing.
```

**Comment by peombwa** [comment] 2022-12-14 20:01
Please construct the hashtable as shown in the example at https://learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&tabs=powershell#request.

The issue is with how you are converting the JSON to hashtable. Specifically, in how you are handling nested objects in the JSON object. `$hash.AccessReviewSettings.GetType()` shows that the nested objects are of type `PSCustomObject` instead of a `hashtable`.

If your goal is to use JSON string as the input, then use `ConvertFrom-Json -AsHashtable` to convert the JSON to hashtable directly. i.e.,
``` powershell
$hash = $string | ConvertFrom-Json -AsHashtable
Set-MgEntitlementManagementAccessPackageAssignmentPolicy `
    -BodyParameter $hash `
    -AccessPackageAssignmentPolicyId $hash.Id -debug
```

**Comment by William-Francillette** [comment] 2022-12-14 20:09
Hi Peter,

I extracted the Json string from my DSC module (I'm developing a resource for M365DSC module) - I used this format as I am testing using PS 5.1 and the AsHashTable is not available - I have tested the hashtable and it is correct - see below when I convert it back to Json

```
convertTo-JsonAsHashtable $json |convertTo-Json -depth 20
{
    "Id":  "cf691887-7f40-4a65-bff5-06ec75f9a583",
    "AccessReviewSettings":  {
                                 "isEnabled":  true,
                                 "startDateTime":  "11/22/2022 23:59:59",
                                 "isAccessRecommendationEnabled":  true,
                                 "accessReviewTimeoutBehavior":  "removeAccess",
                                 "isApprovalJustificationRequired":  true,
                                 "recurrenceType":  "quarterly",
                                 "reviewerType":  "Self",
                                 "durationInDays":  25
                             },
    "DurationInDays":  360,
    "Description":  "",
    "RequestApprovalSettings":  {
                                    "approvalMode":  "SingleStage",
                                    "isRequestorJustificationRequired":  true,
                                    "isApprovalRequiredForExtension":  false,
                                    "approvalStages":  {
                                                           "approvalStageTimeOutInDays":  14,
                                                           "isApproverJustificationRequired":  true,
                                                           "escalationTimeInMinutes":  0,
                                                           "primaryApprovers":  [
                                                                                    {
                                                                                        "isBackup":  true,
                                                                                        "id":  "4fe9b98d-078d-4379-869d-0c673023ab81",
                                                                                        "@odata.type":  "#microsoft.graph.singleUser"
                                                                                    },
                                                                                    {
                                                                                        "isBackup":  false,
                                                                                        "managerLevel":  1,
                                                                                        "@odata.type":  "#microsoft.graph.requestorManager"
                                                                                    }
                                                                                ],
                                                           "isEscalationEnabled":  false
                                                       },
                                    "isApprovalRequired":  true
                                },
    "CanExtend":  false,
    "RequestorSettings":  {
                              "scopeType":  "AllExistingDirectoryMemberUsers",
                              "acceptRequests":  true
                          },
    "DisplayName":  "policy with access review"
}
```

**Comment by William-Francillette** [comment] 2022-12-14 20:23
I've rebuilt the hashtable manually, the nested hashtable is working but still have the ID issue

```
$hash=@{
    "Id"="cf691887-7f40-4a65-bff5-06ec75f9a583"
    "AccessReviewSettings"=@{
                                 "isEnabled"=$true
                                 "startDateTime"="11/22/2022 23:59:59"
                                 "isAccessRecommendationEnabled"=$true
                                 "accessReviewTimeoutBehavior"="removeAccess"
                                 "isApprovalJustificationRequired"=$true
                                 "recurrenceType"="quarterly"
                                 "reviewerType"="Self"
                                 "durationInDays"=25
                             }
    "DurationInDays"=360
    "Description"=""
    "RequestApprovalSettings"=@{
                                    "approvalMode"="SingleStage"
                                    "isRequestorJustificationRequired"=$true
                                    "isApprovalRequiredForExtension"=$false
                                    "approvalStages"=@{
                                                           "approvalStageTimeOutInDays"=14
                                                           "isApproverJustificationRequired"=$true
                                                           "escalationTimeInMinutes"=0
                                                           "primaryApprovers"=@(
                                                                                    @{
                                                                                        "isBackup"=$true
                                                                                        "id"="4fe9b98d-078d-4379-869d-0c673023ab81"
                                                                                        "@odata.type"="#microsoft.graph.singleUser"
                                                                                    }
                                                                                    @{
                                                                                        "isBackup"=$false
                                                                                        "managerLevel"=1
                                                                                        "@odata.type"="#microsoft.graph.requestorManager"
                                                                                    }
                                                                                )
                                                           "isEscalationEnabled"=$false
                                                       }
                                    "isApprovalRequired"=$true
                                }
    "CanExtend"=$false
    "RequestorSettings"=@{
                              "scopeType"="AllExistingDirectoryMemberUsers"
                              "acceptRequests"=$true
                          }
    "DisplayName"="policy with access review"
}


Set-MgEntitlementManagementAccessPackageAssignmentPolicy `
    -BodyParameter $hash `
    -AccessPackageAssignmentPolicyId $hash.Id -debug
```

```
DEBUG: [CmdletBeginProcessing]: - Set-MgEntitlementManagementAccessPackageAssignmentPolicy begin processing with parameterSet 'Set'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', AuthProviderType: 'ClientCredentialProvider', ContextScope: 'Process', AppName: 'M365DSC'.
DEBUG: [Authentication]: - Scopes: [Policy.Read.ConditionalAccess, DeviceManagementManagedDevices.Read.All, Policy.ReadWrite.ConditionalAccess, User.ReadWrite.All, RoleManagement.Read.Directory, Policy.ReadWrite.ApplicationConfiguration, Application.ReadWrite.All, Group.Read.All, Directory.ReadWrite.All, DeviceManag
ementServiceConfig.Read.All, Group.ReadWrite.All, Directory.Read.All, User.Read.All, Agreement.Read.All, DeviceManagementServiceConfig.ReadWrite.All, GroupMember.Read.All, Organization.ReadWrite.All, DeviceManagementConfiguration.Read.All, DeviceManagementManagedDevices.ReadWrite.All, User.ManageIdentities.All, Orga
nization.Read.All, RoleManagement.ReadWrite.Directory, GroupMember.ReadWrite.All, Policy.Read.All, DeviceManagementConfiguration.ReadWrite.All, Application.Read.All, DeviceManagementApps.ReadWrite.All, DeviceManagementApps.Read.All, EntitlementManagement.Read.All, EntitlementManagement.ReadWrite.All].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignmentPolicies/cf691887-7f40-4a65-bff5-06ec75f9a583

Headers:


Body:
{
  "id": "cf691887-7f40-4a65-bff5-06ec75f9a583",
  "description": "",
  "canExtend": false,
  "displayName": "policy with access review",
  "durationInDays": 360,
  "accessReviewSettings": {
    "accessReviewTimeoutBehavior": "removeAccess",
    "durationInDays": 25,
    "isAccessRecommendationEnabled": true,
    "isApprovalJustificationRequired": true,
    "isEnabled": true,
    "recurrenceType": "quarterly",
    "reviewerType": "Self"
  },
  "requestApprovalSettings": {
    "approvalMode": "SingleStage",
    "approvalStages": [],
    "isApprovalRequired": true,
    "isApprovalRequiredForExtension": false,
    "isRequestorJustificationRequired": true
  },
  "requestorSettings": {
    "acceptRequests": true,
    "scopeType": "AllExistingDirectoryMemberUsers"
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : b212fc45-a88a-4eef-95ff-bb0008042c0c
client-request-id             : b212fc45-a88a-4eef-95ff-bb0008042c0c
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"3","ScaleUnit":"000","RoleInstance":"LN2PEPF00009599"}}
Date                          : Wed, 14 Dec 2022 20:19:39 GMT

Body:
{
  "error": {
    "code": "ArgumentNullException",
    "message": "Value cannot be null.\r\nParameter name: Id",
    "innerError": {
      "date": "2022-12-14T20:19:40",
      "request-id": "b212fc45-a88a-4eef-95ff-bb0008042c0c",
      "client-request-id": "b212fc45-a88a-4eef-95ff-bb0008042c0c"
    }
  }
}


Set-MgEntitlementManagementAccessPackageAssignmentPolicy : Value cannot be null.
Parameter name: Id
At line:48 char:1
+ Set-MgEntitlementManagementAccessPackageAssignmentPolicy `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ AccessPackage...gnmentPolicy1 }:<>f__AnonymousType178`2) [Set-MgEntitleme...nmentPolicy_Set], RestException`1
    + FullyQualifiedErrorId : ArgumentNullException,Microsoft.Graph.PowerShell.Cmdlets.SetMgEntitlementManagementAccessPackageAssignmentPolicy_Set
DEBUG: [CmdletEndProcessing]: - Set-MgEntitlementManagementAccessPackageAssignmentPolicy end processing.
```

**Comment by peombwa** [comment] 2022-12-14 22:06
Could you try excluding the `id` from the request body since you are updating an entity and its `id` is already specified in `-AccessPackageAssignmentPolicyId` parameter (API path parameter). I'm not able to verify if this works as my test tenant does not have access to Azure AD entitlement management API:
``` powershell
$AccessPackageAssignmentPolicyId = "cf691887-7f40-4a65-bff5-06ec75f9a583"
$hash = @{
    "AccessReviewSettings"    = @{
        "isEnabled"                       = $true
        "startDateTime"                   = "11/22/2022 23:59:59"
        "isAccessRecommendationEnabled"   = $true
        "accessReviewTimeoutBehavior"     = "removeAccess"
        "isApprovalJustificationRequired" = $true
        "recurrenceType"                  = "quarterly"
        "reviewerType"                    = "Self"
        "durationInDays"                  = 25
    }
    "DurationInDays"          = 360
    "Description"             = ""
    "RequestApprovalSettings" = @{
        "approvalMode"                     = "SingleStage"
        "isRequestorJustificationRequired" = $true
        "isApprovalRequiredForExtension"   = $false
        "approvalStages"                   = @(
            @{
                "approvalStageTimeOutInDays"      = 14
                "isApproverJustificationRequired" = $true
                "escalationTimeInMinutes"         = 0
                "primaryApprovers"                = @(
                    @{
                        "isBackup"    = $true
                        "id"          = "4fe9b98d-078d-4379-869d-0c673023ab81"
                        "@odata.type" = "#microsoft.graph.singleUser"
                    }
                    @{
                        "isBackup"     = $false
                        "managerLevel" = 1
                        "@odata.type"  = "#microsoft.graph.requestorManager"
                    }
                )
                "isEscalationEnabled"             = $false
            })
        "isApprovalRequired"               = $true
    }
    "CanExtend"               = $false
    "RequestorSettings"       = @{
        "scopeType"      = "AllExistingDirectoryMemberUsers"
        "acceptRequests" = $true
    }
    "DisplayName"             = "policy with access review"
}

Set-MgEntitlementManagementAccessPackageAssignmentPolicy `
    -BodyParameter $hash `
    -AccessPackageAssignmentPolicyId $AccessPackageAssignmentPolicyId -debug
```

Please open a question/ticket at https://developer.microsoft.com/en-us/graph/support to get help from the API owner if the API still fails with the same error after excluding the `id` from the body. Please include the `request-id` and `date` in the question. This repository is intended for issues related to the functionality of the module and we may not be the best place to answer some queries that are tied to the functionality of the API.

**Comment by William-Francillette** [comment] 2022-12-15 19:37
Hi Peter,
It was me being silly, I was missing the accessPackageId in the BodyParameter 
I can confirm the cmdlet works as intended and that it works with and without adding the Id in BodyParameter

That can be close and thanks for your help and time
William

**Comment by peombwa** [comment] 2022-12-15 20:41
Sounds good! I'll close the issue.

**Closed by peombwa** 2022-12-15 20:41 UTC
Labels: question, Needs: Attention :wave:
