### ISSUE TITLE
PowerShell SDK is not showing the correct permissions or correct number of permissions

### ISSUE THREAD

**Issue by CarolKigoonya** [microsoftgraph/msgraph-sdk-powershell#2110] opened 2023-06-27 11:29 UTC
There are 2 different permission issues that have been identified
1) There are additional permissions being displayed for some cases e.g.
    On the SDK these are the permissions:
     
![Screenshot (143)](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/9033456/1e84db13-39b1-49fa-9953-9d3bcb736173)

    On the [API reference](https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http) these are the permissions shown:

![Screenshot (144)](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/9033456/63524343-6e25-4766-a7c0-bdde9f26a3fc)

2) There are plenty of gaps based on the stats:

Delegated: 417 in docs versus 292 in Find-MgGraphPermission
Application: 358 in docs versus 222 in Find-MgGraphPermission
Here is an example reported by the customer:

TeamworkTag.Read that exists in delegated mode but doesn't appear with the Find-MgGrapPermission.

**Comment by peombwa** [comment] 2023-06-30 18:54
@CarolKigoonya, this is a duplicate of https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1217 in DevX API. Permissions are fetched from DevX API. The gaps highlighted above exist in DevX API, not PowerShell SDK.

**Closed** 2023-07-07 20:02 UTC
Labels: Needs: Author Feedback, no-recent-activity
