### ISSUE TITLE
Update-MgServicePrincipalSynchronizationJobSchema ==> "No HTTP resource was found that matches the request URI https://syncfabric.windowsazure.com"

### ISSUE THREAD

**Issue by lockelost** [microsoftgraph/msgraph-sdk-powershell#1134] opened 2022-03-08 12:13 UTC
Hi,

While Get-MgServicePrincipalSynchronizationJobSchema works, the Update-MgServicePrincipalSynchronizationJobSchema does not work with the same Service Principal Id and Synchronization Job Id.

It says "No HTTP resource was found that matches the request URI".

But from the Graph API Explorer, works fine with the same parameters.

[](https://docs.microsoft.com/en-us/graph/api/synchronization-synchronizationschema-update?view=graph-rest-beta&tabs=http)

`Get-MgServicePrincipalSynchronizationJobSchema -ServicePrincipalId $servicePrincipal.Id -SynchronizationJobId $synchJob.Id`

```
Update-MgServicePrincipalSynchronizationJobSchema -ServicePrincipalId $servicePrincipal.Id -SynchronizationJobId $synchJob.Id
Update-MgServicePrincipalSynchronizationJobSchema : {"Message":"No HTTP resource was found that matches the request URI 'https://syncfabric.windowsazure.com/api/servicePrincipals('fa8f9754-d7a7-45 40-8132-5bfc2b7d15d8')/synchronization/jobs('customappssoOutDelta.3b92c35ead604f02b0a092e99c9991b0.d2569c8c-9511-4763-8bbb-ca5eca9a4903')/schema?api-version=2.0'."}
At line:1 char:1
+ Update-MgServicePrincipalSynchronizationJobSchema -ServicePrincipalId ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ServicePrinci...izationSchema }:<>f__AnonymousType83`3) [Update-MgServic..._UpdateExpanded], RestException`1
    + FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgServicePrincipalSynchronizationJobSchema_UpdateExpanded


```

**Comment by peombwa** [comment] 2022-04-01 22:12
Thanks for bringing this to our attention. TThe OpenAPI file (the SDK is generated from) currently describes the operation as `PATCH` instead of `PUT` as described in the API reference - https://docs.microsoft.com/en-us/graph/api/synchronization-synchronizationschema-update?view=graph-rest-beta&tabs=http#http-request.
``` powershell
➜ Find-MgGraphCommand -Command Update-MgServicePrincipalSynchronizationJobSchema | select Method, URI

Method URI
------ ---
PATCH  /servicePrincipals/{servicePrincipal-id}/synchronization/jobs/{synchronizationJob-id}/schema
```

We are already tracking the issue in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/783, and a fix will be provided soon.

As a workaround, you can use `Invoke-MgGraphRequest` to update a synchronization schema as shown below:
``` powershell
$uri = " https://graph.microsoft.com/beta/servicePrincipals/{id}/synchronization/jobs/{jobId}/schema"
Invoke-MgGraphRequest -Uri $uri -Method PUT -Body $bodyParameter
```

**Comment by peombwa** [comment] 2022-04-01 22:13
Closing as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/783

**Closed by peombwa** 2022-04-01 22:13 UTC
Labels: metadata-issue

**Comment by salbeck-sit** [comment] 2024-03-13 07:24
This issue has been closed and seen from an SDK viewpoint I tend to agree - but the OpenAPI issue still exists - almost 2 years later. Documentation for the Graph API says to use PUT but that doesn't appear to 'spill over'.

If this is not an API issue and not an SDK-issue due to a faulty OpenAPI description - then where to go ? The suggested workaround comes with its own challenge trying to figure out the complete body-param - it appears that you can't just piece together what you get back from the cmdlet implementing the GET-method.

Last, this issue may look like a duplicate of #783 (which is also closed) but on the API end these may be different issues if API-owners are different teams.
