### ISSUE TITLE
New-MgChat add only 98 users

### ISSUE THREAD

**Issue by guptarajesh001** [microsoftgraph/msgraph-sdk-powershell#1156] opened 2022-03-18 11:24 UTC
We are creating the team group chat by the powershell script to add more then 250 users
Version:
Microsoft.Graph.Teams: 1.9.2/1.9.3
PowerShell: 1.5.1

Code:
` ```
Connect-MgGraph -ClientId $clientId -TenantId $tenantID -Certificate "$ScriptPath\testCert.pfx"
$groupJSONBodies = @{
    "chatType":  "group",
    "topic":  "ITGroup",
    "members":  @[
                    @{
                        "@odata.type":  "#microsoft.graph.aadUserConversationMember",
                        "roles":  ["owner"],
                        "user@odata.bind":  "https://graph.microsoft.com/v1.0/users/316c7b00-0d17-418f-b9ce-3c0976319734"
                    },
                    @{
                        "@odata.type":  "#microsoft.graph.aadUserConversationMember",
                        "roles":  ["owner"],
                        "user@odata.bind":  "https://graph.microsoft.com/v1.0/users/e4d4db5e-2531-4e12-89e3-099800a5c723"
                    },
                    @{
                        "@odata.type":  "#microsoft.graph.aadUserConversationMember",
                        "roles":  ["owner"],
                        "user@odata.bind":  "https://graph.microsoft.com/v1.0/users/232cc001-ad50-46c7-954e-b7e7491e9553"
                    }
					...... #400 users information
                ]
}

 $chatId = New-MgChat -BodyParameter $groupJSONBodies
```
`But it's add only 98 users, even I can't add members in groups or batchs from Add-MgChatMember -ChatId or New-MgChatMember -ChatId

**Comment by peombwa** [comment] 2022-03-18 23:21
Closing as duplicate of #1154. Let's discuss this in #1154 as my response still applies here.

**Closed by peombwa** 2022-03-18 23:21 UTC
Labels: ToTriage
