### ISSUE TITLE
Only generate navigation properties for those that can be expanded

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#89] opened 2020-01-21 20:08 UTC
Having navigation properties in models that do not support expand, is redundant as they will always be null.
We need to add expand capability annotations to the metadata, so that OpenAPI has only the actual expand properties. 
[AB#7437](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7437)

**Comment by MIchaelMainer** [comment] 2020-01-21 20:54
We will need a separate transform for PowerShell that will remove all navigation properties where ExpandRestrictions has Expandable = false. This will also be applicable to model only generation scenarios like PHP, Typescript (for now), Objective-C, and Python (what's currently supported in the generator).

        <Annotation Term="Org.OData.Capabilities.V1.ExpandRestrictions">
          <Record>
            <PropertyValue Property="Expandable" Bool="false" />
          </Record>
        </Annotation>

**Comment by peombwa** [comment] 2022-12-14 19:24
Closing as duplicate of https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/377.

**Closed by peombwa** 2022-12-14 19:24 UTC
Labels: enhancement, P2, OpenApiService-Dependency
