### ISSUE TITLE
Cannot list Service Principals of an App

### ISSUE THREAD

**Issue by Tbohunek** [microsoftgraph/msgraph-sdk-powershell#1290] opened 2022-05-27 15:08 UTC
`Get-MgServicePrincipal` doesn't take `-applicationId`, which makes it impossible to list Service Principals of an App.
On contrary, `Get-MgApplication` only takes `-applicationId` but does not take `-objectId`.
This limits possible usage.

Why do `Get-MgServicePrincipal` and `Get-MgApplication` require specific parameter names `-serviceprincipalId` and `-applicationId` rater than generic `-objectId` as was the case with `Get-AzAdServicePrincipal` and `Get-AzAdApplication`?

**Comment by ddyett** [comment] 2022-06-16 15:58
this looks like a consequence of the Graph service design.  Looking for team to provide feedback.

**Comment by dani3lheidemann** [comment] 2022-08-26 09:39
Hi @Tbohunek,
just stumbled across the same problem. Solved it by using Filter option like this:

```powershell

# For Service Principal
Get-MgServicePrincipal -Filter "AppId eq '64ebc126-26b2-4cda-9eb0-e6bcf50aa987'"

# For App Registration
Get-MgApplication -Filter "Id eq '86143777-9b2e-40d1-a045-0468ae918051'" # --> where 'id' is objectId

```

Does this solve your problem?
Greetings
Daniel

**Comment by Tbohunek** [comment] 2022-08-26 11:48
Ohh, the `-filter`s... I hope they'd die with onprem Active Directories. 😉 

Thanks @dani3lheidemann , it works, but is that the solution we want as final?

**Comment by dani3lheidemann** [comment] 2022-08-29 05:52
@Tbohunek yeah it's absolutely different from what we got with AzureAD PowerShell modules.
I hope they put some parameters in as well!

**Comment by wsmelton** [comment] 2022-08-31 15:58
I have one app registration created and only way to have it returned is to use the filter on AppId. It has no Enterprise Application associated with it, which seems to be only thing the command returns with no parameters.

![image](https://user-images.githubusercontent.com/11204251/187724293-3e8f1e34-44a5-44d3-81c3-246e48ad5240.png)

**Comment by Tbohunek** [comment] 2023-04-14 09:13
Thanks for your explanations @peombwa, makes sense! However..

>You cannot have duplicate parameter names on a command in PowerShell..

Can you not translate the display name of a parameter (requested from user) to the real parameter sent to API?
`-objectID` would map to `{applicationId}` and `{serviceprincipalId}` respectively in each PS command?

**Comment by peombwa** [comment] 2023-04-18 23:21
Duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/906.

**Closed** 2023-04-19 09:18 UTC
Labels: Needs: Author Feedback
