### ISSUE TITLE
Documentation is missing/broken

### ISSUE THREAD

**Issue by seanmcne** [microsoftgraph/msgraph-sdk-powershell#369] opened 2020-09-14 19:58 UTC
![image](https://user-images.githubusercontent.com/2292260/93132099-b4fb8380-f69a-11ea-8f91-9a56a1fe1f89.png)
 
[AB#7390](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7390)

**Comment by PsychoData** [comment] 2021-02-17 17:41
Duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/257

**Closed** 2021-05-11 19:08 UTC
Labels: Bug: Documentation, promote
