### ISSUE TITLE
Get-MgSubscribedSku outputs a SkuPartNumber with extra characters

### ISSUE THREAD

**Issue by bbrownchg** [microsoftgraph/msgraph-sdk-powershell#2323] opened 2023-09-25 15:39 UTC
When running `Get-MgSubscribedSku` to grab all licenses available in my tenant, an extra, unknown, character is getting appended to the end of the CPC_E_2C_8GB_128GB SkuPartNumber.

In the console output of `Get-MgSubscribedSku | Select-Object SkuPartNumber` there is no obvious extra character, as seen below:

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/47155353/27b9d1bb-846b-4689-8ffc-8f4719404463)

Exporting the results to CSV shows something being added on to the end:

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/47155353/50867e21-1826-4580-a94e-cc05ec8c9614)

Running `Get-MgSubscribedSku | where {$_.skupartnumber -eq "CPC_E_2C_8GB_128GB"}` returns no results, whereas `Get-MgSubscribedSku | where {$_.skupartnumber -like "CPC_E_2C_8GB_128GB*"}` does return an object.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/47155353/197aa29e-1df6-493f-ae13-4d2f60ff2741)

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/47155353/db609af6-5251-40e1-b82f-f42f82f38ebd)

Running the same query using an HTTP call via `https://graph.microsoft.com/v1.0/subscribedSkus` does not appear to show the extra character.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/47155353/2784e067-be76-4ec8-8ce2-80ea63cea50a)

Based on this incorrectly filed issue, https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8606, the extra character was identified as a zero-width space.

This is causing issues with matching SKU names to friendly names in automation scripts.

**Comment by SeniorConsulting** [comment] 2023-09-26 00:54
Hi bbrownchg,

Did this just affect the Cloud PC license? i.e. CPC_E_2C_8GB_128GB?

I've conducted some testing, and have found that the other ones seem to be OK:

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/dfaa8048-9f7c-4083-895d-515c91c80b63)

However, I have replicated this issue on the Cloud PC SKU:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/4da3d3e8-3930-427d-be0b-bd8cc9621fdf)

I think this may actually be a service issue, rather than an issue with the module

FYI - this also seems to affect the other Cloud PC SKU:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/5395e64c-3e72-4674-8930-cb305021d044)

**Comment by SeniorConsulting** [comment] 2023-09-26 01:07
Confirmed that it's a service issue via the debug command!

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/d913b900-b995-4954-8393-e16f335e1bab)

**Comment by bbrownchg** [comment] 2023-09-26 01:19
> Confirmed that it's a service issue via the debug command!
> 
> ![image](https://user-images.githubusercontent.com/110941550/270506847-d913b900-b995-4954-8393-e16f335e1bab.png)

I see that now, good catch. Doing the HTTP call and converting to JSON also shows me the extra character that I wasn't seeing before using the Graph Explorer.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/47155353/b4ac62a6-28ea-491d-b14e-7bd40aed6358)

Hopefully someone can help us get this logged to the correct team!

**Comment by peombwa** [comment] 2023-09-26 16:54
Thanks @SeniorConsulting for helping identify the root cause of the issue!

@bbrownchg, please open a ticket at https://developer.microsoft.com/graph/support with the `request-id` and `date` of the affected request as this is an issue with the service returning incorrect results. See https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug.

**Comment by bbrownchg** [comment] 2023-09-26 17:58
Thank you, @peombwa. I have opened a case in my Azure subscription, ID 2309260040011228 if it helps.

**Comment by peombwa** [comment] 2023-09-26 18:48
Awesome! Closing the issue in the repo as this is an issue with the service, not the SDK.

**Closed by peombwa** 2023-09-26 18:48 UTC
Labels: Service issue, Needs: Attention :wave:

**Comment by bbrownchg** [comment] 2023-10-19 12:52
FYI for @peombwa @SeniorConsulting and anyone else that happens to find this thread, MS support got back to me with unfortunate news:

> Hi Brandon,
The Product Group was able to identify where the extra characters come from.  Unfortunately they would not be able to take a fix for this since it would impose a huge compatibility risk.  Due to the way it’s designed, the part number is immutable in all systems since it directly ties to the services on these product SKUs.  They can not be changed or the customers who have purchased these will break.  This behavior has been in market for over 2 years. The product group advised whichever system can’t handle these characters is going to need to make adjustment to handle them.

**Comment by bbrownchg** [comment] 2025-05-13 16:47
> Hi, I ran into this issue today. Im using a hashmap to convert the SkuPartNumbers into the actual names. If anyone is wondering, I solved it by adding the zero-width space to my hashmap keys for these two W365 part numbers like this:
> 
> `"CPC_E_2C_8GB_128GB$([char]0x200B)"`
> 
> If you compare this string above with the SkuPartNumber output string, they will equal. My hashmap works again after this change.

Great idea! Thanks for sharing!
