### ISSUE TITLE
These PIM cmdlets have been generated in the wrong module, device management instead of directory management.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#1322] opened 2022-06-15 13:15 UTC
Wondering to test this in case it's the case for other cmdlets.

![image](https://user-images.githubusercontent.com/73849846/173835736-1fbdbeff-7d28-42d6-8e46-df31c2a8bfe9.png)

**Comment by peombwa** [comment] 2022-06-20 23:31
Thanks for bringing this to our attention. We are already tracking this in #946. As stated in #946, moving these commands to the right module would constitute a breaking change. We will review the current module in v2 of the SDK.

@maisarissi, can you follow up with AGS/workload to figure out the right module mapping for Intune APIs. The old model was based on the TOC, which has changed since we last reviewed the mapping.

**Comment by peombwa** [comment] 2022-06-20 23:32
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/946.

**Closed by peombwa** 2022-06-20 23:31 UTC
Labels: ToTriage
