### ISSUE TITLE
Get-MgUser | Output property 'BusinessPhones' should be 'BusinessPhone' according the "IMicrosoftGraphUser Interface" definition

### ISSUE THREAD

**Issue by Rowan-Ramasray** [microsoftgraph/msgraph-sdk-powershell#1675] opened 2022-12-12 15:39 UTC
When getting a user with the "Get-MGUser" command you get the property "BusinessPhones", but this should be "BusinessPhone" according the "IMicrosoftGraphUser Interface" definition (https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.powershell.cmdlets.resources.msgraph.models.apiv10.imicrosoftgraphuser?view=az-ps-latest). 

In my case i can't use the object from Get-MGuser for the cmdlet "Update-MgDeviceManagementManagedDevice -users" because this cmdlet leans on the IMicrosoftGraphUser definition. I need to update the primary user of a managed device. 

How to repo?
```Powershell
$userobj = Get-MgUser -UserId {UserID}
Update-MgDeviceManagementManagedDevice -ManagedDeviceId {DeviceID} -users $userobj
```

Error:
```Powershell
Update-MgDeviceManagementManagedDevice_UpdateExpanded1: The property 'businessPhones' does not exist on type 'microsoft.management.services.api.user'. Make sure to only use property names that are defined by the type.
```

Can somebody fix this or create a new cmdlet like in #1404?

**Comment by peombwa** [comment] 2022-12-12 17:30
The `IMicrosoftGraphUser` link provided above is for Azure PowerShell.

This module calls Microsoft Graph REST API. In Microsoft Graph, a user resource type has `businessPhones` property (string collection). This is what `Get-MgUser` returns - https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties. You can create an intermediate object with `businessPhone` using the output from `Get-MgUser`.

Please open an API question at https://developer.microsoft.com/en-us/graph/support to get assistance from the API owner on the proper way to update a managed device user.

**Comment by peombwa** [comment] 2022-12-12 17:31
Closing as by design. The API returns `BusinessPhones`.

**Closed by peombwa** 2022-12-12 17:31 UTC
