### ISSUE TITLE
Having difficulties setting 'photo' of a Team

### ISSUE THREAD

**Issue by JvdH-NL** [microsoftgraph/msgraph-sdk-powershell#426] opened 2020-10-10 20:45 UTC
Trying to use Update-MgTeamPhoto to set a team photo. Assuming I need to fill BodyParameter with Image (Byte array). However stuck at ' Missing an argument for parameter 'BodyParameter'. Specify a parameter of type 'Microsoft.Graph.PowerShell.Models.IMicrosoftGraphProfilePhoto' and try again.' 
Should this command already be working (saw open issue on setting photo's) and how should I fill BodyParameter?

**Comment by peombwa** [comment] 2020-10-21 22:42
@JvdH-NL sorry about that. Upload and downloads of files are currently not supported. We will be supporting this in our next release. Duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/54

**Closed by peombwa** 2020-10-21 22:42 UTC

**Comment by JvdH-NL** [comment] 2020-10-22 17:39
Thanks for clarification. I switched to "Invoke-MgGraphRequest -Method PUT -Uri $RequestURL -Body $PhotoBinary -ContentType "image/jpeg" to get this working ok.
