### ISSUE TITLE
Get-MgSubscribedKu commandlet does not expand PrepaidUnits property

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/msgraph-sdk-powershell#1591] opened 2022-10-25 19:20 UTC
PS C:\Users\bachoang> Get-MgSubscribedSku | FL

AppliesTo            : Company
CapabilityStatus     : Enabled
ConsumedUnits        : 0
Id                   : aa00d1fa-5269-4e1c-b06d-30868371d2c5_6470687e-a428-4b7a-bef2-8a291ad947c9
PrepaidUnits         : Microsoft.Graph.PowerShell.Models.MicrosoftGraphLicenseUnitsDetail
ServicePlans         : {EXCHANGE_S_FOUNDATION, WINDOWS_STORE}
SkuId                : 6470687e-a428-4b7a-bef2-8a291ad947c9
SkuPartNumber        : WINDOWS_STORE
AdditionalProperties : {}

Expected Behavior:
PrepaidUnits property should be expanded to show the values

Actual Behavior:
the commandlet shows the type for 'PrepaidUnits' 

The underlying MS Graph REST call does return the json data having PrepaidUnits data

**Comment by hwacookie** [comment] 2022-10-31 08:48
Hello bachoang,

I am aware that this is kind of off-topic, but maybe you could help me out: I'm looking exactly for the REST API endpoint that returns the same stuff that Get-MgSubscribedKu returns. I'm sure there's a mapping from all PowerShell commands to their corresponding REST endpoints somewhere, but I'm to blind to find it. I'd appreciate any hints.

Thank you!

Hauke

**Comment by hwacookie** [comment] 2022-10-31 09:04
Ahhh, I just KNEW it would help to write this comment, because obviously it took just ten more minutes to stumble upon this very useful command:

Find-MgGraphCommand -Command 'Get-MgSubscribedSku'

shows the URL that is queried for the command. I'll leave this here in case it helps someone else.

**Comment by peombwa** [comment] 2022-10-31 16:10
@bachoang, the commands in this module return .NET objects. PowerShell does not expand class type properties of an object.

As with any PowerShell command that produces an output, the cmdlets in this module can be piped to the [Get-Member](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-member) cmdlet to determine what type of an object is produced along with a list of the available properties and methods. You can then pipe the output to PowerShell's [Select-Object](https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Select-Object?view=powershell-7.2) to select the properties you are interested in. See https://learn.microsoft.com/en-us/powershell/azure/queries-azureps?view=azps-9.0.1 for more details.

@hwacookie, you can also find the documentation on `Find-MgGraphCommand` at https://learn.microsoft.com/en-us/powershell/microsoftgraph/find-mg-graph-command?view=graph-powershell-1.0.

**Comment by peombwa** [comment] 2022-10-31 16:11
Closing as by design. See https://github.com/microsoftgraph/msgraph-sdk-powershell#known-issues.

**Closed by peombwa** 2022-10-31 16:11 UTC
Labels: question
