### ISSUE TITLE
Microsoft Graph Powershell app is unverified

### ISSUE THREAD

**Issue by pschaeflein** [microsoftgraph/msgraph-sdk-powershell#468] opened 2020-11-18 16:12 UTC
![image](https://user-images.githubusercontent.com/8008013/99555989-92316800-2986-11eb-9464-3a401c45690b.png)
 
[AB#7377](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7377)

**Comment by covingto** [comment] 2020-11-27 16:35
Hello,

I'm not sure if this is related, but I am unable to follow the examples in the README with a personal account.
The graph powershell module is installed on my machine.

Calling Connect-MgGraph seems to work logging in with my personal me@outlook.com account.


```
Connect-MgGraph -Scopes "User.Read.All","Calendars.Read","User.Read","User.ReadBasic.All"
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXX to authenticate.
Welcome To Microsoft Graph!
```

However, a call to Get-MgUser results in another signin request and then fails after sign-in

```
Get-MgUser
To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code XXX to authenticate.
Get-MgUser_List1: Code: generalException
Message: Unexpected exception returned from MSAL.
```

When I have attempted register apps in Azure to try to access Graph in other ways there is a warning that unverified apps will not be able to use multitennant authentication.

Please do let me know if there are some settings that I am not using correctly.

Thanks

**Comment by PsychoData** [comment] 2021-02-17 17:24
> Hello,
> 
> I'm not sure if this is related, but I am unable to follow the examples in the README with a personal account.
@covingto This should be a [separate Issue](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/new)

**Comment by PsychoData** [comment] 2021-02-17 17:25
Duplicate https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/449

**Comment by peombwa** [comment] 2021-04-15 18:49
Closing as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/468

**Closed by peombwa** 2021-04-15 18:49 UTC
Labels: promote
