### ISSUE TITLE
Get-MgPlace throws InvalidOperation error when using a valid filter

### ISSUE THREAD

**Issue by jetedoff** [microsoftgraph/msgraph-sdk-powershell#1313] opened 2022-06-08 14:25 UTC
Get-MgPlace works for finding an individual PlaceID value, but when filtering for it there is an error:
Get-MgPlace : An error has occurred.
At line:1 char:1
Get-MgPlace -Filter "DisplayName eq 'Room200'"
CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType22`8) [Get-MgPlac
e_List], RestException`1
FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgPlace_List
![image](https://user-images.githubusercontent.com/100362694/172640519-66cf811f-9da3-4fa5-baef-eba9e78e24e2.png)

The equivalent operation works fine in Graph Explorer:
https://graph.microsoft.com/v1.0/places/microsoft.graph.room?$filter=DisplayName eq 'Room200'
![image](https://user-images.githubusercontent.com/100362694/172641481-162ba1ee-b25c-4a21-b57c-e53895e1e0ed.png)

**Comment by peombwa** [comment] 2022-06-13 23:49
Thanks for bringing this to our attention. We are already the issues in #423.

Closing as duplicate of #423.

**Closed by peombwa** 2022-06-13 23:49 UTC
Labels: ToTriage
