### ISSUE TITLE
BUG: Get-MgChat and Get-MgUserChat,  -All or -pagesize  gives  "the limit of 50 for Top query has been exceeded."

### ISSUE THREAD

**Issue by mbourgon** [microsoftgraph/msgraph-sdk-powershell#1248] opened 2022-05-07 01:08 UTC
Howdy! I just started trying to use MG cmdlets.  I'm trying to get all my messages in the last week, from any chat I'm in.  
However, I immediately ran into what appears to be a bug - only a max of 50 are supported. Unfortunately, I need all - I can't filter on LastUpdatedDateTime since that's when something about the channel was changed, not the last message. Which means I need to look at all chats.  (if there's a way to just look at all messages, maybe that would work?)

```
PS> get-mgchat -all
Get-MgChat_List1: The query specified in the URI is not valid. The limit of '50' for Top query has been exceeded. The value from the incoming request is '100'.

PS> get-mguserchat  -UserId "my-user-id-guid-here" -pagesize 300
Get-MgUserChat_List1: The query specified in the URI is not valid. The limit of '50' for Top query has been exceeded. The value from the incoming request is '300'.
PS> get-mguserchat  -UserId "my-user-id-guid-here" -All
Get-MgUserChat_List1: The query specified in the URI is not valid. The limit of '50' for Top query has been exceeded. The value from the incoming request is '100'.
```

**Comment by peombwa** [comment] 2022-05-10 15:00
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1224.

**Closed by peombwa** 2022-05-10 15:00 UTC

**Comment by mbourgon** [comment] 2022-05-11 20:07
@peombwa thanks, that worked, thanks! It was so damn odd that just doing "-all" threw an odd error message, that I created this ticket. (plus, I needed to get all messages.)  Appreciate the help, just trying to figure out how to keep others from having the same problem.
