### ISSUE TITLE
Update-MgPolicyAuthorizationPolicy some command doesn't work

### ISSUE THREAD

**Issue by Hyamyam** [microsoftgraph/msgraph-sdk-powershell#2026] opened 2023-05-20 00:26 UTC
Hi team,

I tried to run the following command, it's successful. (changing false to true)

```powershell
Update-MgPolicyAuthorizationPolicy -AllowEmailVerifiedUsersToJoinOrganization
Update-MgPolicyAuthorizationPolicy -AllowedToSignUpEmailBasedSubscriptions
```

But when changing true to false, the `$false` input is not allowed.

```powershell
Update-MgPolicyAuthorizationPolicy -AllowedToSignUpEmailBasedSubscriptions -AdditionalProperties $False

-> Update-MgPolicyAuthorizationPolicy : No positional parameter found that accepts the argument 'False'.
Place row:1 character:1
+ Update-MgPolicyAuthorizationPolicy -AllowedToSignUpEmailBasedSubscrip ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-MgPolicyAuthorizationPolicy]、ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Update-MgPolicyAuthorizationPolicy
```

On the other hand, the way using `-BodyParameter' is successful.

```powershell
$params=@{
    AllowEmailVerifiedUsersToJoinOrganization = $false
    AllowedToSignUpEmailBasedSubscriptions = $false
}

Update-MgPolicyAuthorizationPolicy -BodyParameter $params
```

Is it correct the explanation in the [docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/update-mgpolicyauthorizationpolicy?view=graph-powershell-1.0&preserve-view=true)?
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/73410575/7584675e-451a-453c-970b-0c567165f9b1)

**Comment by peombwa** [comment] 2023-05-23 19:37
Hello!

`-AllowEmailVerifiedUsersToJoinOrganization` and `-AllowedToSignUpEmailBasedSubscriptions` are [switch parameters](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.3#switch-parameter-design-considerations). With switch parameters, you can use `-<switchname>:$false` to set the switch parameters to false. See the explanation at https://github.com/Azure/autorest.powershell/issues/1040#issuecomment-1352442281 for more details.

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/748.

**Closed by peombwa** 2023-05-23 19:37 UTC
Labels: Question: SDK
