### ISSUE TITLE
[Feature Request] Connect-MgGraph with managedIdentity

### ISSUE THREAD

**Issue by MichaMican** [microsoftgraph/msgraph-sdk-powershell#1216] opened 2022-04-14 14:43 UTC
With managedIdentity MS introduced a safe way to connect to the MS Graph and other Azure Resources from Azure Resources.

The Az module already features a `-Identity` switch property to use the managedIdentity. You actualy can get a Graph accesstoken through `Get-AzAccessToken`. But stuff like accesstoken refreshing does obviously not work if i use `Connect-MgGraph -AccessToken (Get-AzAccessToken)`.

It would be awesome to have that `-Identity` switch parameter in the MgGraph aswell, which also handles the token refresh via refreshtoken or via re acquiration of the token

**Comment by peombwa** [comment] 2022-04-20 17:55
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/721.

**Closed by peombwa** 2022-04-20 17:55 UTC
