### ISSUE TITLE
Please include the ability to optionally specify which azure environment to connect/authenticate to

### ISSUE THREAD

**Issue by mercuryjlt** [microsoftgraph/msgraph-sdk-powershell#311] opened 2020-08-04 19:19 UTC
We are trying to explore the use of Microsoft.Graph in one of the other sovereign regions and have not been able to find a way to do this. The trigger consent in Connect-Graph seems to be hard-coded to https://graph.microsoft.com/v1.0/me  and does not allow for other graph endpoints detailed here: https://docs.microsoft.com/en-us/graph/deployments

Having an -EnvironmentName input would be awesome!

Examples from other PowerShell modules
-------------------------
Connect-AzureAD -AzureEnvironmentName

-AzureEnvironmentName
Specifies the name of the Azure environment. The acceptable values for this parameter are:

AzureCloud
AzureChinaCloud
AzureUSGovernment
AzureGermanyCloud

-------------------------
Connect-AzAccount  -Environment
-Environment
Environment containing the Azure account.  (Accepts the same values as Connect-AzureAD)

-------------------------
Connect-ExchangeOnline -ExchangeEnvironmentName O365USGovGCCHigh

-ExchangeEnvironmentName
The ExchangeEnvironmentName specifies the Exchange Online environment. Valid values are:

O365China
O365Default (this is the default value)
O365GermanyCloud
O365USGovDoD
O365USGovGCCHigh

**Comment by peombwa** [comment] 2020-08-06 18:08
This scenario is currently not supported. We plan to add support for sovereign clouds after our GA release for the public cloud.

Duplicate of #93

**Closed by peombwa** 2020-08-06 18:08 UTC
