### ISSUE TITLE
Can’t use ExchangeOnlineManagement V3.1.0 together with Microsoft.Graph.Authentication V1.27.0 in powershell

### ISSUE THREAD

**Issue by goldenplayer5630** [microsoftgraph/msgraph-sdk-powershell#2042] opened 2023-05-26 19:15 UTC
**Can’t use ExchangeOnlineManagement V3.1.0 together with Microsoft.Graph.Authentication V1.27.0 in powershell**

I’m having some trouble with using the ExchangeOnlineManagement V3.1.0 together with Microsoft.Graph.Authentication V1.27.0 in powershell. Both modules work perfectly independent from eachother, but when I want to use them both in the same script, the following error occurs: `“Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.22.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)”`.

The exception occurs when I try to use the following cmdlet from the ExchangeOnlineManagement v3.1.0 module:

`” Connect-ExchangeOnline -Organization $VerifiedDefaultDomain -AppId $AppId -Certificate $CertObject”`

As you can see, I am using app only authentication using certificates. This command does work with the 2.0.5 version of ExchangeOnlineManagement in combination with Microsoft.graph.authentication, but as soon as I try to use the 3.1.0 version of the  ExchangeOnlineManagement, it stops working.

I think there is an version conflict between the two assemblies, because when the error occurs, and I run this command: `“[System.AppDomain]::CurrentDomain.GetAssemblies() | Where-Object Location | Sort-Object -Property FullName | Select-Object -Property FullName, Location, GlobalAssemblyCache, IsFullyTrusted | Out-GridView”then I can see that the version of 'System.IdentityModel.Tokens.Jwt that is actually used, is 5.6.0.0 but the ExchangeOnlineManagement 3.1.0 module requires 6.22.1.0`.  

So what do we have now? We have 2 modules that both require different versions of the same code assembly in order for certificate authentication to work.

`ExchangeOnlineManagement V3.1.0 = System.IdentityModel.Tokens.Jwt V6.22.1.0`

`Microsoft.Graph V.1.27.0 = System.IdentityModel.Tokens.Jwt V5.6.0.0`

Ofcourse you can’t use both assemblies in the same environment, because the runtime wouldn’t know which one to use when. I think this is something that Microsoft should fix in their Microsoft.Graph.Authentication module. I believe they should update the System.IdentityModel.Tokens.Jwt assembly in their module.  

Can someone tell me how to fix this, or can Microsoft acknowledge this issue and confirm that they are working on it? Feel free to contact me!

**Comment by DirtyMongoose** [comment] 2023-06-05 16:14
I have the same issue.  Given Graph cannot manage Exchange resources I guess we just go back to Az?  Disappointing since everything is pointing in the direction of moving to Graph.

**Comment by athornfam2** [comment] 2023-06-05 16:20
Had the same issue myself.

**Comment by peombwa** [comment] 2023-06-09 16:32
Thanks for following through on this and sorry for the delayed response.

> The exception occurs when I try to use the following cmdlet from the ExchangeOnlineManagement v3.1.0 module:
> ” Connect-ExchangeOnline -Organization $VerifiedDefaultDomain -AppId $AppId -Certificate $CertObject”

> “Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.22.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)”

As you've pointed out above, the issue is with how `ExchangeOnlineManagement` handles its dependencies. The module owner will need to implement a custom ALC, which this module has, to handle side by side loading of different assembly versions as stated at https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.3. `System.IdentityModel.Tokens.Jwt V5.6.0.0` is required by a downstream dependency in v1.

As workaround, you can consider [upgrading to v2](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/features/2.0/docs/upgrade-to-v2.md) (currently in RC status)? We've dropped the dependency on `System.IdentityModel.Tokens.Jwt` in v2 - https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1862.

**Closed** 2023-06-16 19:03 UTC
Labels: Needs: Author Feedback, no-recent-activity, External
