### ISSUE TITLE
Intune APIs - Missing, or Out of Scope?

### ISSUE THREAD

**Issue by gabrieljtaylor** [microsoftgraph/msgraph-sdk-powershell#455] opened 2020-11-09 15:13 UTC
The Intune APIs (devices & apps) don't seem to be included within this project right now, or at least whenever I've installed the Microsoft.Graph PowerShell module from the Gallery, none of the dependency modules seem to include any of the Intune APIs. I am uncertain if they are intentionally out of scope of this project, awaiting development and inclusion in this project, or if I'm having an issue with the module deployment. I've looked through all the historical issues here and haven't found anything clearly stating that the Intune APIs are out of scope, so I'm opening this issue as a question in hopes of gaining clarity.

I've installed the Microsoft.Graph module using the following command:
`Install-Module Microsoft.Graph -AllowClobber -Force`

The various Microsoft.Graph.* modules that are installed do not possess any cmdlets for interacting with the DeviceManagement APIs, though, nor most other Intune APIs. The only Devices modules that are installed are Microsoft.Graph.Devices.CloudPrint and Microsoft.Graph.Devices.CorporateManagement; the latter has cmdlets for _DeviceApps_, but not managed Devices.

I am aware of the separate project, [Microsoft.Graph.Intune](https://github.com/Microsoft/Intune-PowerShell-SDK), but that module hasn't been updated in almost a year and a half and is woefully out of date. It doesn't cover any of the newer APIs and lacks a lot of data that the raw APIs return. For my use cases, it is insufficient. I came here hoping to find a better module ready to go so I don't have to write my own functions to interact with Graph. Though I'm willing to go that route if I have to, I'd rather not reinvent the wheel.

Can anyone provide insight into what the official direction is for PowerShell and the Intune APIs? Thanks in advance.

**Comment by peombwa** [comment] 2020-11-10 17:41
This is in the works and will be available soon. We are tracking this under https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/432

Duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/432

**Closed by peombwa** 2020-11-10 17:41 UTC
Labels: ToTriage
