### ISSUE TITLE
Get-MgUserOwnedDevice returns device metadata as "AdditionalProperties" instead of direct Device properties

### ISSUE THREAD

**Issue by ZachEdwards7** [microsoftgraph/msgraph-sdk-powershell#1702] opened 2022-12-21 00:01 UTC
Get-MgUserOwnedDevice does not return a Device object, it returns a generic graph object with all the important Device attributes returned in AdditionalProperties
![image](https://user-images.githubusercontent.com/44238312/208789541-dbe004b1-3d60-4cf6-a3f8-addea08eff07.png)

I would expect to see the same "Device" type object returned as Get-MgDevice works
![image](https://user-images.githubusercontent.com/44238312/208789739-7c6ec01d-a635-4548-84e8-54569a6c25cf.png)

**Comment by peombwa** [comment] 2022-12-21 00:28
This is a known limitation with the module. The service describes the [API response as a collection of directoryObject](https://learn.microsoft.com/en-us/graph/api/user-list-owneddevices?view=graph-rest-1.0&tabs=http#response) (only has Id and DeletedDateTime properties). The command returns response a directory object with non-directoryObject properties stored in the AdditionalProperties. `AdditionalProperties` can be used as a PowerShell hashtable to access returned properties.

The limitation is being tracked under https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/19.

**Comment by peombwa** [comment] 2022-12-21 00:32
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/19. OData cast/discriminator support is currently planned for v3 milestone.

Customers can access the properties of the derived types via `AdditionalProperties` hashtable.

**Closed by peombwa** 2022-12-21 00:32 UTC
Labels: ToTriage
