### ISSUE TITLE
HowTo / Sample to reply to a mail

### ISSUE THREAD

**Issue by Julien-Des** [microsoftgraph/msgraph-sdk-powershell#749] opened 2021-07-09 13:07 UTC
Hi,

I am struggeling to reply to a mail with Graph (SDK powershell) and cannot find samples on internet.
Do you have some to share ?

I have tried New-MgUserMessageReply, New-MgUserMessageReplyAll and New-MgUserMailFolderMessageReplyAll that have to return a Microsoft.Graph.PowerShell.Models.IMicrosoftGraphMessage1 according to the [doc](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.users.actions/new-mgusermessagereply?view=graph-powershell-beta#outputs)
-> the output of these functions is always empty

My code
```
$resp = New-MgUserMessageReply -MessageId $mail.Id -Message $Message -UserId $UserId
Send-MgUserMessage -MessageId $resp.Id -UserId $UserId
```

The output
```
Send-MgUserMessage: Cannot bind argument to "MessageId" parameter because it is an empty string. 
Send-MgUserMessage -MessageId $resp.Id -UserId $UserId
CategoryInfo          : InvalidData : (:) [Send-MgUserMessage], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Send-MgUserMessage
```
 
[AB#10173](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10173)

**Comment by Julien-Des** [comment] 2021-08-06 15:13
More details for how do I get the $mail :
$mailsTODO = Get-MgUserMailFolderMessage  -All -userid $UserId -MailFolderId $folderTODO
 
```
foreach ($mail in $mailsTODO)
{   
    $resp = New-MgUserMessageReply -MessageId $mail.Id -Message $Message -UserId $UserId
    Send-MgUserMessage -MessageId $resp.Id -UserId $UserId
...
```
When I access to the $mail.Subject, it works perfectly, the subject is correct

**Comment by peombwa** [comment] 2021-11-20 00:46
Thanks for bringing this to our attention. The HTTP status code returned by the service (`201`) does not match what is specified in the OpenAPI document that this SDK is generated from (`200`).  We are already tracking status code mismatch issues [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/907), and a fix will be provided by https://github.com/Azure/autorest.powershell/issues/853.

A workaround is to use `Invoke-MgGraphRequest` to create a draft message as we wait for a fix in the code generator.
``` powershelll
$resp = Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/v1.0/users/$userId/messages/$($mail.Id)/microsoft.graph.createReply" -Method Post -Body $body
```

**Comment by peombwa** [comment] 2021-11-20 00:47
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/907

**Closed by peombwa** 2021-11-20 00:47 UTC
Labels: AutoREST-dependency, Bug: Client
