### ISSUE TITLE
mg graph 2.0.0 update causing issues in azure devops release pipelines. Invoke-MgGraphRequest : Method not found

### ISSUE THREAD

**Issue by shahidsayyed892** [microsoftgraph/msgraph-sdk-powershell#2161] opened 2023-07-14 07:34 UTC
```lang-ps1
$context = Get-AzContext
$graphToken = [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.AuthenticationFactory.Authenticate($context.Account, $context.Environment, $context.Tenant.Id.ToString(), $null, [Microsoft.Azure.Commands.Common.Authentication.ShowDialog]::Never, $null, "https://graph.microsoft.com").AccessToken
$secureAccessToken = $graphToken | ConvertTo-SecureString -AsPlainText -Force
Connect-MgGraph -AccessToken $secureAccessToken
Get-InstalledModule Microsoft.Graph

$UserReadAllId = Find-MgGraphPermission User.Read.All -ExactMatch -PermissionType Application | Select-Object -ExpandProperty Id
write-host $UserReadAllId
```

```Error record:
Invoke-MgGraphRequest : Method not found: 'Void Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider..ctor(Azure.Core.TokenCredential, System.String[], Microsoft.Kiota.Authentication.Azure.ObservabilityOptions, System.String[])'.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\2.0.0\custom\common\Permissions.ps1:37 char:27
+ ... estResult = Invoke-MgGraphRequest -method GET -OutputType PSObject $_ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-MgGraphRequest], MissingMethodException
    + FullyQualifiedErrorId : NotSpecified,Microsoft.Graph.PowerShell.Authentication.Cmdlets.InvokeMgGraphRequest
 
Script stack trace:
at Permissions_GetPermissionsData, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\2.0.0\custom\common\Permissions.ps1: line 37
at Find-MgGraphPermission<Begin>, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\2.0.0\custom\Find-MgGraphPermission.ps1: line 202
```

Facing this issue from 12 July 23.
Seems like microsoft has upgraded mggraph to 2.0.0 in devops pipeline, which earlier was 1.28.0

My use case involves calling below commands in azure devops pipeline to automate tasks:
- Find-MgGraphPermission
- Get-MgServicePrincipal
- Get-MgServicePrincipalAppRoleAssignedTo
- New-MgServicePrincipalAppRoleAssignment

**Comment by andikrueger** [comment] 2023-07-14 08:14
Please have a look at this issue and try to update to V2.1.0

https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2148

**Comment by peombwa** [comment] 2023-07-14 16:11
> Please have a look at this issue and try to update to V2.1.0
> 
> https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2148

Please see the resolution above.

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2148#issuecomment-1635214341.

**Closed by peombwa** 2023-07-14 16:11 UTC
Labels: ToTriage

**Comment by shahidsayyed892** [comment] 2023-07-14 18:50
Thanks @andikrueger
```ps1
Install-Module Microsoft.Graph -RequiredVersion 2.1.0 -Force -AllowClobber
```
updating the mg-graph to v2.1.0 has resolved this issue.
