### ISSUE TITLE
Get-MgGroupMember Graph List members -CountVariable doesn't return value

### ISSUE THREAD

**Issue by satyajit321** [microsoftgraph/msgraph-sdk-powershell#1233] opened 2022-04-27 15:09 UTC
Looking for a way to obtain the member count of a group using the Get-MgGroupMembers cmdlet from MS Graph PowerShell SDK.

However the parameter isn't returning any value. It works using GraphAPI directly. 

#This errors out
Get-MgGroupMember -CountVariable memberCount -GroupId xxxxxxx -ConsistencyLevel eventual
 

#This one works, but not results in count
Get-MgGroupMember -CountVariable memberCount -GroupId xxxxxxxx 

The [article](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.groups/get-mggroupmember?view=graph-powershell-1.0) has this, but doesn’t clarify how to use it.
-CountVariable
Specifies a count of the total number of items in a collection. By default, this variable will be set in the global scope.
#This article has clearly incorrect information.

**Comment by peombwa** [comment] 2022-06-03 23:27
Thanks for bringing this to our attention. Unfortunately, the service metadata from which the SDK is generated is missing the `ConsistencyLevel` header. The header will need to be added to the metadata for us to support it.

We are already tracking this in https://github.com/microsoftgraph/msgraph-metadata/issues/108.

**Comment by peombwa** [comment] 2022-06-03 23:28
Closing as duplicate of https://github.com/microsoftgraph/msgraph-metadata/issues/108 and https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/513#issuecomment-1130652049.

**Closed by peombwa** 2022-06-03 23:28 UTC
Labels: ToTriage
