### ISSUE TITLE
Unable to import Microsoft.Graph module into Azure Automation

### ISSUE THREAD

**Issue by hippygold42** [microsoftgraph/msgraph-sdk-powershell#1972] opened 2023-04-26 09:43 UTC
I have imported all of the 7.1 dependencies (1.26.0) but the Microsoft.Graph module will not load either via the portal or via Powershell. Error importing the module Microsoft.Graph. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: An error occurred when trying to import the module to an internal PowerShell session. Either the module dependencies are not imported correctly or the module is unsupported. Internal Error Message: The required module 'Microsoft.Graph.Authentication' is not loaded. Load the module or remove the module from 'RequiredModules' in the file 'C:\Users\Client\Temp\ZUXUKQUSBM\Microsoft.Graph\Microsoft.Graph.psd1'. . If I query the Automation Account installed modules it doesn't return any at all even though they are clearly visible in the portal.

**Comment by peombwa** [comment] 2023-04-27 19:41
Thanks for following up on this.

Possible duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/465:
> The meta-module (Microsoft.Graph) doesn't support Azure Automation since it does not export any command. You should instead only import the service modules you are interested in individually. A full list of all service modules can be found here https://github.com/microsoftgraph/msgraph-sdk-powershell/wiki/MS-Graph-PowerShell-Modules#service-modules.

Could you try importing only the service modules you need? Please take note of the [AzureAutomationNotSupported](https://www.powershellgallery.com/packages?q=Tags%3A%22AzureAutomationNotSupported%22) tag on the meta-module.

**Closed** 2023-05-04 21:03 UTC
Labels: Needs: Author Feedback, Question: SDK, no-recent-activity
