### ISSUE TITLE
Update-MgUser - setting null values for attributes

### ISSUE THREAD

**Issue by yukieryu** [microsoftgraph/msgraph-sdk-powershell#852] opened 2021-09-09 19:53 UTC
With the Set-MsolUser cmdlet, it is possible to set an attribute to "" to clear the value. 
E.g. Set-MsolUser -LastName "" will clear whatever value is present for the last name. 

However, Update-MgUser -UserId <object id> -Surname "" will generate error as below - 
Also attempted Update-MgUser -UserId <object id> -Surname $null but the same error. 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Update-MgUser : Invalid value specified for property 'mobilePhone' of resource 'User'.
At line:1 char:1
Update-MgUser -UserId 3d5f9e6a-c8e6-4ab3-8167-d56f0cd3b215 -MobilePho ...

    + CategoryInfo          : InvalidOperation: ({ UserId = 3d5f...oftGraphUser1 }:<>f__AnonymousType47`2) [Update-MgUser_Up
   dateExpanded], RestException`1
    + FullyQualifiedErrorId : Request_BadRequest,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUser_UpdateExpanded
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

On the side note, Set-AzureADUser -objectid <object id> -Surname "" will generate an error.
https://github.com/Azure/azure-docs-powershell-azuread/issues/166

**Comment by Chris-Tonev** [comment] 2021-11-03 14:05
Following.

**Comment by gagwithgaffer** [comment] 2021-12-27 22:02
I'm having the same issue trying to clear the password policy for an Azure AD user through the MS Graph SDK.

[https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http](url)

The password policy compromises two strings:

DisablePasswordExpiration, DisableStrongPassword

I can only remove one of the two string options at any one time by updating the user and writing over the previous configuration. It's not possible to overwite the policy with an empty string or null. This means any user who has had a password policy set previously is now stuck with at least one of the options for ever!

I have never know anything so rediculous in all my life, Micosoft are supposed to be security conscious but are leaving us wide open...

**Comment by JakeMoe** [comment] 2022-01-06 22:50
FWIW, this appears to be a duplicate of #833.

@gagwithgaffer You could try Invoke-GraphRequest as mentioned in that other issue.  It worked for me with the City attribute.

**Comment by peombwa** [comment] 2022-01-07 21:59
Closing as duplicate of #833. We are tracking the feature request in #833.

As a workaround, one can use `Invoke-MgGraphRequest -Method PATCH -Uri "https://graph.microsoft.com/v1.0/Users/{USER-ID}" -Body @{Surname = $null}` to nullify properties.

**Closed by peombwa** 2022-01-07 21:59 UTC
Labels: Request: Feature

**Comment by rui0122** [comment] 2022-10-27 21:01
The workaround "Invoke-MgGraphRequest" fails on the latest module 1.14.0. You can run "Invoke-MgRestMethod" instead.

**Comment by peombwa** [comment] 2022-11-02 18:22
@rui0122, please open a new issue with the repro steps and the error message.

The workaround works well for me in `v1.14.0`:
![image](https://user-images.githubusercontent.com/7061532/199571193-cb670d99-dd39-45f6-93df-b68f3f6faff6.png)

**Comment by blb8547** [comment] 2024-01-19 15:08
@yukieryu I found a workaround but I have not tested your exact situation. If you run the MG command with -bodyparameter and define your attributes in a hash table you can set "attribute" = @() and that will null it out. Let me know if that works for you as well.

**Comment by bastienperez** [comment] 2024-07-19 12:11
Any chance that the future SDK will finally support `"$null"`?

**Comment by sirragh** [comment] 2025-01-22 22:03
Use the static Empty field from the System.String class:  [string]::Empty

**Comment by Horgster** [comment] 2025-08-27 12:18
Any chance that the future SDK will finally support "$null"?
Its messy doing above workaround..

**Comment by Horgster** [comment] 2025-08-27 12:21
> [@yukieryu](https://github.com/yukieryu) I found a workaround but I have not tested your exact situation. If you run the MG command with -bodyparameter and define your attributes in a hash table you can set "attribute" = @() and that will null it out. Let me know if that works for you as well.

That will not work, as it will then create blank system.object in this attribute. Dont do that!
