### ISSUE TITLE
Problem Retrieving Extension Attributes using Get-mgUser

### ISSUE THREAD

**Issue by DougChandler** [microsoftgraph/msgraph-sdk-powershell#1955] opened 2023-04-20 18:18 UTC
I have a few Directory Extensions setup in our tenant:
```
extension_..._InCountryManagerUid
extension_..._GlobalTeamLeadUid
extension_..._ServicesSuspended
extension_..._IPTelephone
extension_..._Venture
extension_..._VentureCode
extension_..._WorkplaceIndicator
extension_..._SerialNumber
extension_..._IsManager
extension_..._EmployeeCountryCode
extension_..._WorkLocationCode
extension_..._DepartmentCode
extension_..._OrganizationCode
extension_..._BusinessUnit
extension_..._BusinessUnitCode
extension_..._CompanyCode
extension_..._EmployeeTypeCode
```

But when trying to retrieve using these commands:
`get-mguser -UserId ($aaduser.Id) -Property @("extension_..._**E**mployeeTypeCode")`
Does not return the attribute
`get-mguser -UserId ($aaduser.Id) -Property @("extension_..._**e**mployeeTypeCode")`
Returns the attribute (with a capital in the name)

This must be a bug...

**Comment by peombwa** [comment] 2023-04-25 23:32
Closing as duplicate of https://github.com/microsoftgraph/microsoft-graph-docs/issues/16908. Yes, this in an issue with the API.

**Closed by peombwa** 2023-04-25 23:32 UTC
Labels: ToTriage
