### ISSUE TITLE
Clarify README.md for DevOps automation: Connect-MgGraph function with AccessToken parameter using AzContext

### ISSUE THREAD

**Issue by erwinkramer** [microsoftgraph/msgraph-sdk-powershell#669] opened 2021-05-20 13:45 UTC
In a DevOps pipeline PowerShell task, I'm currently using the following piece of code to authenticate: 

```
$context = Get-AzContext
$graphToken = [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.AuthenticationFactory.Authenticate($context.Account, $context.Environment, $context.Tenant.Id.ToString(), $null, [Microsoft.Azure.Commands.Common.Authentication.ShowDialog]::Never, $null, "https://graph.microsoft.com").AccessToken
Connect-MgGraph -AccessToken $graphToken
```

It would be nice if the README (https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/README.md) explained this method for DevOps automation. It currently doesn't even say that `AccessToken` authentication is possible. 
[AB#9547](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9547)

**Comment by peombwa** [comment] 2021-05-21 18:25
I agree with you. This will be fixed by this feature request https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/509. 

FYI @georgend.

**Comment by peombwa** [comment] 2021-05-21 18:28
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/509

**Closed by peombwa** 2021-05-21 18:28 UTC
Labels: ToTriage
