### ISSUE TITLE
Set-MgUserPhotoContent : An error occurred while sending the request

### ISSUE THREAD

**Issue by tkudya** [microsoftgraph/msgraph-sdk-powershell#2376] opened 2023-10-20 09:18 UTC
**Describe the bug**
Currently uploading multiple photos using the Set-MgUserPhotoContent command and it always runs into the error "An error occurred while sending the request" I have added a time delay thinking maybe its throttling but it always happens. The picture uploads and the next one fails. It's different people, i can run the command manually and it will work

**To Reproduce**
1. Set-MgUserPhotoContent -UserID xxxxxx@xxx.com -infile
2.  Received exception with message 'HttpRequestException - An error occurred while sending the

**Expected behavior**
> Expecting no error

**Debug Output**
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/78653328/7faf76ff-f834-4bfa-800e-42a8707e0d27)

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/78653328/fb0a345f-97af-4819-ab75-339f8822b28b)

> Run the problematic command with `-Debug` and paste the resulting debug stream below.
> ⚠ ATTENTION: Be sure to remove any sensitive information that may be in the logs.

**Module Version**
 Get-Module Microsoft.Graph*

ModuleType Version    Name                                ExportedCommands                                                                                                                                                                                       
---------- -------    ----                                ----------------                                                                                                                                                                                       
Script     2.7.0      Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext...}                                                                                                                             
Script     2.7.0      Microsoft.Graph.Users               {Get-MgUser, Get-MgUserCount, Get-MgUserCreatedObject, Get-MgUserCreatedObjectAsServicePrincipal...}

**Environment Data**
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/78653328/c4137a1b-7acc-4e28-9039-0b70a99a9ef1)

**Comment by peombwa** [comment] 2023-10-20 17:15
Please the request details at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2360#issuecomment-1773105809 in #2360.

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2360.

**Closed by peombwa** 2023-10-20 17:15 UTC
