### ISSUE TITLE
Microsoft.Graph.Authentication Module v2.0.0 cannot be imported in Azure Automation - Same as #2133

### ISSUE THREAD

**Issue by bemokraig** [microsoftgraph/msgraph-sdk-powershell#2142] opened 2023-07-10 17:42 UTC
Import vom Module Microsoft.Graph.Authentication Module v2.0.0 fails in Azure Automation with the error message

Error importing the module Microsoft.Graph.Authentication. Import failed with the following error: 
Orchestrator.Shared.AsyncModuleImport.ModuleImportException: While importing the module, an error occurred while processing 
the module content. Internal error message: Exception has been thrown by the target of an invocation.. 
at Orchestrator.Activities.SetModuleVersion.ExecuteInternal(CodeActivityContext context, String moduleName, 
ModuleLanguage moduleLanguage, String pythonModuleVersion, String modulePath, Guid accountId, Guid moduleVersionId, 
Int64 moduleContentByteSize, String storageUri, Int32 moduleVersion) at 
Orchestrator.Activities.SetModuleVersion.Execute(CodeActivityContext context) at 
System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, 
BookmarkManager bookmarkManager) at 
System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, 
BookmarkManager bookmarkManager, Location resultLocation)

To Reproduce

Create an Azure Automation Account
Go to Modules
Go to Add a Module
Browse Module Microsoft.Graph.Authentication from Gallery and Import
Check Error Message after Module Import shows "Failed"
Expected behavior
I expect the module to import. It worked without any issues for module Version 1.28.0.

Debug Output
None

Module Version
Microsoft.Graph.Authentication v2.0.0

Environment Data
None

Screenshots
image

Additional context
Workaround: No

**Comment by peombwa** [comment] 2023-07-12 20:31
Closing as duplicate of #2133.

We'll use #2133 to follow up with the Azure Automation team as the intermittent error is coming from their end when  importing the module (see stack trace).

**Closed by peombwa** 2023-07-12 20:31 UTC
Labels: ToTriage
