### ISSUE TITLE
New-MgEntitlementManagementAccessPackageAssignmentRequest does not have an output while corresponding API does.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#1193] opened 2022-04-05 12:08 UTC
Running this commande 
```New-MgEntitlementManagementAccessPackageAssignmentRequest -RequestType 'UserAdd' -AccessPackageId '08173ced-8eae-4023-8433-cb85f29e7726' -AssignmentPolicyId '4acf0d48-49b1-495b-816e-58933c9a9e64' -TargetId '6c42590f-fcf0-4922-bac6-205f7c6aa89c'``` does not return any output.

**Comment by markwahl-msft** [comment] 2022-04-08 17:04
I wonder if this might be due to the mismatch between the open API YML files, if those result in auto generated files such as `IdentityGovernance.cs` and others looking only for a _single_ response code,  
```cs
case global::System.Net.HttpStatusCode.Created:
```
whereas the [OData common response codes](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-odata/e85b0f4c-3354-47a2-bbe4-f8d08873202c). does not mention that response code specifically.  Perhaps the results parser accept a service any of the success result codes, not just `.Created`?

**Comment by peombwa** [comment] 2022-05-02 21:46
@msewaweru, what status code does the service return when you call the command with a `-Debug`? Both the OpenAPI file and the [API reference doc](https://docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentrequests?view=graph-rest-beta&tabs=http#response-1) say the status code should be 201:
![image](https://user-images.githubusercontent.com/7061532/166331830-f8856a92-fc0e-4d1d-978c-08bd73f5f1c2.png)

**Comment by msewaweru** [comment] 2022-05-04 10:23
@peombwa, below is what I see.

![image](https://user-images.githubusercontent.com/73849846/166664185-c55998a0-fc65-4f3d-9375-a4ad44b4157b.png)

**Comment by markwahl-msft** [comment] 2022-05-06 17:19
How do we update the OpenAPI to allow HTTP status codes 200..204 (or more) to indicate success, and to check presence of the response body and content type or content length headers to determine if it has a payload, rather than the status code?

**Comment by peombwa** [comment] 2022-05-10 17:35
@markwahl-msft, we are working on that in the OData to OpenAPI lib as part of PR https://github.com/microsoft/OpenAPI.NET.OData/pull/215. The goal is to support 2XX as a status code range and have the clients handle the individual status codes appropriately.

**Comment by peombwa** [comment] 2022-05-10 17:37
@msewaweru, @markwahl-msft I'll mark this as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/907. A fix will be provided by https://github.com/microsoft/OpenAPI.NET.OData/pull/215.

**Closed by peombwa** 2022-05-10 17:37 UTC
Labels: OpenApiService-Dependency
