### ISSUE TITLE
first letter of property is converted to lowercase when using -BodyParameter

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/msgraph-sdk-powershell#1256] opened 2022-05-12 17:48 UTC
When MS GraphPowerShell SDK, the first letter of the property is made lowercase.

Using MS Graph PowerShell SDK v1.9.5
> Issue did not occur in v1.9.2

$UserExtensionProperties = [hashtable]@{
     "msgraphschema_extensionName"= @{
         "SOMETHING"= "test_value"
     }
 } | ConvertTo-Json -Compress

Update-MgUser -UserId user[@contoso.onmicrosoft.com](mailto:user@contoso.onmicrosoft.com) -BodyParameter $UserExtensionProperties -Debug

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://graph.microsoft.com/v1.0/users/xxx

Headers:

Body:
{
  "msgraphschema_extensionName": {
    "sOMETHING": "test_value"
  }
}

This causes problems when using MS Graph Schema Extensions where you own schema can be defined.

**Comment by JakeMoe** [comment] 2022-05-26 04:53
Far out, this is what I've been fighting with all day.  Only just realized that I updated my Microsoft.Graph modules in Azure Automation the other day from 1.9.2 to 1.9.6, as well as my development system, and this might be why my schema extensions suddenly aren't being set.

Added the -Debug option, and I can see my property's first letter dropping from upper to lower case.

As a workaround, though, I am able to use the following (in Update-MgUser, I leave my $body as a hashtable, I've never converted it to JSON there before like OP above):
```
$bodyJson = $body | ConvertTo-Json
Invoke-MgGraphRequest -Method 'PATCH' -Uri "https://graph.microsoft.com/v1.0/users/$UserId" -Body $bodyJson
```

**Comment by peombwa** [comment] 2022-06-02 19:07
The issue is due to a bug fix that was made to address how properties of complex abstract types were serialized.

We are already tracking the bug in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1185, and a fix will be available in the release. Please use the suggested workaround above in the meantime.

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1185.

**Closed by peombwa** 2022-06-02 19:07 UTC
Labels: ToTriage
