### ISSUE TITLE
Category (Update-MgDeviceManagementManagedDevice)

### ISSUE THREAD

**Issue by zpfln** [microsoftgraph/msgraph-sdk-powershell#1552] opened 2022-10-05 15:00 UTC
Hello,

I am attempting to assign a category to a device through **Update-MgDeviceManagementManagedDevice** by using the **DeviceCategoryDisplayName** parameter and using a string but I receive the error below.

```
Update-MgDeviceManagementManagedDevice -ManagedDeviceId f9e23669-e35f-4a7a-8af8-d104ae88483e -DeviceCategoryDisplayName "Sweden, Stockholm"

Update-MgDeviceManagementManagedDevice : {
  "_version": 3,
  "Message": "An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 306f81cd-6ae8-4bb7-b2eb-3b27f476f018 - Url: https://fef.msub06.manage.microsoft.com/DeviceFE/StatelessDeviceFEService/deviceManagement/managedDevices%28%27
f9e23669-e35f-4a7a-8af8-d104ae88483e%27%29?api-version=5022-08-04",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
At line:1 char:1
+ Update-MgDeviceManagementManagedDevice -ManagedDeviceId f9e23669-e35f ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ManagedDevice...anagedDevice1 }:<>f__AnonymousType1892) [Update-MgDevice...UpdateExpanded1], RestException1
    + FullyQualifiedErrorId : InternalError,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgDeviceManagementManagedDevice_UpdateExpanded1
```

I have also tried using **Update-MgDeviceManagementManagedDevice** and the parameter **DeviceCategory** and a object but I receive another error.

```
Update-MgDeviceManagementManagedDevice : The annotation 'odata.context' was found. This annotation is either not recognized or not expected at the current position.
At line:1 char:1
+ Update-MgDeviceManagementManagedDevice -ManagedDeviceId f9e23669-e35f ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ManagedDevice...anagedDevice1 }:<>f__AnonymousType1892) [Update-MgDevice...UpdateExpanded1], RestException1
    + FullyQualifiedErrorId : ModelValidationFailure,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgDeviceManagementManagedDevice_UpdateExpanded1
```

It might be good to know that I have ran below prior to this.

`Connect-MgGraph -Scopes "DeviceManagementManagedDevices.ReadWrite.All","DeviceManagementConfiguration.ReadWrite.All"`

`Select-MgProfile -Name "beta"`

I have also ran the command below successfully as a test, no errors.

`Update-MgDeviceManagementManagedDevice -ManagedDeviceId f9e23669-e35f-4a7a-8af8-d104ae88483e -Notes "hello world"
`

Thoughts?

**Comment by peombwa** [comment] 2022-10-07 21:44
Thanks for following up on this.

The error message points to an issue with the API and not the command. The same error message can be reproduced through Graph Explorer - https://developer.microsoft.com/en-us/graph/graph-explorer.

As this repository is intended for issues related to the functionality of the SDK, we may not be the best placed to answer some queries that are tied to the functionality of the API.

Please open a question/ticket at https://developer.microsoft.com/en-us/graph/support to get an answer from the API owners. You can follow the troubleshooting steps at https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug to get the `request-id` and `date` that's needed when opening a ticket.

Related to https://github.com/microsoftgraph/microsoft-graph-docs/issues/7530.

**Comment by peombwa** [comment] 2023-04-12 23:50
Closing as service issue. Please use the above forums to follow up with the API owner.

**Closed by peombwa** 2023-04-12 23:50 UTC
Labels: Service issue
