### ISSUE TITLE
*-MgTeamSchedule* cmdlets don't work (Missing MS-APP-ACTS-AS Header)

### ISSUE THREAD

**Issue by astapelfeld** [microsoftgraph/msgraph-sdk-powershell#1227] opened 2022-04-25 14:21 UTC
Module Microsoft.Graph v.1.9.5

\*-MgTeamSchedule* cmdlets don't work:

```
Get-MgTeamSchedule -TeamId $id
Get-MgTeamSchedule_Get1: {"error":{"code":"Forbidden","message":"MS-APP-ACTS-AS header needs to be set for application context requests.","details":[],"innererror":{"code":"MissingUserIdHeaderInAppContext"}}}

Get-MgTeamScheduleShift -TeamID $id
Get-MgTeamScheduleShift_List1: {"error":{"code":"Forbidden","message":"MS-APP-ACTS-AS header needs to be set for application context requests.","details":[],"innererror":{"code":"MissingUserIdHeaderInAppContext"}}
```

Apparently it works if the MS-APP-ACTS-AS Header is added to the request ([https://stackoverflow.com/questions/61320529/error-when-querying-microsoft-graph-api-shifts-ms-app-acts-as-header-needs-to](https://stackoverflow.com/questions/61320529/error-when-querying-microsoft-graph-api-shifts-ms-app-acts-as-header-needs-to)). I haven't tested myself, but it works in Graph Explorer as well.

This issue might be related: https://github.com/microsoftgraph/msgraph-metadata/issues/109

**Comment by peombwa** [comment] 2022-05-03 15:58
Thanks for bringing this to our attention. Unfortunately, the header is currently not supported by the SDK as it is not specified in the service metadata or [documented as required](https://docs.microsoft.com/en-us/graph/api/schedule-list-shifts?view=graph-rest-1.0&tabs=http#request-headers). We will address the missing header in https://github.com/microsoftgraph/msgraph-metadata/issues/109.

A workaround is to sign in with delegated access (`Connect-MgGraph -Scopes "Schedule.Read.All"`) to use `*-MgTeamSchedule*` commands. If you need to use [app-only auth](https://docs.microsoft.com/en-us/powershell/microsoftgraph/app-only?context=graph%2Fapi%2F1.0&view=graph-powershell-beta&viewFallbackFrom=graph-rest-1.0&tabs=azure-portal), you can use `Invoke-MgGraphRequest` to make the request with the header as shown below:
``` powershell
Invoke-MgGraphRequest -Uri "v1.0/teams/$teamId/schedule/shifts" -Headers @{ "MS-APP-ACTS-AS" = $userId }
```

**Comment by peombwa** [comment] 2022-05-03 15:59
Closing as duplicate of https://github.com/microsoftgraph/msgraph-metadata/issues/109.

**Closed by peombwa** 2022-05-03 15:59 UTC
Labels: metadata-issue
