### ISSUE TITLE
Get-MgDevice mixes up Id and DeviceId values

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/msgraph-sdk-powershell#1465] opened 2022-08-19 09:18 UTC
Original issue filed at https://github.com/microsoftgraph/microsoft-graph-docs/issues/18095#issue-1343488798. Behavior repro'd.

**Current:**
Assume this is the Id and DeviceId
```
PS C:\> Get-MgDevice| select ID, DeviceId | Format-List

Id       : b75a5ab2-fe55-4463-bd31-d21ad555c6e0
DeviceId : 4c299165-6e8f-4b45-a5ba-c5d250a707ff
```

**Repro steps:**
`Get-MgDevice -Id 'b75a5ab2-fe55-4463-bd31-d21ad555c6e0'` => Fails
`Get-MgDevice -DeviceId 'b75a5ab2-fe55-4463-bd31-d21ad555c6e0'` => Incorrectly succeeds

The code snippets in [Get device](https://docs.microsoft.com/en-us/graph/api/device-get?view=graph-rest-1.0&tabs=powershell) also incorrectly translate `/devices/{deviceObjectId}` to `Get-MgDevice -DeviceId $deviceId`. It should be `Get-MgDevice -Id $Id`.

Filter works correctly:
`Get-MgDevice -Filter "Id eq 'b75a5ab2-fe55-4463-bd31-d21ad555c6e0'"`
`Get-MgDevice -Filter "DeviceId eq '4c299165-6e8f-4b45-a5ba-c5d250a707ff'"`

Kindly assist to resolve.

cc @msewaweru for visibility and tracking.

**Comment by msewaweru** [comment] 2022-08-22 08:01
Thanks @FaithOmbongi. The issue as I see it when the parameters are named, we use the resourceID , for example -UserId instead of -Id. For devices it so happens that there is another property called DeviceId and needs to be looked into. Thanks.

**Comment by peombwa** [comment] 2022-08-23 19:34
Thanks for bringing this to our attention. We are already tracking this in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/906.

The parameters are named this way in the OpenAPI file used to generate the modules. A fix will be provided by DevX API in https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/840.

The code snippets are correct since they show how to get a device using a device id (`-DeviceId`). `-Id` is not a parameter on `Get-MgDevice`:
``` powershell
➜ Get-Help Get-MgDevice -Parameter DeviceId

-DeviceId <String>
    key: id of device

    Required?                    true
    Position?                    named
    Default value
    Accept pipeline input?       false
    Accept wildcard characters?  false
```

Closing as duplicate of #906. We will support this in v2.

**Closed by peombwa** 2022-08-23 19:34 UTC
Labels: ToTriage
