### ISSUE TITLE
Get-MgReportTeamUserActivityCount returning Edm type error

### ISSUE THREAD

**Issue by stvpwrs** [microsoftgraph/msgraph-sdk-powershell#222] opened 2020-05-13 13:45 UTC
Hello,

When trying to use the new 0.5.1 module and the `Get-MgReportTeamUserActivityCount` cmdlet I'm getting a type error.

If I run:
```
Connect-Graph

Get-MgReportTeamUserActivityCount -Period "7D"
```
I get the following error:
```
Get-MgReportTeamUserActivityUserCount : Expression of type 'Edm.Double' cannot be converted to type 'Edm.String'.
At line:1 char:1
+ Get-MgReportTeamUserActivityUserCount
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Period = 7D }:<>f__AnonymousType3`1) [Get-MgReportTea...tyUserCount_Get], Exception
    + FullyQualifiedErrorId : BadRequest,Microsoft.Graph.PowerShell.Cmdlets.GetMgReportTeamUserActivityUserCount_Get
```
None of the Teams report cmdlets appear to be working.

**Comment by darrelmiller** [comment] 2020-05-13 14:06
Yeah sorry about this. It's a known issue  #151.  We have a fix coming out in the next update which will be in a few weeks.

**Comment by stvpwrs** [comment] 2020-05-13 16:59
@darrelmiller so if I format the arguement correctly, I then get a different error which I assume is the cmdlet not expecting a csv as the result. I didn't see that covered in #151 should that be it's own issue?
Get-MgReportTeamUserActivityCount -Period "'D7'"

```
Welcome To Microsoft Graph!
Get-MgReportTeamUserActivityCount : Expected '{' or '['. Was String: Report.
At line:12 char:1
+ Get-MgReportTeamUserActivityCount -Period "'D7'"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgReportTeamUserActivityCount_Get], ParserException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgReportTeamUserActivityCount_Get

```

**Comment by peombwa** [comment] 2020-05-14 00:49
@stvpwrs the second issue is an issue with the code generator - it does not handle non JSON responses. This is covered in #182.

**Comment by TomasCrha** [comment] 2020-06-11 13:06
Hello, is there any update? I would really like to use Get-MgReportTeamUserActivityCount command but I am also struggling with the date format as mentioned above...
Is there any hope this will be fixed/adjusted - or do you think you can advise how to input the date so the cmdlet will accept it?
Many thanks,
Tomas

**Comment by stvpwrs** [comment] 2020-06-15 18:18
> Hello, is there any update? I would really like to use Get-MgReportTeamUserActivityCount command but I am also struggling with the date format as mentioned above...
> Is there any hope this will be fixed/adjusted - or do you think you can advise how to input the date so the cmdlet will accept it?
> Many thanks,
> Tomas

@TomasCrha, you can pass an argument to the cmdlet so that the resulting string is literally `'D7'` for instance, but the cmdlet still cannot handle the csv return type. So this needs to have 2 bugs fixed. 

I ended up using Power BI and the Microsoft Graph report framework to get around this issue. 

Steve

**Comment by peombwa** [comment] 2020-11-11 23:36
Duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/407. Downloading of reports is being tracked by https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/407.

**Closed by peombwa** 2020-11-11 23:36 UTC
