### ISSUE TITLE
Stop hiding Beta commands in 1.0

### ISSUE THREAD

**Issue by FriedrichWeinmann** [microsoftgraph/msgraph-sdk-powershell#1218] opened 2022-04-17 12:24 UTC
As it is currently implemented, the modules generated as part of Microsoft.Graph only export the commands viable to the currently selected endpoint.
This is an anti-pattern, since the users get highly misleading error messages ("Command not found" rather than "Wrong api configured"). This has been a traditional problem with the exchange remote shell, where you only have access to the commands you are allowed to run.

With Exchange, this has been a fairly small issue, since restricted permissions were a rare scenario, where admins had to plan this out and implement it and thus would have the expertise to understand what hit them.

With the Graph modules, literally everybody who tries to call a beta-only command will run into this.
Many of our users are admins with minimal PowerShell skills and will be unable to debug this and figure out what happened to them.

Hence please stop hiding beta-only content and instead implement an error message that allows to user to understand what to do in order for things to work. Ideally, I would like for this to apply to _all_ aspects of the commands (such as beta-only parameters), not just the commands, but the commands would be a major step forward already.

> Notes

Here a few recent issues triggered by this to illustrate the point:

https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1195
https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1093
https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1087

(Note that the majority of users challenged by this are not Github users and will not speak up here)

**Comment by peombwa** [comment] 2022-04-20 17:16
@FriedrichWeinmann, thanks for the valuable feedback. We plan to split the SDK into `Microsoft. Graph` (for v1.0) and `Microsoft.Graph.Beta` (for beta) for the same reasons you've highlighted above. See the discussions in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/692.

**Comment by peombwa** [comment] 2022-04-20 17:17
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/692.

**Closed by peombwa** 2022-04-20 17:17 UTC
