### ISSUE TITLE
Version 2.18.0 broken - Method not found: error

### ISSUE THREAD

**Issue by marckean** [microsoftgraph/msgraph-sdk-powershell#2703] opened 2024-04-25 22:32 UTC
### Describe the bug

I am running this: 

if (-not(Get-Module -ListAvailable -Name Microsoft.Graph.Groups)) {
    Install-Module -Name Microsoft.Graph.Groups -Scope CurrentUser -AllowClobber -Force
    Import-Module -Name Microsoft.Graph.Groups
}

# Sign into the Microsoft Graph
$resource = "https://graph.microsoft.com"
$token = (Get-AzAccessToken -TenantId $tenantID -ResourceUrl $resource).Token

# Create a SecureString from the token
$SecureToken = ConvertTo-SecureString $token -AsPlainText -Force

# Use the SecureString token to connect
Connect-MgGraph -AccessToken $SecureToken

But I get this error:

Method not found: 'Void Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider..ctor(Azure.Core.TokenCredential, System.String[], Microsoft.Kiota.Authentication.Azure.ObservabilityOptions, System.String[])'.

### Expected behavior

I should get something like this:

Welcome to Microsoft Graph!

Connected via userprovidedaccesstoken access using c288694f-2e16-4c20-928d-c262d8008520

### How to reproduce

It's due to the latest Microsoft.Graph.Groups module that's just been released version 2.18.0- https://www.powershellgallery.com/packages/Microsoft.Graph.Groups/2.18.0

Running this instead in my script, to force it to use the previous version 2.17.0, it works:

if (-not(Get-Module -ListAvailable -Name Microsoft.Graph.Groups)) {
    Install-Module -Name Microsoft.Graph.Groups -RequiredVersion '2.17.0' -Scope CurrentUser -AllowClobber -Force
    Import-Module -Name Microsoft.Graph.Groups
}

### SDK Version

2.18.0

### Latest version known to work for scenario above?

2.17.0

### Known Workarounds

Go back to the last known working version:

if (-not(Get-Module -ListAvailable -Name Microsoft.Graph.Groups)) {
    Install-Module -Name Microsoft.Graph.Groups -RequiredVersion '2.17.0' -Scope CurrentUser -AllowClobber -Force
    Import-Module -Name Microsoft.Graph.Groups
}

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

Windows, x64

### Other information

.

**Comment by timayabi2020** [comment] 2024-04-26 05:50
Hi @marckean thank you for reporting this issue. I successfully logged in after going through the reproduction steps.  Kindly let me know which PowerShell version you are using.
<img width="500" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/7eab3b1e-6239-4557-b151-3ff8bf7afb70">

**Comment by marckean** [comment] 2024-04-26 05:56
I am using version 2.17.0 now, whereas before using version 2.18.0 failed for me.

I am running:

if (-not(Get-Module -ListAvailable -Name Microsoft.Graph.Groups)) {
        Install-Module -Name Microsoft.Graph.Groups -Scope CurrentUser -AllowClobber -Force
        Import-Module -Name Microsoft.Graph.Groups
    }

# Sign into the Microsoft Graph
    $resource = "https://graph.microsoft.com"
    $token = (Get-AzAccessToken -TenantId $tenantID -ResourceUrl $resource).Token

    # Create a SecureString from the token
    $SecureToken = ConvertTo-SecureString $token -AsPlainText -Force

    # Use the SecureString token to connect
    Connect-MgGraph -AccessToken $SecureToken


Note, as this doesn't specify a required version, it pulls the latest version (2.18.0). So adding this: -RequiredVersion '2.17.0' gets me past this error. 

Also note, I am running this as an Azure Deployment Script resource which is executed using Bicep - for this, it spins up a container instance and runs the script.

**Comment by dp-h** [comment] 2024-04-26 16:01
Same issue, downgrading to v2.17 is great workaround. My PS version info: 
```Name                           Value
----                           -----
PSVersion                      5.1.14393.6343
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.6343
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1```

**Comment by 12Knocksinna** [comment] 2024-04-27 23:32
Could this be a PowerShell 5 problem? I have no issue connecting with a user provided access token and using the Groups module with PS 7.4.2 and SDK 2.18.

**Comment by timayabi2020** [comment] 2024-04-29 06:53
@12Knocksinna I also have no issue connecting from PowerShell 5. 
<img width="755" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/f11428d1-53a6-4743-9095-02bd8e82cb82">

**Comment by MainDBA** [comment] 2024-04-29 07:35
I have the same issue.  
My Azure automation accounts update their PowerShell Modules automatically in the early hours each Monday morning and two automation accounts' runbooks (that have worked since I moved to Microsoft.Graph In October 2023) have errored this morning with similar errors (see below).
I use PowerShell Runtime version 5.1 and a User Managed Identity to authenticate - Cmdlets Get-MgGroup. Get-MgUser and Get-MgGroupMember have generated the following:

Error 1
Get-MgGroup : Method not found: 'Void Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider..ctor(Azure.Core.TokenCredential, System.String[], Microsoft.Kiota.Authentication.Azure.ObservabilityOptions, System.String[])'. At line:48 char:1 + $GroupID = Get-MgGroup -Filter "DisplayName eq 'everyone'" -Property ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [Get-MgGroup_List], MissingMethodException + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List

Error 2
Get-MgUser : Method not found: 'Void Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider..ctor(Azure.Core.TokenCredential, System.String[], Microsoft.Kiota.Authentication.Azure.ObservabilityOptions, System.String[])'. At line:49 char:1 + $users = Get-MgUser -All + ~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [Get-MgUser_List], MissingMethodException + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List

Error 3
Get-MgGroupMember : Cannot bind argument to parameter 'GroupId' because it is an empty string. At line:50 char:39 + $members = Get-MgGroupMember -GroupId $GroupID.Id -All + ~~~~~~~~~~~ + CategoryInfo : InvalidData: (:) [Get-MgGroupMember], ParameterBindingValidationException + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-MgGroupMember

**Comment by timayabi2020** [comment] 2024-04-29 15:53
I noticed that two versions of ``Azure.Identity`` assembly are loaded in a PowerShell session but PowerShell 5 doesn't seem to handle the conflict well hence throwing the ``AzureIdentityAccessTokenProvider`` constructor error. Microsoft Graph PowerShell SDK uses the latest versions of ``Azure.Identity`` and ``Azure.Identity.Broker`` assemblies (``1.11.0`` and ``1.1.0`` respectively) while the ``Az.Accounts`` module still uses the old ``Azure.Identity`` assembly (``1.10.3``).
I have seen a [pull request](https://github.com/Azure/azure-powershell/pull/24609) in their GitHub repository to bump the ``Azure.Identity`` assembly up. The PR is yet to be merged.

So, if you are executing any scripts in a PowerShell 5 environment, please revert to 2.18.0 for now as suggested by @marckean, @KnudsenMorten, @dp-h and @MainDBA.

**Comment by peterboba** [comment] 2024-05-07 11:57
This seems to be the same type of issue as https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2148
```
PS C:\WINDOWS\system32> Import-Module Az.Accounts
PS C:\WINDOWS\system32> Import-Module Microsoft.Graph.Authentication
PS C:\WINDOWS\system32> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.19.0     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear...
Script     2.18.0     Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, G...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, En...
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...


PS C:\WINDOWS\system32> Get-MgApplication
Get-MgApplication : Method not found: 'Void
Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider..ctor(Azure.Core.TokenCredential, System.String[],
Microsoft.Kiota.Authentication.Azure.ObservabilityOptions, System.String[])'.
At line:1 char:1
+ Get-MgApplication
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgApplication_List], MissingMethodException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgApplication_List

PS C:\WINDOWS\system32> Get-MgOrganization
Get-MgOrganization : Method not found: 'Void
Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider..ctor(Azure.Core.TokenCredential, System.String[],
Microsoft.Kiota.Authentication.Azure.ObservabilityOptions, System.String[])'.
At line:1 char:1
+ Get-MgOrganization
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgOrganization_List], MissingMethodException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgOrganization_List
```

**Comment by MainDBA** [comment] 2024-05-17 11:30
I noticed the Microsoft.Graph modules were updated to version 2.19.0 but this issue #2.18.0 was not included in the release notes - any updates on its progress please?

**Comment by Ndiritu** [comment] 2024-05-17 12:07
@MainDBA from the linked [fix](https://github.com/Azure/azure-powershell/pull/24792) Azure PowerShell, the Az 12.0 release should resolve this.

**Comment by MainDBA** [comment] 2024-05-21 11:56
I spotted Az 12.0.0 was made available earlier today (21/05) on the PowerShell Gallery so I ran my module update script and also moved my MS.Graph modules from [working] version 2.17.0 to 2.19.0 and my two affected automation accounts' runbooks have run OK, so, issue [for me] appears to be resolved.
Thanks.

**Closed** 2024-05-21 14:42 UTC
