### ISSUE TITLE
Update-MgOrganization contacts are for a single email address not a list of addresses

### ISSUE THREAD

**Issue by jonwbstr** [microsoftgraph/msgraph-sdk-powershell#2370] opened 2023-10-18 15:05 UTC
Hello,

The Update-MgOrganization cmdlet says the "TechnicalNotificationMails" parameter supports a string array. I.e. multiple values.
> -TechnicalNotificationMails <String[]>

https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/update-mgorganization?view=graph-powershell-1.0&preserve-view=true

However, my experience and research indicates that while the property supports multiple addresses, the platform only sends emails to the first entry.

Please update documentation to clarify that although it will store and return multiple values, only the first entry is used by the platform. Bonus points for updating the API to reflect how it is used, or updating the platform to support multiple contacts as the API suggests. :)

Current Description:
> Not nullable.

Proposed Description
> Not nullable. The email address for the primary technical person who administers your subscription. This person receives communications about Microsoft service status.

Additional References
This answer from 2016 indicates only one technical contact email address is supported
https://answers.microsoft.com/en-us/msoffice/forum/all/how-many-technical-contacts-can-you-have-per/107ab76f-c9b7-40d5-a082-9fde6810fb5e

This feedback request from 2015 indicates that when multiple addresses are supplied only the first receives notifications. 
https://feedback.azure.com/d365community/idea/2b2de14e-c725-ec11-b6e6-000d3a4f0789

This article describes the field as a singular "person"
> The email address for the primary technical person who administers your subscription. This person receives communications about Microsoft service status.
https://learn.microsoft.com/en-us/microsoft-365/admin/manage/change-address-contact-and-more?view=o365-worldwide

These three properties deal with email notifications and I suspect they all accept multiple addresses but only send notifications to the first address. The documentation indicates it accepts multiple addresses, and uses them all.
[MarketingNotificationEmails](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/update-mgorganization?view=graph-powershell-1.0&preserve-view=true#-marketingnotificationemails)
[SecurityComplianceNotificationMails](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/update-mgorganization?view=graph-powershell-1.0&preserve-view=true#-securitycompliancenotificationmails)
[TechnicalNotificationMails](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/update-mgorganization?view=graph-powershell-1.0&preserve-view=true#-technicalnotificationmails)

**Comment by peombwa** [comment] 2023-10-18 17:30
Thanks for following up on the issue.

This seems like a service issue. Please open a service ticket/ question at https://developer.microsoft.com/graph/support to get assistance from the API owners. The [API reference doc](https://learn.microsoft.com/en-us/graph/api/organization-update?view=graph-rest-1.0&tabs=http#request-body)  and the service description both state that the property accepts a collection of strings, which is what the SDK sends. The API team will need to review why the service only sends an email to the first mail entry. If this is by design, the property description will need to be updated at the service level to explain the behavior.

This repo is for SDK bugs and feature requests only. Service issues should be directed to https://developer.microsoft.com/graph/support.

**Comment by peombwa** [comment] 2023-10-18 17:31
Closing as service-related issue. The API behavior and/or docs will need to be reviewed by the API team per customer findings.

**Closed by peombwa** 2023-10-18 17:31 UTC
Labels: Service issue
