### ISSUE TITLE
Why Select-MgProfile?

### ISSUE THREAD

**Issue by stromnessian** [microsoftgraph/msgraph-sdk-powershell#1674] opened 2022-12-12 10:44 UTC
Maybe I'm missing something, but I find it odd that the cmdlet for setting the profile was named Select-MgProfile when anyone who's used PowerShell would assume that the verb would be Set, as in pretty much every other cmdlet that's used for setting something.

**Comment by peombwa** [comment] 2022-12-12 17:39
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/692.

**Closed by peombwa** 2022-12-12 17:39 UTC
Labels: ToTriage
