### ISSUE TITLE
get-mguser signinactivity returns string

### ISSUE THREAD

**Issue by olliojala** [microsoftgraph/msgraph-sdk-powershell#2387] opened 2023-10-25 05:28 UTC
Hi,
I can't get actual date to be returned with Get-MgUser -all| select-object signInActivity command. It only returns this:

SignInActivity                                                
--------------                                                
Microsoft.Graph.PowerShell.Models.MicrosoftGraphSignInActivity

I have installed the newest module today and using these scopes "AuditLog.Read.All","Directory.Read.All","User.Read.All","Organization.Read.All"

All the other data that I have tried to query returns the correct values

**Comment by peombwa** [comment] 2023-10-25 17:19
This is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/485#issuecomment-790131773.

You'll need use `-Select signInActivity` to $select the signIn activities of a user and `select-object -ExpandProperty` to expand the signInActivity property, or hold the response in a variable:
``` powershell
Get-MgUser -all -Select id, signInActivity | select-object -ExpandProperty signInActivity
``` 

See https://learn.microsoft.com/graph/api/resources/user?view=graph-rest-1.0#properties for more details.

**Comment by peombwa** [comment] 2023-10-25 17:19
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/485#issuecomment-790131773.

**Closed by peombwa** 2023-10-25 17:19 UTC

**Comment by jiaxaiol** [comment] 2023-11-02 06:55
@peombwa  Looks it doesn't work on Azure China, could you help to have a look? In our test we found use the same client pc, it works on Azure global, but doesn't work on Azure China, see the attachment
![info](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/29366114/a5d06662-ec36-4915-9328-dc3ad44842b3)


Thank you.
