### ISSUE TITLE
Microsoft Graph commands including -Search which is unsupported e.g. Get-MgSubscribedSku

### ISSUE THREAD

**Issue by SteveMutungi254** [microsoftgraph/msgraph-sdk-powershell#2456] opened 2023-11-21 19:46 UTC
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
> A clear and concise description of what the bug is.

Graph PS cmdlets are including **-Search** as a parameter which is not supported.

Examples: [Get-MgSubscribedSku](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/get-mgsubscribedsku?view=graph-powershell-1.0), [Get-MgDomain](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/get-mgdomain?view=graph-powershell-1.0)

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/132555836/765a74d8-898d-4387-a18a-677c87a7918f)

**To Reproduce**
1. Execute `-Mg-` with `...`
2. See error at `...`

**Expected behavior**
> A clear and concise description of what you expected to happen.

**Debug Output**
> Run the problematic command with `-Debug` and paste the resulting debug stream below.
> ⚠ ATTENTION: Be sure to remove any sensitive information that may be in the logs.

**Module Version**
> Please run `Get-Module Microsoft.Graph*` after cmdlet execution and paste the output below.
> If a module cannot be installed or imported, please run `Get-Module -ListAvailable` and paste the output.

**Environment Data**
> Please run `$PSVersionTable` and paste the output below. If running the Docker container image, indicate the tag of the image used and the version of Docker engine.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by petrhollayms** [comment] 2024-06-04 15:25
Hi @SteveMutungi254 ,

I tried to reproduce and both cmdlets work with the -Search parameter. It looks like the metadata issue has been fixed in the meantime.

Would you mind testing on your end and give us a feedback about any errors you might see or close this issue?

**Closed** 2024-06-11 16:02 UTC
Labels: Dependency: metadata-issue, no-recent-activity, status:waiting-for-author-feedback
