### ISSUE TITLE
Issues with Microsoft.Identity.Client

### ISSUE THREAD

**Issue by vipulkelkar** [microsoftgraph/msgraph-sdk-powershell#2147] opened 2023-07-11 14:23 UTC
We use the Microsoft Graph PowerShell module along with the 'Az' PowerShell module in Azure function app and the requirements.psd1 specifies the following. The execution runtime is **PowerShell Core**

**'Az' = '6.*'
'Microsoft.Graph' = '1.7.0'**

Since 7/7/2023, we have started observing errors in Microsoft.Graph module. The version 2.0.0 seems to have been released on that day : https://www.powershellgallery.com/packages/Microsoft.Graph/2.0.0

The error we see while trying to connect using "Connect-MgGraph" is :
"_Could not load file or assembly 'Microsoft.Identity.Client, Version=4.49.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Could not find or load a specific file. (0x80131621) Could not load file or assembly 'Microsoft.Identity.Client, Version=4.49.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference._"

The modules have been working well for several months before the release of PowerSHell Graph 2.0.0
We observed that a new module was downloaded on 6/7/2023. 

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/13727430/8b08a8ff-16bd-4aef-8a37-db24c9adfa20)

The difference between the previous and new working module is

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/13727430/f5a3f962-4756-4da8-95f6-0608b80be18f)

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/13727430/dc1b9fee-1625-4420-a62b-aebc0002ae5a)

The Az.Accounts version in both is 2.9.1. I see that the Microsoft.Identity.Client.dll is also there in the Az Accounts module

Although the error says the dll could not be loaded, i can see that DLL of version 4.49.1.0 has been downloaded with the module. Is this an issue with Mg Graph's compatibility with 'Az' module ? Is there a guidance on how to ensure both work seamlessly ?

**Comment by yuanweilei** [comment] 2023-07-17 06:58
I am just curious that why 'Microsoft.Graph' = '1.7.0' got Microsoft.Graph.Authentication 1.9.6 in your Azure function app, because  Microsoft.Graph.Authentication has version 1.10.0 or more. 
https://www.powershellgallery.com/packages/Microsoft.Graph.Authentication/1.10.0

Since Microsoft.Graph.Authentication 2.1.0 was released, it seems 'Microsoft.Graph' = '1.7.0' will get Microsoft.Graph.Authentication 2.1.0 now.

**Comment by peombwa** [comment] 2023-07-17 22:17
This is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2164#issuecomment-1638898941. The ability to install older versions of the SDK was added in v1.12.2.

Please use the latest version of v1.x (v1.28.0) if your goal is to use v1.x - `Install-Module -Name Microsoft.Graph -RequiredVersion 1.28.0`.

**Closed by peombwa** 2023-07-17 22:17 UTC
Labels: ToTriage
