### ISSUE TITLE
New-MgGroup and mailEnabled

### ISSUE THREAD

**Issue by markwahl-msft** [microsoftgraph/msgraph-sdk-powershell#748] opened 2021-07-08 23:57 UTC
In Graph beta,  [create group](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-beta&tabs=http) specifies that the request payload should have
| Property | Type | Description|
|:---------------|:--------|:----------|
| mailEnabled | boolean | Set to **true** for mail-enabled groups. Required. |

Note this field is required, if I attempt to create a group and do not provide **mailEnabled** in the request,  the request fails with
```
{"error":{"code":"Request_BadRequest","message":"A value is required for property 'mailEnabled' of resource 'Group'."
```
However, the cmdlet syntax for **New-MgGroup** in beta is that **[-MailEnabled]** is an optional parameter.
Invoking New-MgGroup does not send **mailEnabled: false** and so the request fails.

In order to create a non-mail-enabled group, the workaround I see is to use **additionalproperties**, as in

```powershell
$ht = @{}
$ht["mailEnabled"] = $false
New-MgGroup -DisplayName "s" -SecurityEnabled -AdditionalProperties $ht -MailNickname "s"
```

It would be preferable if

```powershell
New-MgGroup -DisplayName "s" -SecurityEnabled
```

could be used to create a non-mail-enabled security group.

 
[AB#10168](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10168)

**Comment by peombwa** [comment] 2021-07-16 01:15
@markwahl-msft, a quick work around is to the set `-SecurityEnabled` to false using `-SecurityEnabled:$false`. This sets the value of the switch to `$false` (not ideal).
``` powershell
New-MgGroup -DisplayName "s" -SecurityEnabled:$false -Debug
```

A complete fix for this issue will need to come from 2 places:
1. Workload owners should annotate this property as required. This can be done by adding [RequiredProperties](https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.md#insertrestrictionstype) capability annotation in the $metadata. We currently treat `-SecurityEnabled` as optional because that's what the default is if `RequiredProperties` isn't specified.
2. AutoREST should serialize `switch` parameters that haven't been set to `false`. Alternatively, `boolean` properties should be generated as `boolean` parameters.

**Comment by peombwa** [comment] 2022-03-11 00:05
Will be fixed by https://github.com/microsoftgraph/msgraph-metadata/issues/128.

**Comment by AspenForester** [comment] 2022-11-15 17:09
As a PowerShell user I would like to see parameters that "look like" switches be coded as `[Switch]`.  Parameters coded as `[Boolean]' should be avoided unless the the `$null` state is also valid.  API parameters that are "mandatory" are still fulfilled, with a value of `$false` when a switch parameter is not explicitly provided at the Command Line.

**Comment by peombwa** [comment] 2023-01-24 22:09
The property will remain a [switch] as explained in https://github.com/Azure/autorest.powershell/issues/1040#issuecomment-1352442281.

Closing since the issue is being tracked in https://github.com/microsoftgraph/msgraph-metadata/issues/128.

**Closed by peombwa** 2023-01-24 22:09 UTC
Labels: Bug, Dependency: metadata-issue, missing-annotation
