### ISSUE TITLE
Function capacity 4096 has been exceeded for this scope When Import the Graph Module 

### ISSUE THREAD

**Issue by blackfoxsar** [microsoftgraph/msgraph-sdk-powershell#1488] opened 2022-09-05 06:31 UTC
Hi
I trying to use Import-Module Microsoft.Graph and encountered a error:
```
Import-Module : Function New-MgGroupDriveRootListItemVersion cannot be created because function capacity 4096 has been exceeded for this scope.
```

I trying to understand and find when i changed the 
```
$MaximumVariableCount = 8192
$MaximumVariableCount = 8192
```
and try to import again, the issue can be solve.

But the problem is looks like the default is 4096, and yes i can change the variable values to 8192 or other but it's may not is a good solution. 

Btw, 
Graph module version = 1.11.1
pwsh ver = 5.1
OS ver = Windows 11 Enterprise 21H2

**Comment by peombwa** [comment] 2022-09-12 22:05
@blackfoxsar, please see the available options at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1449#issuecomment-1213550597.

This is a known limitation with PowerShell 5.1 and not the SDK. Microsoft Graph API has ~7k+ unique paths (translates to ~7k+ commands). The unique paths/commands already surpass the default limit of 4096 PowerShell 5.1. The limit was removed in PowerShell 7+. Upgrading to PowerShell 7+ is the path of least resistance.

**Comment by peombwa** [comment] 2022-09-12 22:05
Closing as duplicate of #1449.

**Closed by peombwa** 2022-09-12 22:05 UTC
Labels: question

**Comment by thiagobeier** [comment] 2022-10-25 14:39
I got this working **PowerShell 7** , 
any tips on how to have powershell 7 for automation through azure functions or either using through proactive remediation in intune "automation"?

PS C:\Users\thiago> **Select-MgProfile -Name "beta"**
PS C:\Users\thiago> Import-Module Microsoft.Graph
PS C:\Users\thiago> Import-Module Microsoft.Graph.DeviceManagement.Administration
PS C:\Users\thiago> Get-MgDeviceManagementRoleScopeTag

Id Description
-- -----------
0  Default Role Scope Tag. This will exist by default on all Intune entities whenever a user defined Role Scope Tag is…
8
