### ISSUE TITLE
Get-MgEntitlementManagementAccessPackageApplicablePolicyRequirement InvalidCastException

### ISSUE THREAD

**Issue by markwahl-msft** [microsoftgraph/msgraph-sdk-powershell#941] opened 2021-11-17 19:53 UTC
POST https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackages/642181f0-bc17-4fc6-9ebb-ff53dbf18c2f/microsoft.graph.getApplicablePolicyRequirements
returns 
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#Collection(microsoft.graph.accessPackageAssignmentRequestRequirements)",
    "value": []
}
```
but
```
Get-MgEntitlementManagementAccessPackageApplicablePolicyRequirement -AccessPackageId $id -Verbose -Debug 
```
fails with
```
DEBUG: [CmdletException]: Received exception with message 'InvalidCastException - Unable to cast object of type 'Microsoft.Graph.PowerShell.Runtime.Json.JsonObject' to type 'Microsoft.Graph.PowerShell.Runtime.Json.JsonArray'. :    at Microsoft.Graph.PowerShell.Runtime.Json.JsonArray.Parse(String text)
   at Microsoft.Graph.PowerShell.IdentityGovernance.<>c.<IdentityGovernanceEntitlementManagementAccessPackagesGetApplicablePolicyRequirements_Call>b__1354_0(Task`1 body)
   
```

**Comment by peombwa** [comment] 2021-11-19 19:12
This is an issue with the OpenAPI document and will be fixed by https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/571.

**Comment by peombwa** [comment] 2021-11-19 19:13
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/665.

**Closed by peombwa** 2021-11-19 19:13 UTC
Labels: OpenApiService-Dependency
