### ISSUE TITLE
Get-MGGroupOwner in 2.6 errors

### ISSUE THREAD

**Issue by andersidahl** [microsoftgraph/msgraph-sdk-powershell#2312] opened 2023-09-20 07:59 UTC
**Describe the bug**
Get-MGGroupOwner fails in version 2.6 with error:
Unable to find type [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet].
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Groups\2.6.0\exports\ProxyCmdletDefinitions.ps1:30673 cha
r:52

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10434858/7d1da1a7-5998-4954-aab6-932b8ca5370a)

**To Reproduce**
Get-MGGroupOwner -GroupId xxxxxxx

**Comment by peterboba** [comment] 2023-09-20 08:36
We're hitting the same issue - seems like the just released 2.6 version is broken

**Describe the bug**
Multiple cmdlets in version 2.6 of Microsoft.Graph fail with
`Unable to find type [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet]`

**To Reproduce**
Steps to reproduce the behavior:
Execute:
```
Get-MgApplication -Filter "AppId eq 'hello'"
```

Fails with:
```
Unable to find type [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet].
At C:\Program
Files\WindowsPowerShell\Modules\Microsoft.Graph.Applications\2.6.0\exports\ProxyCmdletDefinitions.ps1:11961 char:52
+ ... ommand -and [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePS ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Windo...n.AzurePSCmdlet:TypeName) [], ParentContainsErrorRe
   cordException
    + FullyQualifiedErrorId : TypeNotFound
```

**Expected behavior**
```
Get-MgApplication -Filter "AppId eq 'hello'" 
Get-MgApplication_List1: Authentication needed, call Connect-MgGraph.
```

**Debug Output**
```
Get-MgApplication -Filter "AppId eq 'hello'" -Debug
Unable to find type [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet].
At C:\Program
Files\WindowsPowerShell\Modules\Microsoft.Graph.Applications\2.6.0\exports\ProxyCmdletDefinitions.ps1:11961 char:52
+ ... ommand -and [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePS ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Windo...n.AzurePSCmdlet:TypeName) [], ParentContainsErrorRe
   cordException
    + FullyQualifiedErrorId : TypeNotFound
```

**Module Version**
```
Get-Module Microsoft.Graph*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.6.0      Microsoft.Graph.Applications        {Add-MgApplicationKey, Add-MgApplicationPassword, Add-MgSe...
Script     2.6.0      Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, G...

```

**Environment Data**
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by eagle00789** [comment] 2023-09-20 08:56
It is many Get-MG commands that have this issue and isn't limited to the ones mentioned here already

**Comment by MTI-gh** [comment] 2023-09-20 09:02
Can confirm, seeing the issues appear with Get-Mg commands. (example: Get-MgGroup)

**Comment by rsta7540** [comment] 2023-09-20 09:43
I am also seeing the same issue running Get-Mg cmdlets in version 2.6.0.

For instance, when running:
Get-MgGroup -All:$true;
InvalidOperation: C:\Users\\..\Documents\PowerShell\Modules\Microsoft.Graph.Groups\2.6.0\exports\ProxyCmdletDefinitions.ps1:43080
 Line |
43080 |  … ommand -and [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePS …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Unable to find type [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet].

**Comment by bonm014** [comment] 2023-09-20 10:25
Same here when I want to get all users.
But reverting back to 2.5 give me the same error

**Comment by peterboba** [comment] 2023-09-20 10:35
> Same here when I want to get all users. But reverting back to 2.5 give me the same error

2.5.0 works fine for me. So it's likely that it's still loading the assemblies from 2.6.0 and that causes the error or you haven't reverted completely.

**Comment by DarrenGowing** [comment] 2023-09-20 11:21
I was getting "Unable to find type [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet]." using any MG-Graph command. I found this this module is broken:

C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Files\2.6.0\exports\ProxyCmdletDefinitions.ps1

To fix it I removed this section starting from line 89490

        if ($null -ne $MyInvocation.MyCommand -and [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet]::PromptedPreviewMessageCmdlets -notcontains $MyInvocation.MyCommand.Name -and [Microsoft.Graph.PowerShell.Runtime.MessageAttributeHelper]::ContainsPreviewAttribute($cmdInfo, $MyInvocation)){
            [Microsoft.Graph.PowerShell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
            [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet]::PromptedPreviewMessageCmdlets.Enqueue($MyInvocation.MyCommand.Name)
        }

**Comment by DarrenGowing** [comment] 2023-09-20 11:34
Hmm, running another Graph command i got:

Unable to find type [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet].
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Files\2.6.0\exports\ProxyCmdletDefinitions.ps1:545000
char:52

So again I removed from line 545000 this section and now that command works:

        if ($null -ne $MyInvocation.MyCommand -and [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet]::PromptedPreviewMessageCmdlets -notcontains $MyInvocation.MyCommand.Name -and [Microsoft.Graph.PowerShell.Runtime.MessageAttributeHelper]::ContainsPreviewAttribute($cmdInfo, $MyInvocation)){
            [Microsoft.Graph.PowerShell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
            [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet]::PromptedPreviewMessageCmdlets.Enqueue($MyInvocation.MyCommand.Name)
        }

It looks like the same command is used for every Mg-Graph command so a quick find and replace all commands now work.

I think someone needs to fix this module "C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Files\2.6.0\exports\ProxyCmdletDefinitions.ps1"

**Comment by UnixC0rn** [comment] 2023-09-20 13:50
Got the same issue for Get-MGUser, New-MgUser, Get-MgSubscribedSku, Set-MgUserLicense, ... 
Deleting the Lines mentioned by @DarrenGowing in the corresponding File fixed the issue.

**Comment by fasteiner** [comment] 2023-09-20 13:54
Can confirm: we got a similar issue when using "Get-MGGroup":
<img width="944" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/75947402/338ef126-9086-405c-b7a3-0334dc00770f">

**Comment by 8ctavious** [comment] 2023-09-20 18:06
Can confirm the same issue with 2.6.0 since updating. I have had to pull the ability to update Microsoft.Graph from scripts for now. 
Also working on a way to roll back if 2.6 is installed anywhere. It's annoying that I discovered this when it started breaking stuff. 

Surprised that no one from Microsoft is assigned this bug yet to look at.

**Comment by AdamPhils** [comment] 2023-09-20 19:56
If anyone still  have problem even after uninstalling 2.6.0 version like I had, I found out that module files still exist for some reason and I created small script to get rid of them one by one (this helped me, maybe someone else will find it useful). It is taking a lot of time though. 

$allgraphmodules = (Get-InstalledModule -Name "Microsoft.Graph.*").Name
foreach ($module in $allgraphmodules) {
    Uninstall-Module -Name "$module" -RequiredVersion "2.6.0" -Force
}

**Comment by ddyett** [comment] 2023-09-20 21:17
a dependency was introduced here inside of autorest that is for Azure SDK but we don't have.  We are going to roll versions of autorest back and push out a 2.6.1 version.  It will take a few hours to complete.

**Comment by kreuzer0351** [comment] 2023-09-21 01:14
did you test before you released this? Seems like a huge stuff up

**Comment by peterboba** [comment] 2023-09-21 10:34
Can confirm that 2.6.1 is not affected by this and since 2.6.0 has been removed from Powershell gallery I guess this can be closed.

**Comment by timayabi2020** [comment] 2023-09-21 11:06
@peterboba thank you for the feedback.

**Closed by timayabi2020** 2023-09-21 11:06 UTC
Labels: Bug - P1
