### ISSUE TITLE
Get-MgSite should be pipeable to Get-MgSiteDrive

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#1282] opened 2022-05-25 22:46 UTC
`MicrosoftGraphSite1` should implement `ISitesIdentity` so that this piping will work.

**Comment by ddyett** [comment] 2022-06-16 15:45
@peombwa is this something we could do with autorest?

**Comment by peombwa** [comment] 2022-06-21 22:37
Piping does not currently work due to how path keys segments are named in the OpenAPI. Ids of output types don't match the ids of the InputObject (`ISitesIdentity`). e.g. `Get-MgSite` returns an object of type `MicrosoftGraphSite1` with `Id` as the key property, yet `ISitesIdentity` object of `Get-MgSiteDrive` expects the key property to be named `SiteId`.

You can currently bypass this limitation by constructing the input object with the right key property name as shown below:
``` powershell
 Get-MgSite -SiteId root |%{@{SiteId = $_.Id}} | Get-MgSiteDrive
```

We will address this in v2 of the SDK since fixing it will involve a breaking change. See #906.

**Comment by peombwa** [comment] 2022-06-21 22:39
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/906.

**Closed by peombwa** 2022-06-21 22:39 UTC
Labels: Status: Needs Investigation, Bug - P2
