### ISSUE TITLE
Remove-MgApplication needs the Object ID of a application, not the Application ID

### ISSUE THREAD

**Issue by mr-oliva** [microsoftgraph/msgraph-sdk-powershell#992] opened 2021-12-23 07:00 UTC
ApplicationId option is required when we use Remove-MgApplication command.

I input the application id as ApplicationId option, but, this command return a error.
Then, I input the object id as ApplicationId option.
I succeeded in removing application.
  
![image](https://user-images.githubusercontent.com/10346162/147200527-45607219-7104-49e4-85d8-66e6a8eac5f6.png)

I think this option name cause confusion...

**Comment by peombwa** [comment] 2022-01-04 19:35
@mr-oliva, yes, the value set on `-ApplicationId` needs to be the `objectId` (in Azure) and `id` (MS Graph). `Application (client) Id` in Azure corresponds to `appId` in MS Graph, see https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0#properties. Also, it is worth noting that Azure properties do not directly mirror MS Graph's properties.

@maisarissi, here is another reason why we need to rename top-level key-segments in DevX API as described here https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/906. Let's prioritize this in v2.

**Comment by peombwa** [comment] 2022-01-04 19:36
Will be fixed by #906.

Closing as duplicate of #906.

**Closed by peombwa** 2022-01-04 19:36 UTC
Labels: question

**Comment by mr-oliva** [comment] 2022-01-11 07:19
@peombwa, thank you for your response.
I understood that Azure properties do not directly mirror MS Graph's properties, and I'm looking forward to using v2 👍
