### ISSUE TITLE
Copy-MgTeam does not return the header location url to query to see if completed

### ISSUE THREAD

**Issue by techienickb** [microsoftgraph/msgraph-sdk-powershell#1485] opened 2022-09-01 12:28 UTC
Copy-MgTeam does not return the header location url to query to see if completed.

Had to instead use Invoke-MgGraphRequest -OutputType HttpResponseMessage to get the Location url.

**Comment by timayabi2020** [comment] 2022-09-15 11:16
Hi @techienickb ,
Thanks for identifying and raising this issue. As per the [service documentation](https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-beta&tabs=powershell) the only response you are going to get is a http status code 202.
We will however consider returning the header location url in future releases. Meanwhile, you can run the command with a ```-debug ``` flag in order to get the url.



![Image](https://user-images.githubusercontent.com/10947120/190390201-3d089748-f5eb-4037-89f0-3ca9f8186cb2.png)

**Comment by techienickb** [comment] 2022-09-15 11:21
Glad it'll be looked at in a future release.

From the doc

> If successful, this method will return a 202 Accepted response code with a Location: header pointing to the [operation](https://docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation) resource. When the operation is complete, the operation resource will tell you the id of the created team.

So yes while 202 is the response code a location header is also part of the mandatory return.  The debug command doesn't help when it's part of a wider script and the location header is used in the next part of the script and you need direct access to the location header to query if the job is complete before moving onto the next step.

I've used the invoke command to get around this in my script I've written.

**Comment by peombwa** [comment] 2022-12-14 18:58
Closing as a duplicate of #897.

We are using #897 to track long running operation support (202 response code). The workaround is to use `Invoke-MgGraphRequest`.

**Closed by peombwa** 2022-12-14 18:58 UTC
Labels: enhancement
