### ISSUE TITLE
New-MgGroup has a parameter set with more than 50 parameters (most of them cannot be used)

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/msgraph-sdk-powershell#1804] opened 2023-02-12 01:58 UTC
The `New-MgGroup` has the "CreateExpanded" parameter set that contains more than 50 parameters.
When you look at the list of parameters, you will realize that those are property names. 
Some of those properties cannot be set at all, because they are **read-only**.
If you look at the syntax (`Get-Command New-MgGroup -Syntax`) or a help file, not a single parameter in that parameter set is marked as required. But, there are 4 required parameters.

How is possible that such a common cmdlet is generated so badly?

Btw, the help file is not usable at all because it describes the properties of the group object, not the parameters of the cmdlet. And, it's missing the important example to show how to use the `-BodyParameter` parameter. That's probably a topic for another issue. :(

**Comment by peombwa** [comment] 2023-02-22 01:21
Related to https://github.com/microsoftgraph/msgraph-metadata/issues/128.

There is nothing in the service schema that we can safely rely on to know which properties are read-only, and which ones aren't:
![image](https://user-images.githubusercontent.com/7061532/220495849-278387b6-9c4a-4e08-8cf5-757b67c36f40.png)

API owners will need to annotate read-only properties with computed annotation as I mentioned in https://github.com/microsoftgraph/msgraph-metadata/issues/128. We are actively following up with API owners to ensure their service schemas accurately describe their APIs.

**Comment by peombwa** [comment] 2023-02-22 01:23
Closing as duplicate of https://github.com/microsoftgraph/msgraph-metadata/issues/128.

**Closed by peombwa** 2023-02-22 01:23 UTC
Labels: ToTriage

**Comment by alexandair** [comment] 2023-02-22 01:42
@peombwa What about the required parameters? How can a user know what is required? All parameters are marked as optional in help and when you programmaticaly look at the syntax. Still, when you try to use New-MgGraph you will be prompted for the missing parameters.
