### ISSUE TITLE
Get-MgInformationProtectionBitlockerRecoveryKey Fails With Missing User-Agent Error

### ISSUE THREAD

**Issue by dfwarden** [microsoftgraph/msgraph-sdk-powershell#920] opened 2021-10-27 17:56 UTC
I believe this is a duplicate/new instance of #630 where the REST API endpoint requires a User-Agent. The following invocation shows the error:
```
> Get-MgInformationProtectionBitlockerRecoveryKey -debug                                                                                            DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: https://graph.microsoft.com/beta/informationProtection/bitlocker/recoveryKeys
DEBUG: RequestCreated: https://graph.microsoft.com/beta/informationProtection/bitlocker/recoveryKeys
DEBUG: HeaderParametersAdded: https://graph.microsoft.com/beta/informationProtection/bitlocker/recoveryKeys
DEBUG: GET /beta/informationProtection/bitlocker/recoveryKeys HTTP/1.1
HTTP: graph.microsoft.com


DEBUG: BeforeCall: 
DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 
Get-MgInformationProtectionBitlockerRecoveryKey_List: The request failed with status BadRequest (400). Parameter (User-Agent) is required but missing from headers
DEBUG: GET https://graph.microsoft.com/beta/informationProtection/bitlocker/recoveryKeys
HTTP/1.1 400 Bad Request
Date: Wed, 27 Oct 2021 17:42:26 GMT
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 06567d78-77a6-4453-9752-d78f0b7a1009
client-request-id: 06567d78-77a6-4453-9752-d78f0b7a1009
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Central US","Slice":"E","Ring":"5","ScaleUnit":"004","RoleInstance":"CH01EPF00003ED3"}}
Content-Type: application/json
Content-Encoding: gzip
```
```json
{
  "error": {
    "code": "invalid_request",
    "message": "The request failed with status BadRequest (400). Parameter (User-Agent) is required but missing from headers",
    "innerError": {
      "date": "2021-10-27T17:42:27",
      "request-id": "06567d78-77a6-4453-9752-d78f0b7a1009",
      "client-request-id": "06567d78-77a6-4453-9752-d78f0b7a1009"
    }
  }
}
```
I am able to use Invoke-MgGraphRequest to get data from this endpoint, which sets a User-Agent:
```
> Invoke-MgGraphRequest GET '/beta/informationProtection/bitlocker/recoveryKeys' -debug                                                             VERBOSE: GET https://graph.microsoft.com/beta/informationProtection/bitlocker/recoveryKeys with 0-byte payload

DEBUG: GET /beta/informationProtection/bitlocker/recoveryKeys HTTP/1.1
HTTP: graph.microsoft.com
User-Agent: Mozilla/5.0 (Macintosh; Darwin 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64; en-US) PowerShell/7.1.5 Invoke-MgGraphRequest


VERBOSE: received 2455-byte response of content type application/json

DEBUG: GET https://graph.microsoft.com/beta/informationProtection/bitlocker/recoveryKeys
HTTP/1.1 200 OK
Date: Wed, 27 Oct 2021 17:48:25 GMT
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 0ac4ad50-bc1c-4811-b7ed-546ab4745ca6
client-request-id: 0ac4ad50-bc1c-4811-b7ed-546ab4745ca6
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Central US","Slice":"E","Ring":"5","ScaleUnit":"005","RoleInstance":"CH01EPF0000B205"}}
OData-Version: 4.0
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; IEEE754Compatible=false; charset=utf-8
Content-Encoding: gzip

...private response payload snipped...
```

**Comment by peombwa** [comment] 2021-11-01 23:41
@dfwarden, thanks for surfacing this. We will fix this in our next release by pre-populating the User-Agent request header. Duplicate of #630.

**Closed** 2021-11-02 16:02 UTC
Labels: duplicate, Bug: Client
