### ISSUE TITLE
Get-MgServicePrincipal incorrectly returns empty PasswordCredentials and KeyCredentials

### ISSUE THREAD

**Issue by cnotin** [microsoftgraph/msgraph-sdk-powershell#1848] opened 2023-03-06 16:19 UTC
When I try to retrieve the `PasswordCredentials` and `KeyCredentials` attributes of a service principal, using the MS Graph PowerShell SDK, I get empty results whereas I know that this SP have them.

Env info:
```powershell
PS C:\> Get-InstalledModule Microsoft.Graph

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.23.0               Microsoft.Graph                     PSGallery            Microsoft Graph PowerShell module


PS C:\> Connect-MgGraph -Scopes "Application.Read.All"
Welcome To Microsoft Graph!
```

Empty results returned:
```powershell
PS C:\> Get-MgServicePrincipal -filter "appid eq '00000005-0000-0ff1-ce00-000000000000'" | fl passwordcredentials,keycredentials


PasswordCredentials : {}
KeyCredentials      : {}
```

Proof that both types of credentials exist:
```powershell
PS C:\> $out = Invoke-MgGraphRequest -Method GET "https://graph.microsoft.com/v1.0/servicePrincipals?`$filter=appid%20eq%20'00000005-0000-0ff1-ce00-000000000000'"
PS C:\> $out.value[0]["passwordCredentials"]

Name                           Value
----                           -----
keyId                          3abdfc74-077a-43fb-bca9-e1f669354012
hint                           tot
endDateTime                    11/01/2024 13:11:51
displayName
customKeyIdentifier
startDateTime                  11/01/2023 13:11:51
secretText


PS C:\> $out.value[0]["keyCredentials"]

Name                           Value
----                           -----
key
startDateTime                  05/01/2023 09:55:41
keyId                          e37541dc-df43-4c84-b3df-8cd6074cf18e
usage                          Verify
endDateTime                    06/01/2023 09:55:40
type                           AsymmetricX509Cert
customKeyIdentifier            QXRvbWljVGVzdA==
displayName                    CN=atomicredteam.example.com
```

Another proof of the bug, is this API capture, using Fiddler, of the Graph API request that Get-MgServicePrincipal did:
![image](https://user-images.githubusercontent.com/550823/223168530-67a2ff7a-9f6b-40ad-bdc7-ca138d30104b.png)

**Comment by cnotin** [comment] 2023-03-06 16:55
Same with v2:
```powershell
PS C:\> Get-InstalledModule Microsoft.graph

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.0.0-preview5       Microsoft.Graph                     PSGallery            Microsoft Graph PowerShell module

PS C:\> Connect-MgGraph -Scopes "Application.Read.All"
Welcome To Microsoft Graph!
PS C:\> Get-MgServicePrincipal -filter "appid eq '00000005-0000-0ff1-ce00-000000000000'" | fl passwordcredentials,keycredentials

PasswordCredentials : {}
KeyCredentials      : {}

```

**Comment by cnotin** [comment] 2023-03-06 18:10
However, it works if I access the attributes of the returned PowerShell object. Am I missing something?
```powershell
PS C:\> $sp = Get-MgServicePrincipal -filter "appid eq '00000005-0000-0ff1-ce00-000000000000'"
PS C:\> $sp | fl passwordcredentials,keycredentials


PasswordCredentials : {}
KeyCredentials      : {}



PS C:\> $sp.KeyCredentials

CustomKeyIdentifier    DisplayName                  EndDateTime         Key KeyId                                StartDateTime       Type               Usage
-------------------    -----------                  -----------         --- -----                                -------------       ----               -----
{65, 116, 111, 109...} CN=atomicredteam.example.com 06/01/2023 09:55:40     e37541dc-df43-4c84-b3df-8cd6074cf18e 05/01/2023 09:55:41 AsymmetricX509Cert Verify


PS C:\> $sp.PasswordCredentials

CustomKeyIdentifier DisplayName EndDateTime         Hint KeyId                                SecretText StartDateTime
------------------- ----------- -----------         ---- -----                                ---------- -------------
                                11/01/2024 13:11:51 tot  3abdfc74-077a-43fb-bca9-e1f669354012            11/01/2023 13:11:51

```

**Comment by peombwa** [comment] 2023-03-14 19:25
Closing as duplicate of #1849.

The same explanation applies to both PasswordCredentials and KeyCredentials.

**Closed by peombwa** 2023-03-14 19:25 UTC
Labels: ToTriage
