### ISSUE TITLE
Get-MgUserMailFolder does not provide a way to include or return hidden mail folders.

### ISSUE THREAD

**Issue by ThoughtContagion** [microsoftgraph/msgraph-sdk-powershell#1864] opened 2023-03-13 14:05 UTC
Using the REST API does work, however a pure PowerShell implementation fails.

The `IsHidden` attribute is returned when running the `Get-MgUserMailFolder -UserId $userId` query but no hidden folder are returned, even using the `-All` switch. 

Issuing the command `Get-MgUserMailFolder -UserId $userId -Filter "isHidden+eq+true"` returns the error `Get-MgUserMailFolder : Invalid filter clause`.

Microsoft Graph Explorer code snippets provides the following command which also throws errors about the `-IncludeHiddenFolders' switch and the invalid filter.

`Get-MgUserMailFolder -UserId $userId -Includehiddenfolders true -Filter "isHidden+eq+true"`

**Comment by peombwa** [comment] 2023-03-16 22:17
Thanks for bringing this to our attention.

This is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1339. The issue has been resolved in [v2 preview 6](https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.0.0-preview6). Please you this version instead.

If you are using v1.23.0, please use the suggestion at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1339#issuecomment-1165891565 to unescaped the filter value before passing it to the command.

Closing as duplicate of #1339.

**Closed by peombwa** 2023-03-16 22:17 UTC
Labels: ToTriage

**Comment by ThoughtContagion** [comment] 2023-03-16 23:06
Much appreciated!
