### ISSUE TITLE
Add @odata.nextLink as a property that is returned for Get-MgPlaceAsRoom or provide clear method of pagination

### ISSUE THREAD

**Issue by dotnvo** [microsoftgraph/msgraph-sdk-powershell#2260] opened 2023-08-22 20:41 UTC
**Is your feature request related to a problem? Please describe.**

Not sure if feature or bug, so putting as feature but can correct if needed. 

I haven't found a way to properly paginate through Get-MgPlaceAsRoom. I can get 999 results by setting the page size to 999, but if I have more than that, there's not a `@odata.NextLink` property that is returned. I can use the countvariable to get a total count and use the `-Skip` switch to skip and use some math to determine how many times I need to loop and build a skip value myself.

Should this property be returned (AKA this is a bug) or is this something not in scope for places?
**Describe the solution you'd like**
I'd like to be able to easily get all objects in a tenant with this command. It'd be nice if there was a property returned that aligned with [MS Graph Paging](https://learn.microsoft.com/en-us/graph/paging). 

It seems commands like `Get-MgUser` actually return the property '@odata.nextLink' so it's easy to paginate but this command doesn't have that in the response.

**Describe alternatives you've considered**

As mentioned, I've used the 'Skip' switch and count variable along with doing some math to figure out how many loops I need. It works, but it's a tad clunky. I think it might be the only option right now (though it's very possible I'm missing something).

I tried using `-all` as well but it's limited by the 999 pagesize limit. I think this has been noted on other issues as well.

I tried using Invoke-MGGraphRequest but it also doesn't seem to have the `@odata.nextlink`. 

It's very possible there is a way to do this and I'm just not seeing it, but digging around i found others claiming they don't see it either.

**Comment by peombwa** [comment] 2023-08-28 17:55
Thanks for following up on this.

Per the [Microsoft Graph Q&A response](https://learn.microsoft.com/en-us/answers/questions/1161943/places-api-with-microsoft-graph-room-return-incons), this is by design. The API ([https://graph.microsoft.com/v1.0/places/microsoft.graph.room](https://learn.microsoft.com/en-us/graph/api/place-list?view=graph-rest-1.0&tabs=http)) does not support paging by `@odata.NextLink`. The API instead supports paging by `$top` (-pageSize) and `$skip`(-Skip) as you've pointed out above.

Please open an API feature request at https://developer.microsoft.com/graph/support if paging by `@odata.NextLink` is something you'd like to see supported by API.

**Comment by dotnvo** [comment] 2023-08-31 20:15
Sure thing, appreciate the resources/response. I will likely fill out the form as I believe there's a big benefit to having some consistency where possible across commands. That applies to things like `-all` as well, where the behavior with a command like `Get-MgUser` will actually return all results, but with this command, it will not if there are more than 999.

**Comment by peombwa** [comment] 2023-09-08 21:40
Thanks for logging the service feature request. +1 to having consistency across all APIs.

I'll close the issue since this is by design (today) and is being tracked as a service feature request. Please past the link to feature request in this issue to help others find it.

**Closed by peombwa** 2023-09-08 21:40 UTC
Labels: Needs: Attention :wave:, Question: API
