### ISSUE TITLE
New-MgBetaDeviceManagementTemplateInstance & Update-MgBetaDeviceManagementIntentMultipleSetting throw errors on apparent success

### ISSUE THREAD

**Issue by jpedlow** [microsoftgraph/msgraph-sdk-powershell#2203] opened 2023-07-28 20:29 UTC
**Describe the bug**
New-MgBetaDeviceManagementTemplateInstance and Update-MgBetaDeviceManagementIntentMultipleSetting each appear to throw errors, despite being fed correct (atleast in previous versions) information.
Even though they error, they do proceed as intended. However, I'm unable to dynamically get the devicemanagementID to run the second command, due to the error output. Any attempt thus far to play with New-MgBetaDeviceManagementTemplateInstance has resulted in an error.

**To Reproduce**
Steps to reproduce the behavior (worked similarly on older versions, updated to include "beta" in cmdlets):

```
$intentsettings = [abunchofJSON]
$newinstance = New-MgBetaDeviceManagementTemplateInstance -DisplayName "bitlocker" -Description "bitlocker intent" -DeviceManagementTemplateId "d1174162-1dd2-4976-affc-6667049ab0ae"
Update-MgBetaDeviceManagementIntentMultipleSetting -DeviceManagementIntentId $newinstance.id -BodyParameter $intentSettings

```
alternate (which actually almost works but throws errors):
```
$intentsettings = [abunchofJSON]
New-MgBetaDeviceManagementTemplateInstance -DisplayName $intentdata.DisplayName -Description $intentdata.description -DeviceManagementTemplateId $intentdata.TemplateId
$newinstance = (get-mgbetadevicemanagementintent | sort lastmodifieddatetime -Descending)[0] | where DisplayName -like $intentdata.displayname 
Update-MgBetaDeviceManagementIntentMultipleSetting -DeviceManagementIntentId $newinstance.id -BodyParameter $intentSettings
```

if you'd like filler for [abunchofjson]:

```
$intentsettings= @(
    @{
        "settings" = @(
            @{
                "@odata.type"  = "#microsoft.graph.deviceManagementBooleanSettingInstance"
                "definitionId" = "$($definitionBase)bitLockerEncryptDevice"
                "value"        = $true
            }
            @{
                "@odata.type"  = "#microsoft.graph.deviceManagementBooleanSettingInstance"
                "definitionId" = "$($definitionBase)bitLockerEnableStorageCardEncryptionOnMobile"
                "value"        = $true
            }
            @{
                "@odata.type"  = "#microsoft.graph.deviceManagementBooleanSettingInstance"
                "definitionId" = "$($definitionBase)bitLockerDisableWarningForOtherDiskEncryption"
                "value"        = $true
            }
            @{
                "@odata.type"  = "#microsoft.graph.deviceManagementBooleanSettingInstance"
                "definitionId" = "$($definitionBase)bitLockerAllowStandardUserEncryption"
                "value"        = $true
            }
            @{
                "@odata.type"  = "#microsoft.graph.deviceManagementStringSettingInstance"
                "definitionId" = "$($definitionBase)bitLockerRecoveryPasswordRotation"
                "value"        = "enabledForAzureAd"
            }
        )
    }
) | ConvertTo-Json
```
Errors:

New-MgBetaDeviceManagementTemplateInstance
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/46536194/308b0d82-275b-4b2c-a12d-4945a2446240)
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/46536194/80ed923e-d753-4918-ad64-0fe3cd587aaa)

Update-MgBetaDeviceManagementIntentMultipleSetting:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/46536194/19dfacd0-7c01-4236-acc9-70a15999fe4a)
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/46536194/768bc10b-6e6f-4669-86ed-dcd527496be6)

**Expected behavior**
Commands are expected to run without an error, or more clearly explain the issue if there's a problem with the schema.

**Debug Output**
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/46536194/9220fcbc-a0f9-4f9d-92ce-191f6572671d)
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/46536194/8d46733d-4b9e-4570-b9e4-84671c4054cb)

**Module Version**

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/46536194/d7dc7d34-b9c3-4872-a148-5b0d4ee66942)

**Environment Data**
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/46536194/58e54f2b-1017-4ddd-9724-e168262f8c5f)

**Screenshots**
>It's all screenshots :D 

**Additional context**
> This worked in previous versions, prior to the update, without error. I am willing to accept that I'm doing something wrong, however I am not able to fully grasp the error & debug, given that the cmdlets do go ahead and do the instructed work, albeit throwing an error. 
The errors obviously cause issues for my try-catch, but more annoying is the hack of ($newinstance = (get-mgbetadevicemanagementintent | sort lastmodifieddatetime -Descending)[0] | where DisplayName -like $intentdata.displayname ) that I need to use to get the devicemanagementID in my workaround.

Any and all help greatly appreciated as always :) tyvm

**Comment by peombwa** [comment] 2023-07-31 20:20
Thanks for bringing this to our attention.

We are currently investigating this issue in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2191. Our preliminary investigation points to an issue with the HTTP implementation in .NET 4.x when cloning the request content. As a workaround, please use PowerShell 7.x to run the commands as we investigate the issue.

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2191.

**Closed by peombwa** 2023-07-31 20:20 UTC
Labels: ToTriage

**Comment by jpedlow** [comment] 2023-08-01 15:53
Ok, thank you @peombwa - Let me know if I can be of further help!
Have a great day!
