### ISSUE TITLE
Issues connecting to Microsoft.graph module

### ISSUE THREAD

**Issue by Jason542** [microsoftgraph/msgraph-sdk-powershell#1863] opened 2023-03-13 12:21 UTC
I can get tokens no problem, just connecting is an issue, and seems to be intermittent (ISE and PS).  Same result with access token and  clientID/secret/tenant connection.  

Connect-MgGraph : Could not load type 'Microsoft.Identity.Client.OsCapabilitiesExtensions' from assembly 'Microsoft.Identity.Client, Version=4.16.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'

ModuleType Version    Name
---------- -------    ----
Script     3.1.0      ExchangeOnlineManagement
Script     1.23.0     Microsoft.Graph.Authentication
Manifest   3.1.0.0    Microsoft.PowerShell.Management
Manifest   3.0.0.0    Microsoft.PowerShell.Security
Manifest   3.1.0.0    Microsoft.PowerShell.Utility
Script     4.16.0.3   MSAL.PS
Script     1.0.0.1    PowerShellGet
Script     1.2        PSReadline

**Comment by peombwa** [comment] 2023-03-16 22:00
I am not able to reproduce this issue is PowerShell 5.1, PowerShell 7, and PowerShell ISE using the latest version of the loaded modules:
![image](https://user-images.githubusercontent.com/7061532/225761162-b681bd87-0919-4a26-a057-9fdd3467cea9.png)

Could you please share the following details to help repro the issue:
1. Loaded assemblies before and after `Connect-MgGraph`:
``` powershell
# Provide output of [System.AppDomain]::CurrentDomain.GetAssemblies() | Where-Object Location | Sort-Object -Property FullName | Select-Object -Property FullName, Location

```

2. Loaded modules before and after `Connect-MgGraph`: 
``` powershell
# Provide output of Get-Module here.

```

3. StackTrace of the failed command - `$Error[0].Exception.StackTrace`:
``` powershell
# Provide output of $Error[0].Exception.StackTrace here.

```

4. Your version table:
``` powershell
# Provide output of $PSVersionTable here.

```

5. Detailed repro steps, if any:
``` powershell
# Provide repro steps here.

```

Also, could you try using `v2.0.0-preview6` to see if this version fixes the issue for you? We've made significant to auth assembly resolution in `v2`.

**Comment by Jason542** [comment] 2023-03-17 11:33
Seems adding this did the trick.

***@***.***


***@***.***





Jason Wagner

**Comment by peombwa** [comment] 2023-03-17 15:38
Perfect! I'll go ahead and close the issue then.

**Closed by peombwa** 2023-03-17 15:38 UTC
Labels: Status: Under Investigation, Needs: Attention :wave:
