### ISSUE TITLE
Pipeline execution issue with cmdlets - resultant objectIds fail due to strong naming convention

### ISSUE THREAD

**Issue by mlhickey** [microsoftgraph/msgraph-sdk-powershell#1606] opened 2022-11-01 18:36 UTC
Maybe covered deeper but raising here.  Most cmdlets dependent on ids will fail in pipelines without iteration and resolution to commonize parameter, e.g. you cannot create a pipeline like:
`Get-MgGroup -Search "displayName:MyGroup" -ConsistencyLevel Eventual | Get-MgGroupMember`
as it will not recognize the Id returned by `Get-MgGroup` due to strong naming of parameters.  This results in a prompt for id:
cmdlet Get-MgGroupMember at command pipeline position 2
Supply values for the following parameters:
GroupId:
since ` Get-MgGroupMember` is expecting GroupId and ignores the pipeline named/positional value of Id.

**Comment by peombwa** [comment] 2022-11-02 16:16
The module does not currently support pipeline input due to a limitation by our code generator.

This is being tracked in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/214 as a feature request.

Closing as duplicate of #214.

**Closed by peombwa** 2022-11-02 16:16 UTC
Labels: ToTriage
