### ISSUE TITLE
Information level output has useless information || Microsoft.Graph.PowerShell.Runtime.EventData data 

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/msgraph-sdk-powershell#1369] opened 2022-07-06 09:25 UTC
We are getting Microsoft.Graph.PowerShell.Runtime.EventData spam output whenever we query the graph module please help

**Comment by peombwa** [comment] 2022-07-06 16:47
@ProgrammingWithDJ, which version of the SDK are you using? This is potentially a duplicate of #823.

Please share the output of the following with us:
- `Get-Module Microsoft.Graph, Microsoft.Graph.Authentication`.
- `$PSVersionTable`.
- Your repro steps.

**Comment by ProgrammingWithDJ** [comment] 2022-07-07 05:25
Hello @peombwa thanks for looking into it.

I am getting this error aftering running this command Connect-MgGraph and this is the below output I get.

The command is working as expected however I am spammed with Info: Microsoft.Graph.PowerShell.Runtime.EventData

is there any way we can avoid that ?

Connect Success
● CSV file read check

Read CSV file: Success

Number of readings: 2

The following email addresses are already licensed.
[test01@abc.onmicrosoft.com](mailto:test01@abc.onmicrosoft.com)

● License grant
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData
Info: Microsoft.Graph.PowerShell.Runtime.EventData

**Comment by peombwa** [comment] 2022-07-07 15:27
Which version of the module are using? `Get-Module Microsoft.Graph, Microsoft.Graph.Authentication` should show you the loaded version.

Please update to the latest version using `Update-Module Microsoft.Graph` as the spammy logs was fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/868. I can't repro the issue in v1.10.0.

**Closed** 2022-07-14 16:02 UTC
Labels: Needs: Author Feedback, no-recent-activity
