### ISSUE TITLE
Find-MgGraphPermissions on v2 throws error when not connected

### ISSUE THREAD

**Issue by jasoth** [microsoftgraph/msgraph-sdk-powershell#1778] opened 2023-01-30 21:45 UTC
Unlike v1, Find-MgGraphPerission throws an error when Connect-MgGraph has not been called previously.

![image](https://user-images.githubusercontent.com/17210677/215601979-2a23e09d-8ba7-4393-8f6b-782b1804c1ad.png)

**Comment by peombwa** [comment] 2023-02-02 01:00
Thanks for bringing this to our attention.

I can confirm that this is a bug in v2.x preview due to changes made in `Invoke-MgGraphRequest`. We will issue a bug fix in the upcoming release of v2.x preview.

As a workaround, you can call `Connect-MgGraph` (to initiate an auth session) before using `Find-MgGraphPermission`.

**Comment by peombwa** [comment] 2023-02-25 01:20
Closing as fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.0.0-preview5.

**Closed by peombwa** 2023-02-25 01:20 UTC
Labels: Bug - P1, v2.x
