### ISSUE TITLE
Feature Request: Allow specifying x-ms-throttle-priority via a -Priority parameter

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#959] opened 2021-12-01 01:12 UTC
Cmdlets should have a `-Priority` parameter that allows specifying the priority of a request, so certain high importance queries can take precedence and batch ones can be avoided.

https://docs.microsoft.com/en-us/graph/throttling#request-headers

## Workaround
You can use a `-HttpPipelinePrepend` to inject a priority header, but this should be more user friendly.

**Comment by peombwa** [comment] 2021-12-07 17:45
This is a valid feature request that we can consider supporting. We will need to ensure that the CSDL metadata is annotated with the custom header - `x-ms-throttle-priority`.

@darrelmiller, would you know if `x-ms-throttle-priority` is supported by all APIs?

**Comment by peombwa** [comment] 2023-04-14 17:09
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1570.

Custom request headers are currently not supported by the SDK generator - https://github.com/Azure/autorest.powershell/issues/1005.

**Closed by peombwa** 2023-04-14 17:09 UTC
Labels: Request: Feature
