### ISSUE TITLE
Why does Get-MgUser have the -Skip parameter when $skip query parameter is unsupported?

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/msgraph-sdk-powershell#1771] opened 2023-01-27 21:07 UTC
According to the [List users](https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http) doc, $skip query isn't supported for that method. Still, Get-MgUser has the -Skip parameter and when we try to use it we get an error:

```powershell
Get-MgUser -Skip 3
Get-MgUser_List: '$skip' is not supported by the service.
```
![skip](https://user-images.githubusercontent.com/3135708/215198824-65ca655c-c259-407e-9a23-3a65149705fe.jpg)

**Comment by peombwa** [comment] 2023-01-30 22:48
Thanks for following on this.

Unfortunately, `$skip` is declared as supported in the service schema, our source of truth. The issue is already being tracked in https://github.com/microsoftgraph/msgraph-metadata/issues/135. A fix will be provided by the metadata team.

**Comment by peombwa** [comment] 2023-01-30 22:49
Closing as duplicate of https://github.com/microsoftgraph/msgraph-metadata/issues/135.

**Closed by peombwa** 2023-01-30 22:49 UTC
Labels: Dependency: metadata-issue
