### ISSUE TITLE
Revoke-MgUserSign fails to execute

### ISSUE THREAD

**Issue by gnought** [microsoftgraph/msgraph-sdk-powershell#1131] opened 2022-03-06 10:39 UTC
We face an error, any clue?
``` bash
Revoke-MgUserSign_Revoke1: Object reference not set to an instance of an object.
```

The whole trace is as follows:
``` bash
PS /Users/gnought>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /Users/gnought> Install-Module -Name Microsoft.Graph

PS /Users/gnought> Get-Module Microsoft.Graph -List

    Directory: /Users/gnought/.local/share/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.9.2                 Microsoft.Graph                     Core,Desk

PS /Users/gnought> Connect-MgGraph -Scopes "User.ReadWrite.All, Directory.ReadWrite.All"
Welcome To Microsoft Graph!

PS /Users/gnought> Get-MgUser -UserId gnought<redacted>

Id                                   DisplayName            Mail                           UserPrincipalName              UserType
--                                   -----------            ----                           -----------------              --------
e340cd2f-<redacted> Gnought <redacted> gnought<redacted> gnought<redacted>

PS /Users/gnought> Revoke-MgUserSign -UserId gnought<redacted> -Debug
DEBUG: [CmdletBeginProcessing]: - Revoke-MgUserSign begin processing with parameterSet 'Revoke1'.
DEBUG: [Authentication]: - AuthType: 'Delegated', AuthProviderType: 'InteractiveAuthenticationProvider', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph PowerShell'.
DEBUG: [Authentication]: - Scopes: [Directory.AccessAsUser.All, Directory.ReadWrite.All, Group.ReadWrite.All, openid, profile, User.Read, User.Read.All, User.ReadWrite.All, email].

Confirm
Are you sure you want to perform this action?
Performing the operation "Revoke-MgUserSign_Revoke1" on target "Call remote 'UsersRevokeSignInSessions1' operation".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://graph.microsoft.com/v1.0/users/gnought<redacted>/microsoft.graph.revokeSignInSessions

Headers:
SdkVersion                    : graph-powershell/1.9.2,Graph-dotnet-1.25.1
FeatureFlag                   : 00000047
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Macintosh; Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64; en-US),PowerShell/7.2.1,Revoke-MgUserSign_Revoke1
Accept-Encoding               : gzi

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Transfer-Encoding             : chunked
Location                      : https://graph.microsoft.com/
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 5f3d66fd-<redacted>
client-request-id             : 5f3d66fd-<redacted>
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Korea Central","Slice":"E","Ring":"3","ScaleUnit":"000","RoleInstance":"SE1PEPF00001881"}}
x-ms-resource-unit            : 1
OData-Version                 : 4.0
Date                          : Sun, 06 Mar 2022 10:29:21 GM

Body:



DEBUG: [CmdletException]: Received exception with message 'NullReferenceException - Object reference not set to an instance of an object. :    at Microsoft.Graph.PowerShell.Cmdlets.RevokeMgUserSign_Revoke1.onOk(HttpResponseMessage responseMessage, Task`1 response)
   at Microsoft.Graph.PowerShell.UsersActions.UsersRevokeSignInSessions1_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.UsersActions.UsersRevokeSignInSessions1_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.UsersActions.UsersRevokeSignInSessions1(String userId, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Cmdlets.RevokeMgUserSign_Revoke1.ProcessRecordAsync()'
Revoke-MgUserSign_Revoke1: Object reference not set to an instance of an object.
DEBUG: [CmdletEndProcessing]: - Revoke-MgUserSign end processing.

PS /Users/gnought>
```

**Comment by peombwa** [comment] 2022-03-09 23:47
Thanks for bringing this to our attention. We are already tracking this bug in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/834. A fix will be provided by https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/726 once it has been released.

A workaround is to use `Invoke-MgGraphRequest` to make the request:
``` powershell
 Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/v1.0/users/$UserId/microsoft.graph.revokeSignInSessions" -Method POST
```

**Comment by peombwa** [comment] 2022-03-09 23:47
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/834.

**Closed by peombwa** 2022-03-09 23:47 UTC
Labels: OpenApiService-Dependency
