### ISSUE TITLE
Get-MgTeamChannelMessage limits to 50

### ISSUE THREAD

**Issue by Clifra-Jones** [microsoftgraph/msgraph-sdk-powershell#874] opened 2021-09-24 13:42 UTC
I need to generate an array of all messages in a channel but this command is apparently limited to 50 messages.
`Get-MgTeamChannelMessage -TeamId $team.id -ChannelId $channel.id -PageSize 50`
returns 50 message but
`Get-MgTeamChannelMessage -TeamId $team.id -ChannelId $channel.id -PageSize 51`
throws the error "Limit of '50' for Top Query has been exceeded." I didn't specify a Top query
if you use the -Top parameter with anything over 50 you get the same error, the -All parameter does the same thing.

I understand API limits but having to get 50 messages, then do another query with a -Skip 50 and add to the array, then do a -Skip 100 (rinse repeat) seems ridiculous! 

I can't find any workaround for this in the relatively sparse documentation for these modules.

**Comment by Clifra-Jones** [comment] 2021-09-24 14:16
OK I did figure out a work around by looking at the C# code.

`Get-MgTeamChannelMessage -TeamId $Team.Id -ChannelId $Channel.Id -PageSize 50 -All`

But that just seems stupid. If the max allowed page size is 50 (The C# code says the max is 999) then the -All parameter should automatically set the -PageSize to 50, we should not have to provide it is we want ALL messages.

**Comment by peombwa** [comment] 2021-09-29 22:28
We should update the paging logic to use the default payload count as the initial pageSize then follow the nextLink until the last item is retrieved.

The current implementation uses a [default pageSize of 100](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/tools/Custom/ListCmdlet.cs#L54), which conflicts with Teams' max allowed pageSize of 50. Note, the max allowed pageSize varies from service to service. Most services generally accept a pageSize of 100, but it appears Teams is an exception.

**Note to self:** Should AGS formalize a default page size/$top for all workloads?

**Comment by peombwa** [comment] 2022-07-01 21:13
Will be fixed by #1361.

Closing as duplicate of #1351.

**Closed by peombwa** 2022-07-01 21:13 UTC
Labels: Bug, Request: enhancement
