### ISSUE TITLE
Get-MgUser not returning or setting usagelocation

### ISSUE THREAD

**Issue by kross-git** [microsoftgraph/msgraph-sdk-powershell#1547] opened 2022-09-30 00:00 UTC
Get-MgUser not returning or setting usage location. I can make it work in azuread, but need it to work in Powershell Core from a MAC or windows machine

**Comment by kross-git** [comment] 2022-09-30 03:12
update: Seems that it is changing the usage-location when I do an update, but I also updated PowerShell this morning

Still can't get it to display using 
**get-mguser -userID "username@domain.com" | select UsageLocation**

**Comment by kross-git** [comment] 2022-09-30 03:58
update: if I use the API explorer I can pull the usage location...I must be doing something wrong somewhere

**Comment by peombwa** [comment] 2022-09-30 16:26
This is by design. For v1.0 endpoint/profile, you'll have to use `-Property` ($select when using the API) to select the property:
``` powershell
Get-MgUser -UserId $user_id -Property UsageLocation -Debug | select UsageLocation
```

See https://github.com/microsoftgraph/msgraph-sdk-powershell#known-issues and [API reference](https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#optional-query-parameters) for more details:
> By default, only a limited set of properties are returned (businessPhones, displayName, givenName, id, jobTitle, mail, mobilePhone, officeLocation, preferredLanguage, surname, and userPrincipalName).To return an alternative property set, specify the desired set of [user](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0) properties using the OData $select query parameter. For example, to return displayName, givenName, and postalCode, add the following to your query $select=displayName,givenName,postalCode.

**Comment by peombwa** [comment] 2022-09-30 16:28
Closing as by design.

**Closed by peombwa** 2022-09-30 16:28 UTC
Labels: question
