### ISSUE TITLE
'NotSpecified (...) FormatException' with some users using Get-MgUserEvent or Get-MgUserCalendarView

### ISSUE THREAD

**Issue by mlduber** [microsoftgraph/msgraph-sdk-powershell#511] opened 2021-01-22 09:45 UTC
I have something like 150 users. When I attempt to export events using `Get-MgUserCalendarView`, 3 users throw a `FormatException`. Trying to pinpoint what's wrong, I type one `Get-MgUserEvent` for each one of these (with just one argument `-UserId`). It works for two users but it throws another `FormatException` for one of them. It doesn't make sense.

```
Get-MgUserEvent : Le format de la chaîne d'entrée est incorrect.
Au caractère Ligne:1 : 1
+ Get-MgUserEvent -UserId <proper Id or userPrincipalName>
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgUserEvent_List], FormatException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgUserEvent_List
```

The userId is correct. It goes exactly the same when using `UserPrincipalName` instead of `Id`. I cannot find anything fancy or specific in the users' profiles.

If I copy-paste the userId into Microsoft Graph Explorer, it works.
If I use `Invoke-RestMethod`, it works.

The exception is not the same as the one you get for an incorrect id:

```
Get-MgUserEvent -UserId 'incorrect'

Get-MgUserEvent : The requested user 'incorrect' is invalid.
Au caractère Ligne:1 : 1
+ Get-MgUserEvent -UserId 'incorrect'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : ({ UserId = inco...ndProperty =  }:<>f__AnonymousType19`9) [Get-MgUserEvent_List], RestException`1
    + FullyQualifiedErrorId : ErrorInvalidUser,Microsoft.Graph.PowerShell.Cmdlets.GetMgUserEvent_List
```
 
[AB#7713](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7713)

**Comment by mlduber** [comment] 2021-01-22 13:31
Now I re-run my script and get the error with other users (+ the 3 ones).

BUT: if I run
```
Get-MgUserCalendarView -CalendarId $calendar.Id -UserId $user.Id -EndDateTime $endISO -StartDateTime $startISO
```
it works.

Now, if I add `-All` or `-Top 100`, I get the error. But I do not get an error with `-Top 10`.

**Comment by peombwa** [comment] 2021-01-23 00:12
@mlduber Could you share entire script? I'm not able to repro the exception on my end even when running `Get-MgUserCalendarView -CalendarId $calendar.Id -UserId $user.Id -EndDateTime $endISO -StartDateTime $startISO -All`.

Also, can you try the following:
- Can you isolate this error to a single user id?
- Try using fiddler to inspect the request/response to see if this is a service error.
- Does this error happen all the time or is it transient?

**Comment by mlduber** [comment] 2021-01-24 12:24
Full "code":

```
PS C:\tmp> Connect-MgGraph -Scopes 'User.Read.All', 'Calendars.ReadWrite.Shared'
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DL56GABP9 to authenticate.
Welcome To Microsoft Graph!
PS C:\tmp> $startdatetime = '2021-01-01'
PS C:\tmp> $endDateTime = '2021-02-01'
PS C:\tmp> (Get-MgUserCalendarView -UserId 'user1@mydomain.tld' -StartDateTime $startdatetime -EndDateTime $endDateTime -All).Count
110
PS C:\tmp> (Get-MgUserCalendarView -UserId 'user2@mydomain.tld' -StartDateTime $startdatetime -EndDateTime $endDateTime -All).Count
Get-MgUserCalendarView : Le format de la chaîne d'entrée est incorrect.
Au caractère Ligne:1 : 1
+ (Get-MgUserCalendarView -UserId 'user2@mydomain.tld' -StartDateTim ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgUserCalendarView_List], FormatException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgUserCalendarView_List

0
PS C:\tmp>
```

- This error happened each time with a few specific users. One day later, with the same users + some other users.
- Using fiddler, I notice I do get a proper JSON answer, with `@odata.context`, `@data.nextlink` and populated `value` with calendar events. However, there is no second GET request to fetch the "next" link.
- If I run the `Get-MgUserCalendarView` 20 times for each user, I will get the error 20 times with user2, 0 times with user1.

**Comment by peombwa** [comment] 2021-05-28 01:23
I have traced the cause of this issue to our code generator and is being tracked here https://github.com/Azure/autorest.powershell/issues/772.

Closing this a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/290.

**Closed** 2021-05-28 01:23 UTC
Labels: Perf, Status: Under Investigation, question
