### ISSUE TITLE
PowerShell 7 stop responsing if browser closed after using Connect-MgGraph 

### ISSUE THREAD

**Issue by farismalaeb** [microsoftgraph/msgraph-sdk-powershell#1301] opened 2022-06-02 14:51 UTC
When trying to connect to MSGraph using 
```Connect-MgGraph -Scopes  "User.ReadWrite.All",  "Group.ReadWrite.All",  "GroupMember.ReadWrite.All", "Application.ReadWrite.All"```

The browser starts to authenticate, if the page is closed, PowerShell 7 stuck and remains to wait for a response forever unless I exit Pwsh and start it again.
CTRL+C won't work.
There should be a timeout like 60 seconds when it should be a timeout.
In PowerShell 5.1 its OK and Windows PowerShell return Connect-MgGraph : User canceled authentication.

**Comment by danielniccoli** [comment] 2022-06-02 15:38
Duplicate of #1259

**Comment by ddyett** [comment] 2022-06-16 16:01
indeed.  closing as duplicate.

**Closed by ddyett** 2022-06-16 16:01 UTC
Labels: ToTriage
