### ISSUE TITLE
update-mgapplication -logoinputfile gives error

### ISSUE THREAD

**Issue by raymonvt3fifty** [microsoftgraph/msgraph-sdk-powershell#935] opened 2021-11-08 11:06 UTC
update-MgApplication -ApplicationId [id] -LogoInputFile .\logo.png gives the following error Update-MgApplication_UpdateExpanded1: Unexpected contents in request body.

**Comment by peombwa** [comment] 2022-03-19 00:07
Setting an application logo is currently not supported by the native commands due https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1097.

As a workaround, you can use `Invoke-MgGraphRequest` to upload an application as shown below:
``` powershell
Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/beta/applications/$Id/logo" -Method PUT -InputFilePath "PATH_TO_LOGO.png" -ContentType "image/png"
```

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1097.

**Closed by peombwa** 2022-03-19 00:07 UTC
Labels: Question: SDK
