### ISSUE TITLE
Update-MgUser fails to remove OfficeLocation value

### ISSUE THREAD

**Issue by VonGlitch** [microsoftgraph/msgraph-sdk-powershell#2087] opened 2023-06-14 14:06 UTC
I am using Update-MgUser to update OfficeLocation values and sometimes when a person is between locations, or not yet assigned a location, we want the location field to be empty.   But if I pass either an empty string or $nul the cmdlet fails.   How do I remove the OfficeLocation value.   We don't want to populate it with garbage!

```
PS C:\admin\365\SharePoint> Update-MgUser -UserId $User.Id -OfficeLocation ""
Update-MgUser : Invalid value specified for property 'officeLocation' of resource 'User'.
At line:1 char:1
+ Update-MgUser -UserId $User.Id -OfficeLocation ""
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = 7ce2...oftGraphUser1 }:<>f__AnonymousType63`2) [Update-MgUser_UpdateExpanded], RestException`1
    + FullyQualifiedErrorId : Request_BadRequest,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUser_UpdateExpanded
```

**Comment by peombwa** [comment] 2023-06-19 22:58
Thanks for following up on this.

The SDK does not currently support setting properties to null due to a design limitation with the code generator - https://github.com/Azure/autorest.powershell/issues/961.

As a workaround, please use the `Invoke-GraphRequest` to set properties to null as shown below:
``` powershell
Invoke-MgGraphRequest -Uri "v1.0/users/$userId" -Method PATCH -Body @{ OfficeLocation = $null }
```

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/833.

**Closed by peombwa** 2023-06-19 22:58 UTC
Labels: ToTriage
