### ISSUE TITLE
New-MgBookingBusiness : "~At least one error occured"

### ISSUE THREAD

**Issue by iuaj7** [microsoftgraph/msgraph-sdk-powershell#2224] opened 2023-08-07 09:29 UTC
**Description:**
Running the New-MgBookingBusiness command does not work as expected

The output is: (~"At least one error occured")
New-MgBookingBusiness : Mindestens ein Fehler ist aufgetreten.
In Zeile:17 Zeichen:1
+ New-MgBookingBusiness -BodyParameter $params
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-MgBookingBusiness_Create], AggregateException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.NewMgBookingBusiness_Create

**To Reproduce / Steps to reproduce the behavior:**

Import-Module Microsoft.Graph.Bookings
Connect-MgGraph -ContextScope Process -Scopes "Bookings.Manage.All", "Bookings.Read.All", "Bookings.ReadWrite.All", "BookingsAppointment.ReadWrite.All"
Welcome To Microsoft Graph!
PS C:\PS> 
PS C:\PS> $params = @{
        displayName = "Fourth Coffee"
        address = @{
                postOfficeBox = "P.O. Box 123"
                street = "4567 Main Street"
                city = "Buffalo"
                state = "NY"
                countryOrRegion = "USA"
                postalCode = "98052"
        }
        phone = "206-555-0100"
        email = "manager@fourthcoffee.com"
        webSiteUrl = "https://www.fourthcoffee.com"
        defaultCurrencyIso = "USD"
}
New-MgBookingBusiness -BodyParameter $params

**Expected behavior:**
Created new Bookings page

**Debug Output**
None, also nothing from Fiddler

Module Version:
Get-Module Microsoft.Graph*
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.1.0      Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext...}
Script     2.1.0      Microsoft.Graph.Bookings            {Get-MgBookingBusiness, Get-MgBookingBusinessAppointment, Get-MgBookingBusinessAppointmentCount, Get-MgBookingBusinessCalendarView...}

**Environment Data:**
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Additional context**
Get-MgBookingBusiness works nicely
Graph Explorer works also

**Workaround:**
Invoke-MgGraphRequest -Method POST -Uri $url -Body $body

**Comment by peombwa** [comment] 2023-08-09 22:38
Thanks for following up on this.

This is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2191#issuecomment-1662690070. The fix is scheduled to go out somewhere this week as part of v2.3.0.

As a workaround, please use the standalone PowerShell 5.1 (not VS Code extension) or PowerShell 7 to run the command.

**Closed by peombwa** 2023-08-09 22:38 UTC
Labels: ToTriage
