### ISSUE TITLE
The cmdlet Update-MgPolicyAdminConsentRequestPolicy returns the error 'No HTTP resource was found that matches the request URI'

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#1661] opened 2022-12-01 19:16 UTC
This is on both V1.0 and beta profile.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/73849846/205139967-8533fbfd-bc76-4270-88f4-64d85ddd08b3.png">

**Comment by peombwa** [comment] 2022-12-01 21:35
Duplicate of https://github.com/microsoftgraph/msgraph-metadata/issues/218.

We will need to open ICM to surface this to the workload owner. The CSDL currently says the API supports PATCH instead of PUT for updates.

**Comment by peombwa** [comment] 2022-12-01 21:35
Closing as duplicate of https://github.com/microsoftgraph/msgraph-metadata/issues/218

**Closed by peombwa** 2022-12-01 21:35 UTC
Labels: ToTriage

**Comment by peombwa** [comment] 2022-12-01 22:35
I've opened ICM # 352593620 for the workload to fix the missing annotation.

**Comment by YenNantes** [comment] 2023-05-23 13:45
Hi,
Any update?
It's been a while that this issue was raised and so far it does not seem to be fixed.
