### ISSUE TITLE
Fresh install, error connect without parameters

### ISSUE THREAD

**Issue by HiltonGiesenow** [microsoftgraph/msgraph-sdk-powershell#82] opened 2020-01-19 08:22 UTC
Hi team,

I just installed this module, and I'm trying to run `Connect-Graph` but it does nothing for a long time and eventually errors out. If I look at Fiddler, it's giving a 400-error (Bad Request). Here's a sample payload:

Url: https://login.microsoftonline.com/common/oauth2/v2.0/token
Body: 
client_id=[guid] &client_info=1&scope=offline_access+openid+profile+User.Read&grant_type=device_code&device_code=[long code]

I've also tried specifying a tenant id - same payload but different url - same result.

**Comment by darrelmiller** [comment] 2020-01-21 05:22
Could you try using the new modules on PowerShell Gallery and see if you have the same problem?  https://developer.microsoft.com/en-us/graph/blogs/microsoft-graph-powershell-preview-now-on-powershell-gallery/

Thanks.

**Comment by HiltonGiesenow** [comment] 2020-01-21 10:13
Nope, same issue. I've tested directly, and with a tenant id, and it's giving a 400 bad request in both cases (different error though). This is with:

1) remove this GH beta version
2) install the PowerShell gallery version
3) Try connect with Connect-Graph (using PowerShell ISE, both elevated (Admin) and non-elevated
I've also tried with a different tenant id, same result (400) but different error payload.

**Error payload 1 (Connect-Graph):**
{"error":"authorization_pending","error_description":"AADSTS70016: The provided request has not yet been authorized by the user. The user must input their code.\r\nTrace ID: 753a3bd9-89ee-4961-a005-16505bb86b00\r\nCorrelation ID: c6d398d2-4509-45eb-9896-779ed083783e\r\nTimestamp: 2020-01-21 10:09:23Z","error_codes":[70016],"timestamp":"2020-01-21 10:09:23Z","trace_id":"753a3bd9-89ee-4961-a005-16505bb86b00","correlation_id":"c6d398d2-4509-45eb-9896-779ed083783e","error_uri":"https://login.microsoftonline.com/error?code=70016"}

**Error payload 1 (Connect-Graph -TenantId "[tenant id]"):**
{"error":"authorization_pending","error_description":"AADSTS70016: OAuth 2.0 device flow error. Authorization is pending. Continue polling.\r\nTrace ID: 47312991-4c64-4e9b-8b22-d633b28d7400\r\nCorrelation ID: 2c56efe3-d397-439d-aaf4-48c00dc3a0c7\r\nTimestamp: 2020-01-21 10:07:16Z","error_codes":[70016],"timestamp":"2020-01-21 10:07:16Z","trace_id":"47312991-4c64-4e9b-8b22-d633b28d7400","correlation_id":"2c56efe3-d397-439d-aaf4-48c00dc3a0c7","error_uri":"https://login.microsoftonline.com/error?code=70016"}

Hope that helps?

**Comment by darrelmiller** [comment] 2020-01-21 13:01
@HiltonGiesenow Are you getting an error from the https://microsoft.com/devicelogin screen when you paste in the device code?

**Comment by HiltonGiesenow** [comment] 2020-01-21 13:47
So:

for the default tenant (connect-graph), I do use MFA. But, if I just go to that address and enter the code from my device, it says "That code didn't work. Check the code and try again".

However, the other (test) tenant I use has no MFA (Connect-Graph -TenantId "[tenant id]" example)

**Comment by darrelmiller** [comment] 2020-01-21 13:50
That's weird.  FYI, you only provide a tenantId/ClientId to Connect-Graph if you want to do app-only login with a certificate.  Otherwise the tenant is based on whatever user you choose to login as.
I'm surprised the MFA doesn't work.  I will investigate that further.
Can you try logging into an account in the test tenant but without specifying the tenantId in Connect-Graph?  /cc @peombwa

**Comment by HiltonGiesenow** [comment] 2020-01-21 14:06
ah ok - I thought maybe it's how I force it to switch to another tenant (was expecting a browser popup). Thanks for clarifying.

"Can you try logging into an account in the test tenant but without specifying the tenantId in Connect-Graph?" - how would I do that exactly?

**Comment by darrelmiller** [comment] 2020-01-21 14:13
During the device code flow login, you would use an email (technically a UPN) from the test tenant.  That will automatically select the tenant for you.

**Comment by HiltonGiesenow** [comment] 2020-01-21 14:20
what I mean is how do I trigger that? Just running a vanilla "connect-graph" command?

**Comment by darrelmiller** [comment] 2020-01-21 14:21
Ahh, sorry.  Yes, just a connect-graph.  However, by default it uses the token cache.  In order to get it to ask you to sign in again, you need to do disconnect-graph before calling connect-graph.

**Comment by HiltonGiesenow** [comment] 2020-01-21 14:27
Ahhh ok, that makes sense.

"Disconnect-Graph" gives "No application to sign out from."

**Comment by peombwa** [comment] 2020-01-22 23:35
@darrelmiller @HiltonGiesenow I believe I've figured out what's happening here. PowerShell ISE [doesn't support Console class](https://devblogs.microsoft.com/powershell/differences-between-the-ise-and-powershell-console/) which is what we use to write the device code to the host.

The current sequence of events are follows:
- When the device code callback is invoked, **Console.Out.WriteLineAsync** is called to output the device code.
- Since PowerShell ISE does not support Console class, it skips the WriteLineAsync without throwing any error :(, hence no device code is shown on the host.
- In the meantime, MSAL keeps polling in the background as it waits for the authentication result from the user and it eventually times out. This polling is what causes the 400 errors seen in Fiddler.

We will need to instead pass a `WriteHost` to the `DeviceCodeProvider` callback which may be a challenge with cmdlets due to threading. I'll investigate this option further, but a work around for now would be to use VS Code + PowerShell Extension as outlined [here](https://docs.microsoft.com/en-us/powershell/scripting/components/ise/introducing-the-windows-powershell-ise?view=powershell-7#support).

**Comment by peombwa** [comment] 2020-01-22 23:44
@HiltonGiesenow, can you try using the normal PowerShell host and not ISE.

**Comment by HiltonGiesenow** [comment] 2020-01-23 05:45
Ahhhh, now I understand what @darrelmiller meant about the "Device code"! Yes - that works - I tried both powershell console and VS Code. I'm fine to use one of those instead, but it's worth noting that someone - I know I'm not the only dinosaur still using ISE :-). Thanks for the help though

**Comment by HiltonGiesenow** [comment] 2020-01-23 12:27
Ok, I got it working, but just fyi on this - I initially got:

> Connect-Graph : Access to the path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\0.1.5\bin\userTokenCache.bin3' is denied.

So I needed to run the PS console as Admin to get it to work. Surely this token cache should be in a user folder rather than program files, by default?

**Comment by HiltonGiesenow** [comment] 2020-01-23 12:28
I've gotten it signed in, but now getting a different error trying to issue a command (Get-mguser). Will log as a separate issue so that it's tracked separately, in case it's helpful to others

**Comment by darrelmiller** [comment] 2020-02-14 23:13
Duplicate of #62 Will track this issue there.

**Closed by darrelmiller** 2020-02-14 23:13 UTC
Labels: bug
