### ISSUE TITLE
Get-MgDeviceManagementDeviceConfigurationOmaSettingPlainTextValue doesn't return anything

### ISSUE THREAD

**Issue by hstrang** [microsoftgraph/msgraph-sdk-powershell#1050] opened 2022-01-31 20:14 UTC
Get-MgDeviceManagementDeviceConfigurationOmaSettingPlainTextValue does not return anything using ID values that give the expected result using Graph Explorer. Calling with invalid IDs return error messages so the function is at least making the API calls and is not completely a no-op.

**Comment by peombwa** [comment] 2022-03-04 22:09
Thanks for bringing this to our attention. The issue is due to how the response object is described in the OpenAPI file that the SDK is generated from. We are already tracking the bug in #834, and a fix will be provided by https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/726.

A workaround is to use `Invoke-MgGraphRequest`, as shown below, to make the same request:
``` powershell
Invoke-MgGraphRequest -Uri "v1.0/deviceManagement/deviceConfigurations/$deviceConfigurationId/getOmaSettingPlainTextValue(secretReferenceValueId='$ValueId')"
```

**Comment by peombwa** [comment] 2022-03-04 22:09
Closing as duplicate og #834.

**Closed by peombwa** 2022-03-04 22:09 UTC
Labels: OpenApiService-Dependency, Bug
