### ISSUE TITLE
Get-MgGroupById: Fails with json cast exception if multiple IDs are specified

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#1053] opened 2022-02-01 18:44 UTC
### Example
```ps
Get-MgGroupById -Ids 'e58c0748-29c1-441f-99f6-87823a05818b','28901a8d-c074-4e99-9edd-2e1b6e94a51a'
```

### Expected
Returns list of group objects

### Actual Error
```
Exception             : 
    Type       : System.InvalidCastException
    TargetSite :
        Name          : ChkCast_Helper
        DeclaringType : System.Runtime.CompilerServices.CastHelpers, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Unable to cast object of type 'Microsoft.Graph.PowerShell.Runtime.Json.JsonObject' to type 'Microsoft.Graph.PowerShell.Runtime.Json.JsonArray'.
    Source     : System.Private.CoreLib
    HResult    : -2147467262
    StackTrace :
   at Microsoft.Graph.PowerShell.Runtime.Json.JsonArray.Parse(String text)
   at Microsoft.Graph.PowerShell.Groups.<>c.<GroupsGetByIds_Call>b__772_0(Task`1 body)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgGroupById_GetExpanded.onOk(HttpResponseMessage responseMessage, Task`1 response)
   at Microsoft.Graph.PowerShell.Groups.GroupsGetByIds_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Groups.GroupsGetByIds_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Groups.GroupsGetByIds(IPaths1E1O4BoGroupsMicrosoftGraphGetbyidsPostRequestbodyContentApplicationJsonSchema body, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgGroupById_GetExpanded.ProcessRecordAsync()
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgGroupById_GetExpanded.ProcessRecordAsync()
CategoryInfo          : NotSpecified: (:) [Get-MgGroupById_GetExpanded], InvalidCastException
FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgGroupById_GetExpanded
InvocationInfo        :
    MyCommand        : Get-MgGroupById_GetExpanded
    ScriptLineNumber : 1895
    OffsetInLine     : 23
    HistoryId        : 37
    ScriptName       : C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Microsoft.Graph.Groups\1.9.0\exports\v1.0-beta\ProxyCmdletDefinitions.ps1
    Line             :         $scriptCmd = {& $wrappedCmd @PSBoundParameters}

    PositionMessage  : At C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Microsoft.Graph.Groups\1.9.0\exports\v1.0-beta\ProxyCmdletDefinitions.ps1:1895 char:23
                       +         $scriptCmd = {& $wrappedCmd @PSBoundParameters}
                       +                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Microsoft.Graph.Groups\1.9.0\exports\v1.0-beta
    PSCommandPath    : C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Microsoft.Graph.Groups\1.9.0\exports\v1.0-beta\ProxyCmdletDefinitions.ps1
    InvocationName   : &
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\Users\JGrote\Projects\SeasonsHospiceDDL\ACDL\Tests\E2E\TagGroups.Tests.ps1: line 28
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 1988
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 1949
                        at Invoke-ScriptBlock, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 2110
                        at Invoke-TestItem, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 1184
                        at Invoke-Block, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 826
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 881
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 1988
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 1949
                        at Invoke-ScriptBlock, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 2113
                        at Invoke-Block, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 928
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 881
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 1988
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 1949
                        at Invoke-ScriptBlock, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 2113
                        at Invoke-Block, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 928
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 1662
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.ps1: line 3
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 3154
                        at Invoke-InNewScriptScope, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 3161
                        at Run-Test, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 1665
                        at Invoke-Test, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 2465
                        at Invoke-Pester<End>, C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1: line 5225
                        at Invoke-Main, C:\Users\JGrote\.vscode-insiders\extensions\pspester.pester-test-2021.10.2\Scripts\PesterInterface.ps1: line 474 
                        at <ScriptBlock>, C:\Users\JGrote\.vscode-insiders\extensions\pspester.pester-test-2021.10.2\Scripts\PesterInterface.ps1: line 481
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :

```

**Comment by peombwa** [comment] 2022-03-04 20:13
Thanks for bringing this to our attention. The error is due to an issue with how the response object is described in the OpenAPI file that the SDK is generated from. We are already tracking the issue in #665, and a fix will be provided by microsoftgraph/microsoft-graph-devx-api#307.

A workaround is to use `Invoke-MgGraphRequest` as follows:
``` powershell
$Body = @{
    Ids = @($Id_1, $Id_2)
}
Invoke-MgGraphRequest -Uri "v1.0/groups/getByIds" -Method POST -Body $Body
```

**Comment by peombwa** [comment] 2022-03-04 20:14
Closing as duplicate of #665.

**Closed by peombwa** 2022-03-04 20:14 UTC
Labels: OpenApiService-Dependency
