### ISSUE TITLE
For the New-MgUserAppRoleAssignment the first parameter variant does not work as defined.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#706] opened 2021-06-18 06:09 UTC
The parameter option requires UserId as the only mandatory parameter. Running it returns the error below:

```
New-MgUserAppRoleAssignment : Not a valid reference update.
At line:1 char:1
+ New-MgUserAppRoleAssignment -Userid '68550c41-18a3-495e-aa1d-cf628c17 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = 6855...oleAssignment }:<>f__AnonymousType96`2) [New-MgUserAppRo...CreateExpanded1], RestException`1
    + FullyQualifiedErrorId : Request_BadRequest,Microsoft.Graph.PowerShell.Cmdlets.NewMgUserAppRoleAssignment_CreateExpanded1
``` 
[AB#9952](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9952)

**Comment by peombwa** [comment] 2021-06-22 15:17
Unfortunately, the [$metadata](https://graph.microsoft.com/v1.0/$metadata) that the SDK is generated from lacks the [necessary capability annotation](https://github.com/oasis-tcs/odata-vocabularies/blob/f964d4ed6a5c43af79c8f6e0839645f54c7a1a2c/vocabularies/Org.OData.Capabilities.V1.md#insertrestrictionstype) that should tell us whether or not a property is required for an insert operation. This is something that has to be fixed by the workload owners or AGS.

**Comment by peombwa** [comment] 2021-06-22 15:58
New-MgGroup and New-MgGroupMember are also affected by this.

**Comment by adamedx** [comment] 2021-08-19 16:20
My short-term suggestion to partially mitigate: we can add heuristics to exclude parameter sets that are obviously non-functional. For example, there's no scenario where a `Set-` command for MS Graph with an `Id` parameter should have no other mandatory parameters. At the very least we could generate doc code that says that at least one additional parameter is required so that customers have confidence in the documentation.

**Comment by adamedx** [comment] 2021-08-19 16:21
@msewaweru , another option is to just globally add documentation that explains that one parameter must be specified. Ideally the actual code provides a specific error code for this case.

**Comment by peombwa** [comment] 2023-05-25 22:23
I've transferred the issue to the metadata repo at https://github.com/microsoftgraph/msgraph-metadata/issues/278 where this is actionable. Required properties on insert and update should be explicitly annotated in the CSDL for SDKs to generate the right thing.

Closing as duplicate of https://github.com/microsoftgraph/msgraph-metadata/issues/278.

**Closed by peombwa** 2023-05-25 22:23 UTC
Labels: Dependency: metadata-issue, missing-annotation
