### ISSUE TITLE
Not able to use the counterpart of New-AzureADApplication (New-MgApplication) cmdlet with the same permissions

### ISSUE THREAD

**Issue by LenaVinogradov** [microsoftgraph/msgraph-sdk-powershell#1599] opened 2022-10-28 21:42 UTC
Part of my responsibilities of my team is to create and maintain AAD multi tenant applications registered in our production tenant.
I am NOT Global Admin in this tenant.
Out current implementation is using New-AzureADApplication cmdlet. My user does not have either Application.ReadWrite.All or Directory.ReadWrite.All in the production Tenant. And it's unreasonable to assume that Global Admin should grant me either of these permissions.
I was previously able to create new AAD applications in our tenant using New-AzureADApplication.
As part of the work of migrating from Azure AD PS to Microsoft Graph PF announced [here](https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/azure-ad-change-management-simplified/ba-p/2967456)
I am switching our scripts to use New-MgApplication. With the same permissions that I was able to create AAD Application before I cannot create application using new PS module. 
"New-MgApplication : Insufficient privileges to complete the operation."

**Comment by peombwa** [comment] 2022-11-01 17:47
Same response as https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1598#issuecomment-1298889368.

Closing as duplicate of #1598.

**Closed by peombwa** 2022-11-01 17:47 UTC
Labels: ToTriage
