### ISSUE TITLE
Device Extension Attributes Are Not Nullable

### ISSUE THREAD

**Issue by nkasco** [microsoftgraph/msgraph-sdk-powershell#1823] opened 2023-02-17 00:01 UTC
Unable to null extension attributes, this is valid JSON and is accepted, but does not result in a null value.

null and "" both do not work.

Same result in 1.0 and beta

```
$json = '{ "extensionAttributes": { "extensionAttribute3":"" } }'
Update-MgDevice  -DeviceId $DeviceId  -BodyParameter $json
```

**Comment by peombwa** [comment] 2023-02-21 22:45
We do not support setting properties to null due to a design limitation with the code generator - https://github.com/Azure/autorest.powershell/issues/961.

As a workaround, please use [Invoke-MgGraphRequest](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#using-invoke-mggraphrequest) to set the extension properties to null.

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/833.

**Closed by peombwa** 2023-02-21 22:45 UTC
Labels: ToTriage

**Comment by makotsur** [comment] 2023-02-24 12:19
Hi, we are having the same problem.
We ran the following PowerShell script and null could not be set.

// Sigin-in
Connect-MgGraph -Scope Directory.AccessAsUser.All

// Get current value
Invoke-MgGraphRequest -Method GET -Uri https://graph.microsoft.com/beta/devices/{device-object-id}/extensionAttributes/extensionAttribute1

// output sample 
Name                           Value
@odata.context                 https://graph.microsoft.com/beta/$metadata#devices('c65459dd-5be0-4429-acf7-60c68f84d...
value                          aaa

// Update extensionAttribute1 to null
Invoke-MgGraphRequest -Method PATCH -Uri https://graph.microsoft.com/beta/devices/{device-object-id}/ -Body '{"extensionAttributes":{"extensionAttribute1":null}}'

// Get current value again
Invoke-MgGraphRequest -Method GET -Uri https://graph.microsoft.com/beta/devices/{device-object-id}/extensionAttributes/extensionAttribute1

// output sample -> Not null
Name                           Value
@odata.context                 https://graph.microsoft.com/beta/$metadata#devices('c65459dd-5be0-4429-acf7-60c68f84d...
value                          aaa

**Comment by AmirTerani** [comment] 2023-02-27 19:32
> We do not support setting properties to null due to a design limitation with the code generator - [Azure/autorest.powershell#961](https://github.com/Azure/autorest.powershell/issues/961).
> 
> As a workaround, please use [Invoke-MgGraphRequest](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#using-invoke-mggraphrequest) to set the extension properties to null.
> 
> Closing as duplicate of #833.

This shouldn't be closed. We still have the same issue and as others have mentioned, the workaround doesn't work either. We need a fix ASAP. Please re-open.

**Comment by AmirTerani** [comment] 2023-02-28 01:40
> > > We do not support setting properties to null due to a design limitation with the code generator - [Azure/autorest.powershell#961](https://github.com/Azure/autorest.powershell/issues/961).
> > > As a workaround, please use [Invoke-MgGraphRequest](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#using-invoke-mggraphrequest) to set the extension properties to null.
> > > Closing as duplicate of #833.
> > 
> > 
> > This shouldn't be closed. We still have the same issue and as others have mentioned, the workaround doesn't work either. We still need a fix or a working workaround. Please re-open.
> 
> The workaround is acceptable, but the workaround isn't working because the core API is the root of the issue. I've tried to open a case but the only option for cases with the API itself appears to be the QnA section. If you can open an actual support case it might get higher priority.
> 
> Since the same issue exists with the Graph Explorer, it is not a PowerShell module issue to solve. (Though definitely a desired feature)

Looks like it's been fixed! It worked both in Graph Explorer and the Update-MgDevice commandlet!

**Comment by nkasco** [comment] 2023-02-28 01:47
> Looks like it's been fixed! It worked both in Graph Explorer and the Update-MgDevice commandlet!

Appears like you can now pass "" but not null. I'll take it, but still just very odd. Thanks for updating I wouldn't have checked otherwise!

Hopefully we see this in a changelog soon to understand what the impact was.
