### ISSUE TITLE
HTTP/2 validation

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-sdk-powershell#1015] opened 2022-01-19 14:41 UTC
AGS is rolling out HTTP/2 support. It is already available in Canary.

The goal here is to test our current client against Canary to validate that it's using http2 when available and there's no issues related to http.2 (response header casing etc.)

Details to connect to Canary are available on the dedicated Teams discussion.

**Comment by peombwa** [comment] 2022-01-24 17:52
HTTP/2 support will be inherited from MS Graph .NET Core SDK.

**Comment by ddyett** [comment] 2022-05-05 04:35
@peombwa should this be closed for https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1220

**Comment by peombwa** [comment] 2022-05-10 17:40
Closing as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1220.

**Closed by peombwa** 2022-05-10 17:40 UTC
Labels: Request: Awaiting Validation
