### ISSUE TITLE
Get-MgOauth2PermissionGrant Filter on Scope property

### ISSUE THREAD

**Issue by jaoenrong** [microsoftgraph/msgraph-sdk-powershell#1763] opened 2023-01-25 16:57 UTC
I am trying to pull permissions and filter on the Scope property.  Scope is a string of space delimited permission names: profile User.ReadWrite.All

When I run the command I get an error saying filter is invalid.  Is the Scope property outside the Filter paramaters?
Get-MgOauth2PermissionGrant -Filter "Scope eq '$scope'"

Error:
writeErrorStream      : True
PSMessageDetails      : 
Exception             : Microsoft.Graph.PowerShell.Runtime.RestException`1[Microsoft.Graph.PowerShell.Models.IMicrosoftGraph
                        ODataErrorsOdataError]: Filter is invalid. scope
TargetObject          : { Top = , Skip = , Search = , Filter = Scope eq 'profile offline_access openid email', Count = , 
                        Sort = , Property = , ExpandProperty =  }
CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType5`8) 
                        [Get-MgOauth2PermissionGrant_List1], RestException`1
FullyQualifiedErrorId : Request_UnsupportedQuery,Microsoft.Graph.PowerShell.Cmdlets.GetMgOauth2PermissionGrant_List1
ErrorDetails          : Filter is invalid. scope
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-MgOauth2PermissionGrant<Process>, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.
                        Identity.SignIns\1.17.0\exports\v1.0\ProxyCmdletDefinitions.ps1: line 4613
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

$scope:
profile offline_access openid email

Scope property value:
profile offline_access openid email

$appperm.scope -eq $scope:
True

**Comment by peombwa** [comment] 2023-01-30 22:37
Thanks for following up on this.

This is a service issue that can be reproduced in Graph Explorer as well. It is likely that the API does not support filtering on `scope` property. Unfortunately, this is not mentioned in the API reference doc - https://learn.microsoft.com/en-us/graph/api/resources/oauth2permissiongrant?view=graph-rest-1.0#properties. Please open a question at https://developer.microsoft.com/en-us/graph/support to get assistance from subject matter experts/ API owner.

This repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API.

**Comment by peombwa** [comment] 2023-01-30 22:38
Closing as API question, please open the question at https://developer.microsoft.com/en-us/graph/support.

**Closed by peombwa** 2023-01-30 22:38 UTC
Labels: Question: API, ToTriage
