### ISSUE TITLE
'Update-MgGroup' doesn't affect owner/members of a group.

### ISSUE THREAD

**Issue by meta-anurag-chaturvedi** [microsoftgraph/msgraph-sdk-powershell#103] opened 2020-02-07 08:15 UTC
Hi,
Earlier, in the beta version, we had **'New-Groupmember'** which worked as adding new member to any group. But, now we don't have **'New-MgGroupmember'** so I tried assigning a member using **'Update-MgGroup'** with a parameter _'-Members'_ and tried passing a list of members(users) as _directory objects_.  When I did so, I noticed that although it didn't give any error, it failed to update that group. The same thing happened when I tried updating owner with param _-Owners_.
Refer to below screenshot(_updating group Owners_) for more info and let me know if there's a mistake in my approach.
![GroupOwner_Issue](https://user-images.githubusercontent.com/46713159/74012351-10042400-49b0-11ea-8c83-f6160cf7122f.jpg)

cc: @KirkMunro 
[AB#7430](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7430)

**Comment by KirkMunro** [comment] 2020-06-09 13:35
Just following up on this, how can someone modify group membership using this module bundle? When we run the commands, no errors are returned, but membership is not updated. Is there an ETA for this functionality? Or a documented way that it does work?

**Comment by ryanspletzer** [comment] 2020-09-22 13:02
I see `New-MgGroupMember` and `New-MgGroupMemberByRef` available now (need to test them).

However, I don't see `Remove-MgGroupMember` / `Remove-MgGroupMemberByRef` nor the same for Owners.

There is a `New-MgGroupOwnerByRef` but no `New-MgGroupOwner`.

I could open issues for tracking the ones that are missing if it helps.

**Comment by phazlett** [comment] 2021-04-15 23:17
Are there any updates on when we'll have a way to remove group owners?

**Comment by peombwa** [comment] 2022-05-12 18:00
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/452.

**Closed by peombwa** 2022-05-12 18:00 UTC
Labels: OpenApiService-Dependency

**Comment by djpirocchi** [comment] 2022-06-06 16:23
I wanted to bump this as I too am starting to use MgGraph for everything.  Only to find that a simple maintenance script I wanted to write but, cannot due to the missing Remove-MgGroupMember.  Rather than explore the work-a-round, I will resort to older AzureAD commands.
