### ISSUE TITLE
Filter on clientId comes with a 404 at the `/v1.0/oauth2PermissionGrants` endpoint

### ISSUE THREAD

**Issue by spiral-dev** [microsoftgraph/msgraph-sdk-powershell#1557] opened 2022-10-06 07:37 UTC
When calling the `/v1.0/oauth2PermissionGrants` endpoint with a filter on clientId that does NOT exist. It returns a 404 with the following body:

Request:

GET https://graph.microsoft.com/v1.0/oauth2PermissionGrants?$filter=clientId%20eq%20%aaaaaaaa-3d02-4fe8-85ea-bbbbbbbb%27 HTTP/1.1
Host: graph.microsoft.com
SdkVersion: graph-powershell/1.12.3, Graph-dotnet-1.25.1
FeatureFlag: 00000047
Cache-Control: no-store, no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.17763;) PowerShell/7.2.6 Get-MgOauth2PermissionGrant_List1
Authorization: Bearer xxxxxxxxx
Accept-Encoding: gzip

```json
"error": {
  "code": "Request_ResourceNotFound",
  "message": "Resource '' does not exist or one of its queried reference-property objects are not present.",
  "innerError": {
	  "date": "2022-10-06T07:13:31",
	  "request-id": "xxxxxxxx-1350-4bc3-8c45-1888078d943b",
	  "client-request-id": "xxxxxxxx-1350-4bc3-8c45-1888078d943b"
  }
}
```
I expect that it should return an empty array.

```json
{
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#oauth2PermissionGrants",
	"@odata.nextLink": "https://graph.microsoft.com/v1.0/oauth2PermissionGrants?$filter=clientId+eq+<some-more-data>",
	"value": []
}
```

My expected result is returned when using a filter on the field `resourceId` where the specified value does not exists.

GET https://graph.microsoft.com/v1.0/oauth2PermissionGrants?$filter=resourceId%20eq%20%aaaaaaaa-a810-4b89-ae04-bbbbbbbb%27

Returns:
```json
{
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#oauth2PermissionGrants",
	"@odata.nextLink": "https://graph.microsoft.com/v1.0/oauth2PermissionGrants?$filter=resourceId+eq+<some-more-data>",
	"value": []
}
```

**Comment by peombwa** [comment] 2022-10-07 21:56
Thanks for following up on this.

It's the API that returns the response like that as shown in the `-Debug` logs above. The same behavior can also be reproduced through Graph Explorer - https://developer.microsoft.com/en-us/graph/graph-explorer/preview.

As this repository is intended for issues related to the functionality of the module, we may not be the best placed to answer some queries that are tied to the functionality of the API. Please open a question/ticket/feature request at https://developer.microsoft.com/en-us/graph/support to get an answer from the API owners.

**Comment by peombwa** [comment] 2022-10-07 21:58
Closing as not actionable by the SDK. Please open a question at https://developer.microsoft.com/en-us/graph/support to get assistance on the issue.

**Closed by peombwa** 2022-10-07 21:58 UTC
Labels: Question: API
