### ISSUE TITLE
Invoke-MgInstantiateApplicationTemplate creates app and corresponding service principal but doesn't return any output

### ISSUE THREAD

**Issue by premfix** [microsoftgraph/msgraph-sdk-powershell#1061] opened 2022-02-04 10:52 UTC
Hello.
I want to put the result of Invoke-MgInstantiateApplicationTemplate to the variable, so that I can get IDs (and other details) of the created service principal and application further in the script, but there is no any output from that cmdlet.

**Comment by peombwa** [comment] 2022-02-22 19:36
Thanks for bringing this to our attention. The command does not currently return an object due to a status code mismatch as described in #907. A fix will be provided by https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/492.

A workaround is to use `Invoke-MgGraphRequest` to instantiate an application like this:
``` powershell
$App = Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/v1.0/applicationTemplates/{id}/instantiate" -Method POST -Body @{DisplayName = "My custom name"}
```

**Comment by peombwa** [comment] 2022-02-22 19:37
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/907.

**Closed by peombwa** 2022-02-22 19:37 UTC
Labels: duplicate, Bug: Client
