### ISSUE TITLE
The argument name to determine Application should be ObjectId instead of ApplicationId

### ISSUE THREAD

**Issue by watahani** [microsoftgraph/msgraph-sdk-powershell#593] opened 2021-03-23 07:37 UTC
## Current behavior

To get an application, we need to provide objectId but argument name is "ApplicationId"

```powershell
Get-MgApplication -ApplicationId 03dc4a88-bc57-4da0-9d7d-cee2b98fba78

Id                                   DisplayName  AppId                                SignInAudience PublisherDomain
--                                   -----------  -----                                -------------- ---------------
03dc4a88-bc57-4da0-9d7d-cee2b98fba78 testtesttest 50fc07ef-3afd-4df3-8577-a2115c95a0d2 AzureADMyOrg   04.wahaniya.com
```

## Expected

The argument name should be ObjectId.

```powershell
Get-MgApplication -ObjectId 03dc4a88-bc57-4da0-9d7d-cee2b98fba78

Id                                   DisplayName  AppId                                SignInAudience PublisherDomain
--                                   -----------  -----                                -------------- ---------------
03dc4a88-bc57-4da0-9d7d-cee2b98fba78 testtesttest 50fc07ef-3afd-4df3-8577-a2115c95a0d2 AzureADMyOrg   04.wahaniya.com
```

**Comment by peombwa** [comment] 2021-03-26 20:33
This is by design. For my Microsoft Graph PowerShell SDK, all [id](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0#properties) parameters are named based on the entity they represent as described in the [OpenAPI document](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/v1.0/Applications.yml#L212) e.g. `Application` entity will have a parameter of `ApplicationId`. 

We understand that customers upgrading from AzureAD Graph can find it confusing to have an `appId` property and `-ApplicationId` parameter. In this case, we can consider aliasing `-ApplicationId` parameter to something like `-ObjectId` or `-Id` (If feasible).

cc/ @darrelmiller

**Comment by peombwa** [comment] 2022-06-24 22:30
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/906.

**Closed by peombwa** 2022-06-24 22:30 UTC
Labels: Request: enhancement, Request: Feature
