### ISSUE TITLE
Get-MgDevice -DeviceId <String> - DeviceId is not clearly described, very confusing

### ISSUE THREAD

**Issue by dweppeler-msft** [microsoftgraph/msgraph-sdk-powershell#1631] opened 2022-11-15 14:54 UTC
Hi,

the DeviceId of all MgDevice Commands is not clearly described and is very confusing. Because for all devices exist an ObjectId and a DeviceId in AAD:

![2022-11-15 14_32_21-Windows PowerShell ISE](https://user-images.githubusercontent.com/112628800/201949801-73e34d76-c828-4daf-b8b6-d79dd40c6ed0.png)

**However, you do not have to use the AAD device ID for the commands, but the AAD object ID.** 

Example:
`Get-MgDevice
   -DeviceId <String>`
`Remove-MgDevice
      -DeviceId <String>`

Source:
https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/get-mgdevice?view=graph-powershell-1.0

Please describe the definition for the device ID in more detail. 
![2022-11-15 15_52_38-Get-MgDevice (Microsoft Graph Identity DirectoryManagement) _ Microsoft Learn an](https://user-images.githubusercontent.com/112628800/201950357-51c1771f-b029-4043-a29e-e1556bc41d39.png)

Thanks, Daniel

**Comment by peombwa** [comment] 2022-11-15 20:44
The confusion comes from how the property is named in Microsoft Graph schema. [`Device` resource type](https://learn.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0#properties) has both `Id` and `DeviceId` properties that exist on the same entity. `Id` is the key and maps to `-DeviceId` when using `*-MgDevice` commands. We are already tracking this in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/906.

I've opened an issue at https://github.com/microsoft/OpenAPI.NET.OData/issues/309 for the right description to be added to the key parameter. The parameter descriptions are provided by the upstream OData to OpenAPI tool.

**Comment by peombwa** [comment] 2022-11-15 20:45
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/906.

The description update will be provided by https://github.com/microsoft/OpenAPI.NET.OData/issues/309.

**Closed by peombwa** 2022-11-15 20:45 UTC
Labels: ToTriage
