### ISSUE TITLE
Directory Scope is not respected when creating a eligible role assignment using Graph API

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#2041] opened 2023-05-26 11:05 UTC
Moving this from the docs repo.

Original issue: https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/issues/249

**Comment by peombwa** [comment] 2023-05-26 15:26
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1996#issuecomment-1536696632.

This is a service issue as the customer is directly calling the REST API.

**Closed by peombwa** 2023-05-26 15:26 UTC
Labels: ToTriage
