### ISSUE TITLE
Get-MgReportOffice365Activation* results in Expected { or [ errors.

### ISSUE THREAD

**Issue by gkneale** [microsoftgraph/msgraph-sdk-powershell#166] opened 2020-04-08 23:32 UTC
Running the Get-MgReportOffice365ActivationCount or Get-MgReportOffice365ActivationUserDetail commands result in the following errors.

Get-MgReportOffice365ActivationCount : Expected '{' or '['. Was String: Report.
At line:1 char:1
+ Get-MgReportOffice365ActivationCount
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgReportOffice365ActivationCount_Get], ParserException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgReportOffice365ActivationCount_Get

Get-MgReportOffice365ActivationUserDetail : Expected '{' or '['. Was String: Report.
At line:1 char:1
+ $x =  Get-MgReportOffice365ActivationUserDetail
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgReportOff...nUserDetail_Get], ParserException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgReportOffice365ActivationUserDetail_Get

**Comment by MIchaelMainer** [comment] 2020-04-09 20:13
Related #54

**Comment by peombwa** [comment] 2020-05-14 00:43
This is an issue with the code generator that we using to generate the cmdlets - it doesn't handle non JSON responses. We are currently work on a fix for this as part of work item #182.

**Comment by peombwa** [comment] 2020-11-11 23:35
Duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/407. Downloading of reports is being tracked by https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/407.

**Closed by peombwa** 2020-11-11 23:35 UTC
