### ISSUE TITLE
Issue adding an application to Catalog through PowerShell SDK - New-MgEntitlementManagementAccessPackageResourceRequest

### ISSUE THREAD

**Issue by purishd** [microsoftgraph/msgraph-sdk-powershell#1089] opened 2022-02-15 10:07 UTC
Below is my request detail from a Development environment. This request utilises PowerShell SDK and gets submitted successfully but always remains in Delivering state. The audit log shows that it failed but not with much information to troubleshoot. However, same request through Graph explorer is working fine.

$params = @{
catalogId = "813f7a2e-7b43-423f-b7c1-ef48111fd889"
requestType = "AdminAdd"
justification = ""
accessPackageResource = @{
resourceType = "Application"
originId = "c2a43cb8-a3a0-4609-b702-af60338a7bd6"
originSystem = "AadApplication"
displayName = "Linkedin"
description = "AppId: 869359cc-b146-42f1-a9aa-27117fe6a3dd"
url = "https://myapps.microsoft.com/signin/a865e2b7-e613-4b4d-a3a7-92c6d3b518b3?tenantId=e0971d3b-58ad-4dac-b6c6-36451af47032"
}
}
}
Write-Host
New-MgEntitlementManagementAccessPackageResourceRequest -BodyParameter $params

Output looks like below, the IGA audit logs show this as failure and application never gets added to the catalog.
![image](https://user-images.githubusercontent.com/11908199/154039614-0d81bac9-5819-4372-8971-d0651342dcec.png)

**Comment by markwahl-msft** [comment] 2022-02-24 00:38
I noticed your example may have an extra close-brace "}". But otherwise I was able to use this bodyparameter pattern to create a resource request for an application in my tenant, and so this indicates the requested resource was identified from the parameters by the service. Since you mentioned the audit log is indicating failure, it might be due to an issue with authorization in your environment established at Connect-MgGraph, or with the application in question, rather than with the New-MgEntitlementManageementAccessPackageResourceRequest cmdlet itself.  To narrow down the possible cause, you might wish to try connecting as a global administrator and adding a group as a resource.  We recently published an example of using PowerShell to add a group at https://docs.microsoft.com/en-us/azure/active-directory/governance/entitlement-management-catalog-create and more details on permissions requirements in the request body section of https://docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta .

**Comment by purish87** [comment] 2022-03-22 02:42
Hi Mark, Thanks for your response on this and apologies that I haven't been able to update the issue here. However, I have opened this case with support as well and have provided them Fiddler traces as well for the request. Please note this issue is only happening while adding an application to the catalogue. Adding a group to catalog works like a charm.
I can also confirm that permission is not an issue here. The same request of adding an application with Graph explorer works fine. However, I am suspecting there is some issue with PowerShell SDK for this request.

**Comment by peombwa** [comment] 2022-05-12 16:12
Closing as this is a service issue, and no action is needed from the SDK.

**Comment by peombwa** [comment] 2022-05-12 16:13
Please open a new issue if the problem is traced back to the SDK.

**Closed by peombwa** 2022-05-12 16:12 UTC
Labels: Service issue
