### ISSUE TITLE
SDK 1.6.1 does not load correct on Server 2016 PS5.1

### ISSUE THREAD

**Issue by dloder0** [microsoftgraph/msgraph-sdk-powershell#797] opened 2021-08-02 20:34 UTC
On a fresh, fully OS patched 2016 still running PS 5.1, after installing the Authentication module, I get the following error message when attempting to load it. I can confirm from the output that no "netstandard" assembly exists.  Is there another missing prerequisite not in the documentation?

PS C:\Users\Administrator> import-module Microsoft.Graph.Authentication
Import-Module : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral,
PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
At C:\Program
Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.6.0\Microsoft.Graph.Authentication.psm1:3 char:9
+ $null = Import-Module -Name (Join-Path $PSScriptRoot 'Microsoft.Graph ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

WARNING: Unable to find type [Microsoft.Graph.PowerShell.Authentication.Utilities.DependencyAssemblyResolver].
PS C:\Users\Administrator>

Here are the versions for this install

PS C:\Users\Administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.4530
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.4530
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\Users\Administrator> Get-Module | Select Name, Version

Name                            Version
----                            -------
Microsoft.Graph.Authentication  1.6.0
Microsoft.PowerShell.Management 3.1.0.0
Microsoft.PowerShell.Utility    3.1.0.0
PSReadline                      1.2

PS C:\Users\Administrator> [System.AppDomain]::CurrentDomain.GetAssemblies() | select FullName, Location

FullName                                                                                                    Location
--------                                                                                                    --------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                                 C:\Windo...
Microsoft.PowerShell.ConsoleHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35         C:\Windo...
System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                                   C:\Windo...
System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                              C:\Windo...
System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35             C:\Windo...
Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35      C:\Windo...
System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                               C:\Windo...
System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a                        C:\Windo...
System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a                 C:\Windo...
System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                          C:\Windo...
System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                              C:\Windo...
Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Microsoft.PowerShell.Security, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35            C:\Windo...
System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a                     C:\Windo...
System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                      C:\Windo...
Microsoft.Powershell.PSReadline, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35          C:\Progr...
Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a                         C:\Windo...
Microsoft.PowerShell.Commands.Utility, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35    C:\Windo...
System.Configuration.Install, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a             C:\Windo...
Microsoft.PowerShell.Commands.Management, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 C:\Windo...
System.Dynamic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a                           C:\Windo...
Microsoft.Graph.Authentication, Version=1.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35           C:\Progr...
Microsoft.Graph.Auth, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35                     C:\Progr...
System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a                           C:\Windo...
System.Threading.Tasks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a                   C:\Windo...
Microsoft.IdentityModel.JsonWebTokens, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35    C:\Progr...
Microsoft.IdentityModel.Tokens, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35           C:\Progr...
Microsoft.IdentityModel.Logging, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35          C:\Progr...
Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed                         C:\Progr...
System.Dynamic.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a                   C:\Windo...
System.Linq.Expressions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a                  C:\Windo...
System.Reflection, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a                        C:\Windo...
System.ObjectModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a                       C:\Windo...
System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a                       C:\Windo...
System.IdentityModel.Tokens.Jwt, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35          C:\Progr...
 
[AB#10466](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10466)

**Comment by tyteen4a03** [comment] 2022-01-28 21:30
+1  - same issue here on Windows 10.

**Comment by peombwa** [comment] 2022-06-24 22:52
This should have been fixed by now as it is not reproducible using the latest version of the SDK.

Please open a new issue if the issue is still present with the latest version of the SDK (v1.10.0).

**Closed by peombwa** 2022-06-24 22:52 UTC
Labels: under-investigation
