### ISSUE TITLE
Get-MgReportAzureAdLicenseUsage not accepting Report Period.

### ISSUE THREAD

**Issue by DaveyRance** [microsoftgraph/msgraph-sdk-powershell#313] opened 2020-08-06 13:04 UTC
Version 0.7.1 of the module.

Trying to run a AD License Usage report. It will not accept any of the listed values for Period.

7Day period.
PS C:\> Get-MgReportAzureAdLicenseUsage -Period 7D
Get-MgReportAzureAdLicenseUsage : Bad request received for report getAzureADLicenseUsage(): parameter 7D is not a valid period parameter. Valid parameters are '1D', '7D', '30D'
At line:1 char:1
+ Get-MgReportAzureAdLicenseUsage -Period 7D
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Period = 7D }:<>f__AnonymousType3`1) [Get-MgReportAzureAdLicenseUsage_Get], Exception
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgReportAzureAdLicenseUsage_Get

Tried with and without the quotes.
Same for 1D and 30D

**Comment by peombwa** [comment] 2020-11-11 23:40
Duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/407. Downloading of reports is being tracked by https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/407.

**Closed by peombwa** 2020-11-11 23:40 UTC
Labels: Bug: Service
