### ISSUE TITLE
Invoke-MgInstantiateApplicationTemplate throws an error although is successful

### ISSUE THREAD

**Issue by luleonpla** [microsoftgraph/msgraph-sdk-powershell#282] opened 2020-07-08 00:47 UTC
I get an error type message when creating an applicationTemplate using the Invoke-MgInstantiateApplicationTemplate, but the call is successful and it creates the resource. Also, it doesn't return the expected applicationServicePrincipal resource

This is the command that invokes the API call /beta/applicationTemplates/<Id>/instantiate. 

![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/22843225/86860515-d9732800-c079-11ea-85f9-893d19236b95.png)
 
[AB#7419](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7419)

**Comment by MIchaelMainer** [comment] 2020-07-09 20:17
OpenAPI doc response status code does not match actual response. This is a metadata/service issue.

Leave this open to track.

**Comment by peombwa** [comment] 2020-12-18 22:59
This has not been fixed, but it looks like the command is not returning the created service principal.

**Comment by peombwa** [comment] 2022-05-13 00:06
The command is not returning the response due to HTTP status code mismatch in the OpenAPI files. As a workaround, you can use `Invoke-MgGraphRequest` to access the response if needed:
``` powershell
Invoke-MgGraphRequest -Uri "v1.0/applicationTemplates/$Id/instantiate" -Body @{DisplayName = "Azure AD SAML Toolkit"} -Method POST
```
A fix will be provided by https://github.com/microsoft/OpenAPI.NET.OData/issues/153.

Closing a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/907.

**Closed by peombwa** 2022-05-13 00:06 UTC
Labels: AutoREST-dependency, Service issue, Bug
