### ISSUE TITLE
-All switch no longer available for Get-MgDomain

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/msgraph-sdk-powershell#1530] opened 2022-09-22 16:06 UTC
When testing a script with the command `Get-MgDomain -All`, script works fine on module versions prior to 1.12. With 1.12 installed, the switch is not available. Microsoft.Graph.Identity.DirectoryManagement module.

**Comment by Raj-MCITP** [comment] 2022-09-22 19:15
Tried Get-MGuser -All getting error like below

Get-MgUser : A parameter cannot be found that matches parameter name 'all'.
At line:1 char:12
+ get-mguser -all
+            ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-MgUser], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-MgUser

**Comment by peombwa** [comment] 2022-09-22 23:51
We've just released a patch to address the missing parameter. Please update to the latest version (v1.12.1) - `Update-Module Microsoft.Graph`.

Closing as duplicate of #1527.

**Closed by peombwa** 2022-09-22 23:51 UTC
Labels: ToTriage

**Comment by Raj-MCITP** [comment] 2022-10-02 15:07
Using 1.12.1 version.. but still an error.. masked few details. Pls advice

PS C:\WINDOWS\system32> Get-MgUser -Search ***_rajkumar@*.onmicrosoft.com
Get-MgUser : One or more errors occurred.
At line:1 char:1
+ Get-MgUser -Search ***_rajkumar@*.onmicrosoft.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgUser_List], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List
