### ISSUE TITLE
Missing cmdlets for access reviews APIs in beta

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/msgraph-sdk-powershell#1291] opened 2022-05-27 15:54 UTC
Hello,

As first reported through this customer comment https://github.com/microsoftgraph/microsoft-graph-docs/issues/17073#issuecomment-1139655406,  there doesn't seem to be any cmdlets for the base [access reviews schedule definitions](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta) set of APIs. It looks like this gap applies to all access reviews APIs with the following URL paths

```
/identityGovernance/accessReviews/definitions
/identityGovernance/accessReviews/historyDefinitions
```

It also seems those related to [access review stages](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta) aren't mapping to the expected URL pattern. I.e should be `/identityGovernance/accessReviews/definitions/{accessReviewScheduleDefinitionId}/instances/{accessReviewInstanceId}/stages` and not as per the attached screenshot/

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/14026935/170734149-b3766c11-4625-403f-8194-705d527277a0.png">

I think all access reviews cmdlets might need to be investigated. Kindly assist.

cc @msewaweru, @zhusijia26 for visibility.

**Comment by peombwa** [comment] 2022-06-10 22:16
Thanks for bringing this to our attention. The missing/updated commands will ship as part of the upcoming 1.10.0 release.

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1286.

**Closed by peombwa** 2022-06-10 22:16 UTC
Labels: OpenApiService-Dependency

**Comment by FaithOmbongi** [comment] 2022-07-28 08:15
Hi @peombwa - The cmdlets are not yet available in the module nor the [public docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.governance/?view=graph-powershell-1.0) but they are referenced in the Examples for the REST API, like this one [Example 1](https://docs.microsoft.com/en-us/graph/api/accessreviewset-list-definitions?view=graph-rest-beta&tabs=powershell#example-1-list-the-first-one-hundred-access-review-definitions). Could you check on this?

Related customer issue https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1291

cc @msewaweru
