### ISSUE TITLE
Get-MgTeamInstalledApp no longer accepts Team id

### ISSUE THREAD

**Issue by SteveoMS** [microsoftgraph/msgraph-sdk-powershell#1209] opened 2022-04-13 21:47 UTC
Just started to having a script fail that was working.

PS C:\users\modadministrator\pSAPP> Get-MgTeamInstalledApp

cmdlet Get-MgTeamInstalledApp at command pipeline position 1
Supply values for the following parameters:
TeamId: '348802e4-6562-4f21-aa66-5e1ebb5571a3'

Get-MgTeamInstalledApp : **Expected literal (number, boolean, or null). Was '<'.
At line:1 char:1**
+ Get-MgTeamInstalledApp
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgTeamInstalledApp_List1], ParserException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgTeamInstalledApp_List1

**Comment by peombwa** [comment] 2022-04-14 00:38
Sorry about this. The bug is related to #1204. A fix has been deployed in v19.5. Please update to the latest version of the SDK `Update-Module Microsoft.Graph`.

**Comment by peombwa** [comment] 2022-04-14 00:38
Closing as duplicate of #1204.

**Closed by peombwa** 2022-04-14 00:38 UTC
Labels: ToTriage
