### ISSUE TITLE
Error 'Cannot query data for more than 120 users at a time.'

### ISSUE THREAD

**Issue by tkalligo** [microsoftgraph/msgraph-sdk-powershell#1898] opened 2023-03-23 16:37 UTC
This problem started last night on code that i have been running nightly for over 5 months.  As part of the data collection i am getting SignInActivity.  Based  on https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1024, I specified each property I want with the -Property parameter.  Now, if I use that parameter I get the following error:

Get-MgUser : {"@odata.context":"http://reportingservice.activedirectory.windowsazure.com/auditLogs/$metadata#Edm.String
","value":"Cannot query data for more than 120 users at a time."}
At line:1 char:1
$Users2 = Get-MgUser -All -pagesize 999 -Property "signInActivity,OnP ...
CategoryInfo: InvalidOperation: ({ ConsistencyLe...ndProperty =  }:<>f__AnonymousType62`9) [Get-MgUser_List], RestException`1
FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List

If I use "-Property *", the call works, but SignInActivity comes back blank, hence the need to specify each Property "... -Property "UserPrincipalName, UserType, signInActivity..."

I was using v1.14.0 but updated to v1.23.0, that did not make a difference.

How can I get the SignInActivity data for all users if I can no longer specify the property?

**Comment by peombwa** [comment] 2023-03-23 16:55
Thanks for following up on this.

Please open a support ticket/question at https://developer.microsoft.com/en-us/graph/support to get assistance from API owner as this is a service issue. As you've stated above, the API just started failing last night with the error message. You can use the `-Debug` log to find the `date` and `request-id` of the failing request.  See https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug for more details.

This repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.

**Comment by JazBInKC** [comment] 2023-03-24 03:23
Same problem for me as well.  Code I've been running nightly for months.

I'd love to hear the answer to this one

Thanks,

jbw

**Comment by BananZG** [comment] 2023-03-24 09:08
I'm experiencing this with direct Graph API call as well.
It only happens when i pass in filter 'signInActivity'

**Comment by YoupHulsebos** [comment] 2023-03-24 14:12
Also having the same issue. Will create a ticket as @peombwa suggested.

**Comment by HenrikBernhard** [comment] 2023-03-24 14:46
@YoupHulsebos could you update this thread when you get a reply from support? 
Also having the same issue and have tried to drop pagesize down to 120  - but would like to hear if you get a reply from support as i need to pull in 100k+ users on every run

**Comment by YoupHulsebos** [comment] 2023-03-24 15:07
@HenrikBernhard sure thing! I have to go though an our cloud provider to create this ticket. So I expect that it will take a couple of business days.

**Comment by tkalligo** [comment] 2023-03-24 18:21
I did open a ticket yesterday, the support engineer said they were going to escalate it to the product group.  I haven't received any updates yet.  I'll let you know what I find out.  I did change page size to 120 as well.  The code is running now without an error so far, but I am assuming it is going to take significantly longer to complete.

**Comment by jvpenna1975** [comment] 2023-03-25 14:15
I am having similar issues as well using Power Automate.  Code was running fine for months then started giving me issues with the signin in data.  I am not seeing valid lastSignInDatetime data come across for some users, when I compare the Sign in logs from the Azure GUI, they are not consistent.

**Comment by loryanstrant** [comment] 2023-03-27 06:47
Throwing my hat in the ring on this thread, I'm also experiencing this issue now, but via Power Automate.
Some workflows have no issue getting a bunch of loops with 999 items then randomly will stop and throw the 120 limit error, whereas just today it happened straight out the gate on the first run.

**Comment by magnusjak** [comment] 2023-03-27 08:36
Same issue here when using a page size of more than 120 when adding the SignInActivity property to the Users Graph call. Also hoping that this will be fixed, as things will take a lot longer to complete.

**Comment by rfoppen** [comment] 2023-03-27 12:31
This had me puzzled for a few days; automation jobs failing all of a sudden. I have opened a case through our MS EA as well.

**Comment by colinhqgit** [comment] 2023-03-27 13:57
Having the same issue, using beta Graph SDK for C#.
The problem started happening on March 22nd for us.
We've been running our automated tasks for over 2 years now that fetched 999 users at a time.

If the direction is to bring it down to 120 per request, please support more search criteria in the queries.
Exemple: Being able to request users where OnPremisesLastSyncDateTime == null.

**Comment by JazBInKC** [comment] 2023-03-27 14:05
It does seem counterintuitive that MS would deliberately create 8x more queueing by reducing the maximum page size.

**Comment by jvpenna1975** [comment] 2023-03-27 22:49
I have opened a case with Microsoft on this as well.  I am not sure the pagination issue is affecting us, but SignInActivity does not seem to be accurate or missing when we use simple Graph queries.  Even if I query just one user we have consistency issues.  I urge people to audit your data.   We are using Power Automate http connector with $filter User Type eq 'Guest' and trying to just pull the activity so we can purge old accounts not logged in for X amount of days for compliance purposes.  Looking back on our flow history, as early as last Tuesday, we were pulling accurate data.  Now, for some users data that was there for SignInActivity is missing.  I have tried both Beta and V1.0 and they both produce the same results

**Comment by pkoelemij** [comment] 2023-03-28 14:42
I can cofirm this issue: seeing the same behaviour when selecting SignInActivity.

**Comment by rfoppen** [comment] 2023-03-28 15:21
I've received a comment back from Microsoft that:

"After looking into it, it seems that there may be some service issue, which is now being investigated internally on our side."

**Comment by YoupHulsebos** [comment] 2023-03-28 17:07
I've also received a comment back from Microsoft that:

```
•	On the /users endpoint you can use a $top parameter and specify the number of objects(users) that you want to be retrieved on each page. When you request a page, you also get an odata.nextLink that can be used to request the next page of results. 
•	The $top parameter indicates the maximum size of the page. Until recently, this parameter could have had a value between 100 and 999. However, this has changed and the maximum value it can have is now 120. 
•	We have discussed about this change with our Product Group and they mentioned they are working on making this change globally available and the reason for updating the logic of the API is to reduce the number of users that can be pulled from the backend in the same time. They also added that they are working on a public documentation that will provide more details about the update.
```

It seems more information is coming soon...

**Comment by JazBInKC** [comment] 2023-03-28 17:19
That's ridiculous.  That just means more pages.  How is that helping anything?   Our need doesn't decrease accordingly.  :(

**Comment by colinhqgit** [comment] 2023-03-28 18:02
Agreed, this is ridiculous. I hope when they decided to change the limit to 120 that they are planning to support more filters in order to narrow down our search then!

**Comment by FiggyRoll** [comment] 2023-03-28 18:22
Ridiculous is a bit harsh, frustrating yes. Could MS communicate a change properly for once, yes but I’m sure they have valid reasons for making the change. 

Just change the value to 120. You don’t need extra filters, you are still going to get the same data back, albeit slightly slower than previously.

A script we have running polls ~70000 users, changing to use 120 has probably added a couple of mins onto the runtime if that, but the script runs in azure on a schedule so it has 0 impact on me apart from the minor inconvenience of having to do a pull request to change a value from 999 to 120.

I’m sure there are use cases out there where the absolute quickest response possible is needed, but surely for the majority of users this isn’t a massive issue?

**Comment by colinhqgit** [comment] 2023-03-28 18:33
One of our tasks is required to fetch all users that aren't sync'ed on-prem (ie: OnPremisesSyncEnabled eq Null).

v1.0 or beta
https://graph.microsoft.com/beta/users?$filter=OnPremisesSyncEnabled eq Null
=> response: Request_UnsupportedQuery
https://graph.microsoft.com/beta/users?$filter=OnPremisesSyncEnabled ne true
=> response: Request_UnsupportedQuery

Here is the documented list of properties that are supported/unsupported/supported using advanced querying: https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http#support-for-filter-on-properties-of-azure-ad-directory-objects

**Comment by JazBInKC** [comment] 2023-03-28 19:44
And a (completely unnecessary) programming lesson along with the " we know what's best for you (and we we're going to tell you eventually)" justification.  Gotta LOVE Microsoft.

**Comment by tkalligo** [comment] 2023-03-29 17:09
Here is the response I received from the support ticket opened.

Thank you for your patience.
The PG have confirmed that this endpoint will be transitioning from beta to General Availability (GA).
As part of this transition, changes to its behavior has been made, this includes not requesting more than 120 results per call.
They recommend requesting less than 120 results per call, which can be done by setting the top parameter to, say 100.
 
**Here is an example in PowerShell:**
Get-MgUser -Top 100 #additional parameters here ...
 
Let me know if you have additional questions.
 
**Current Status:**
PG confirms that changes are being made to this endpoint, transitioning from beta to GA (v1.0). Part of the changes, includes limiting the amount of data that can be returned per call to less than 120.
 
**Proposed Solution:**
Limit data returned to less than 120 using the top parameter:
Get-MgUser -Top 100
 
**Action on Customer:**
Review findings.
Address questions and concerns to Microsoft engineer.
 
**Action on Microsoft:**
Hear from customer.

**Comment by JazBInKC** [comment] 2023-03-29 17:34
Funny - I don't think they want to hear from customer.   They just do what they want and tell us what will be.  :(

**Comment by techjazz** [comment] 2023-04-03 16:11
Hi All - is there any public announcement on this? My script has broken too :S

**Comment by besiler** [comment] 2023-04-04 22:40
I'm from the Microsoft team working on this data. Apologies for responding so late after you opened this, but I was just sent this thread. 

Current workaround: Requests with no top parameter or a top parameter equal to or less than 120 will work

Background:
As you all have noticed, we made two changes here that impacted scripts and apps using signInActivity in the users API:

1. We reduced the max page size to 120 user records when making a call that includes signInActivity. This was done because the primary complaint for this query type was poor performance/throttling
2. We changed from a silent failure for requests over the max page size to throwing an error message. This was done to comply with best practices that the API should inform clients when it does not respect parameters the client passes

The combination of these two changes broke any scripts/clients requesting larger page sizes. 

Mitigation: (As noted in the workaround above) Modify scripts/clients to request 120 users or less

Next steps: We'll publish public guidance on this and evaluate how to meet the performance reqs identified above. We also need to do a post mortem to identify the processes that broke down and how to avoid these kinds of issues. 

Request for you: If you're open to it, I'd like to know more about the different use cases people are trying to balance. What is the main issue in your opinion with the incident? 

1. Lack of communication: You don't have a strong opinion on this page size restriction, but the rollout and communication of the change was insufficient 
2. 120 is too small: You need bigger page sizes than 120. If you choose this option, I'd appreciate if you could expand a bit on your use case like @colinhqgit did above
3. Throwing an error is unnecessary: you don't mind page size restrictions from the server side since your client will page through all the data requested regardless, but you'd prefer the API to return data up to the server's limit rather than throwing a failure

**Comment by jvpenna1975** [comment] 2023-04-05 00:05
@besiler I am still having issues even requesting one user when looking for signInActivity.  I am using power automate to report on our tenant Guest users and we want to grab their last login date so we can reconcile unused guest accounts.  My power automate flow was working fine up until a couple weeks ago and now there are a whole host of guest accounts that do not give us anything for signInActivity.  I am stumped at this point on what to do next...I have a case opened.  

For us, 120 users is low as now we have to over-engineer a power automate flow for grabbing guest accounts based on some loose metadata.  Looking for your feedback

**Comment by JustinRustin** [comment] 2023-04-05 00:53
@besiler We are also seeing poor data coming back for signInActivity. For example, for a particular user we have received a signInActivity of '3/26/2021 12:22:11 AM' on a previous request, and we've recorded that date in our database for use in various processes. When we query the same user, we're now getting a date of '6/17/2020 4:44:09 AM'. For some users we have previously received a date for the query, where now we are getting a null.

Are you aware of a data issue?

**Comment by rfoppen** [comment] 2023-04-05 06:28
@besiler  Thanks for the info.

1) The lack of communication far below par. We have automated business processes which rely on these API calls. Unexpected changes like these first caused a set of failures, then a set of frustrated techs not understanding why unchanged code on our end no longer works. Opening a case with support leads to nothing and then finding others in the same boat on the public internet is not a good story to tell to our (many contract dollars spending) management. 

2) I do not particularly mind a max page, but do not see the value in it?  We have about 60.000 objects to query. The lowered max will simply result in us doing more calls. 

3) Throw an informational error.

Lastly I concur with @JustinRustin and @jvpenna1975  The returned signInActivity appears to be inaccurate. This again interferes with business logic. We make decisions based on the data values, and have to rely on those being correct and consistent. (same concept for Guest account cleanup)

**Comment by loryanstrant** [comment] 2023-04-05 07:14
Same here, it's taken a lot of pain and frustration to figure out this problem.
999 was already a low top count, especially when other MS APIs allow 5,000.

A low count of 120 is not workable for my requirements, when one of the tenants I pull user data from has 300k users, and I'm currently building a solution **for** MS AU that will pull from a tenant of 800k+ users.

**Comment by JazBInKC** [comment] 2023-04-05 13:16
Besiler –

The most unnerving issue was the total lack of communication.   Then the lack of knowledge on MS behalf when we (most of us) opened case with support.

We all experienced the same issue:  what was essentially “set and forget” code no longer worked and the associated error was misleading.   I run nightly reports for all of our managed tenants so we (they) can determine which accounts will be disabled (much like others, I assume).  Limiting the page size for SignInActivity will only result in more page calls, and 120 vs 999 vs (everything else is 5000) is a massive inconsistency.   Frankly, Graph should report MORE – I’m having to run a second pass against ‘qualifying’ users for their Exchange activity date / times – why isn’t that also available from Graph?

The error should have been clear and precise, but moreover there should not have been an error.  There should have been a warning and the result set limited to the new page max.   That would have resulted in still-working code and allowed US to catch up to the latest unannounced change.

Thanks for spear pointing this.

Regards,

jbw

***@***.***<https://ihs911.com/>
***@***.***<https://twitter.com/IHS911marketing>
***@***.***<https://www.facebook.com/IHS911/>
***@***.***<https://www.linkedin.com/company/ihs911>
James Wood​​​​
Support Services ‑ Solution Specialist
t: (913) 945-4711<tel:(913)%20945-4711>
f: (913) 945-4711<fax:(913)%20945-4711>
e: ***@***.******@***.***>
 |
w: www.ihs911.com<https://ihs911.com/>
a:
7520 W. 160th St. Suite 101
,
Overland Park
,
KS
66085

**Comment by besiler** [comment] 2023-04-06 00:39
All,

Thanks for all the responses. I'll give an update on the current status of this issue and then some thoughts on the points you've raised. 

**Mitigation for the $top page size error**: we reverted the code that throws the error when **$top exceeds 120 and signInActivity is requested** this morning. This is a relatively safe change so we can roll out quicker than our normal deployment cycle. Please note that for the short term, the server will still enforce a page size of 120 when a client requests signInActivity and $top greater than 120. 

**Current workaround**: Clients that page through results using skiptokens should resume working, even if the $top parameter is set for more than 120. 

**Next steps for Microsoft**:
- Roll out further mitigations: increase the page size limit for requests to the users API that include signInActivity
- Investigation on data issues: the data issues you're raising are highly concerning. Stability of the data in this property is very important for detecting stale users accurately. We've been working on improving performance of API calls that include this property, but degradations here should have been caught in the battery of test cases we ran. I don't have an answer yet for why they weren't caught, but we'll find that as part of the investigation
- Post incident report (PIR). After getting a full set of mitigations in place, the next step is to run a post incident report. The communications and change management failures in the rollout of this change mean that multiple processes and safeguards broke down. We need to figure out how that happened and how we can prevent it in the future. We will make sure to discuss the comms process, the lack of notice for changes to an API, and the data issues. 

-------

Beyond the update above, I wanted to address the comments you made:

1. **Data issues**: Three people noted data issues which is a very serious sign that we likely have other, unreported issues. None of the issues you're reporting match known issues from before we rolled out changes to make this property more efficient. @jvpenna1975 could you please send the number of your case to me at besiler@microsoft.com? We can't look at your data except in the context of an open case, so I'd like to work with the support rep on that one. @JustinRustin and @rfoppen you didn't mention whether you had cases open or not, but if you do can you also send the number to me at besiler@microsoft.com for the same data access reasons? 
2. **Comms process**: The comms process (or lack of comms) you saw here is not at all what we expect or what you should expect. There are Graph guidelines on how to communicate necessary changes to the APIs -- part of the Post Incident Report will be figuring out why those were not followed and how we can prevent missing comms in the future. 
3. **Page size limits**: Thank you all for sharing the pain points for lower page sizes. I think there's another pain point here in that the users API (and other Azure AD directory APIs) have limits of 999 except in this case, which is hard to plan for as a dev. 

Overall, I just want to apologize for the issues and frustration you all dealt with diagnosing and responding to this issue. We're rolling out mitigations, but they won't undo the time spent tracking down this issue and updating clients. Right now the dev who worked on this feature is focused on mitigations, but when we get those done we'll move into the Post Incident Report stage ASAP. It still won't undo the issues you've faced, but at least we'll be able to provide info on what went wrong and steps to harden our systems and processes against these kinds of issues. 

I'll keep this thread updated with the latest on our mitigations -- we're also communicating with CSS (customer support) so they get the guidance as well.

**Comment by jvpenna1975** [comment] 2023-04-06 01:30
@besiler I will send our case to you via our corporate email...watch for it

**Comment by rfoppen** [comment] 2023-04-06 04:52
@besiler  Sending case data via email.

Thank you for taking ownership of this one and the candid response. Appreciate it.

**Comment by JustinRustin** [comment] 2023-04-06 05:50
@besiler Thank you. 

Regarding the data issue, I incorrectly assumed that the change in batch size was related to a broader service issue that Microsoft already knew about, and was tied up with the poor data we were seeing. As happens from time to time, I didn't have enough time to both investigate and resolve the impact on my side, and also get through the many emails back and forth to 1st level support it usually takes before the issue is escalated to the SMEs. So I went with the 'surely there are going to be others who had the time to raise tickets with MS and they already know about it'. Sorry - I am being flippant, but it has been a week. I know escalation paths exist for a reason, but some times it's so hard to get through the process. 

We've disabled our automated processes in Production until this is resolved, but I have just raised a ticket with some data from our NonProduction environment, and I've just sent details through via email.

Thanks again for your help!

**Comment by helipetr** [comment] 2023-04-11 11:05
Also discovered issue today where signinActivity was returned EMPTY for users that last week had attribute filled in ok. So, it's not just a page size issue. Still nothing communicated in Message Center. Ok, it's a preview feature (my bad if using it) but Microsoft obviously sees it's been used a lot already. Microsoft has an article suggesting using this signinActivity attribute for hunting stale accounts.

**Comment by besiler** [comment] 2023-04-12 00:23
All,

Thanks for sending the support cases my way. We're focusing on the data quality issues raised as our current area of focus. It seems that customer support wasn't able to solve the data issues you experienced, so I'm asking them to escalate to the product engineering team so we can take a look at specific examples from your tenant. You may still hear questions from them if we need to gather more data. 

Ben

**Comment by BananZG** [comment] 2023-04-12 14:17
Update on this issue after able to get users with size > 120 and selecting signinActivity, i found that signinActivities for some users are EMPTY when im trying to get >=120 users. When i try exact queries with only 100 users, the signinActivities returned.

**Comment by BananZG** [comment] 2023-04-13 07:11
> Update on this issue, after able to get users with size > 120 and selecting signinActivity, i found that signinActivities for some users are EMPTY when im trying to get >=120 users. When i try the exact queries again with only 100 users, this time the signinActivities returns correctly.

update again, it happens when the request includes ConsistencyLevel: eventual + $count=true for advanced query.

**Comment by Borgquite** [comment] 2023-04-17 09:56
@BananZG Same experience here - selecting count > 120 and SignInActivities are EMPTY. **This behaviour is now worse than it was before** - because queries are failing without people knowing.

**Comment by besiler** [comment] 2023-04-18 06:14
All, as of last Thursday we believe that all the behaviors you've raised in this thread are mitigated. We're currently validating that everything is fixed in the support cases you've sent our way -- if you still see incorrect or missing data, please let me know your support case number and we'll get the data from customer support so we can investigate.

**Comment by HenrikBernhard** [comment] 2023-04-18 11:19
@besiler 
It doesn't yet look to be fixed. 

Prior to the issue occuring we had a script running which would take all guests created more than 395 days ago, and if they had no activity or last activity more than 395 days ago - delete them. 
The script was paused and accounts restored when this broke. 

I just tried to run my script (using top=120 and without actually deleting accounts) and had 400+ accounts created in 2021 or before report as "no sign in activity" (which should all have been deleted months ago if that was true...) 

Doing spot checks on these accounts show them as having a sign in date in the GUI even if reported "null" in the graph calls

I haven't opened a case as I could see others had cases open so it didn't seem needed - but if you need more details, let me know and I can open one.

**Comment by JBines** [comment] 2023-04-19 11:17
@besiler It was a mistake to change the error reported from my perspective. 

The use case here is that we had a script removing stale accounts based on the lastSignInDateTime but when user object (0..1000) was reported with a null signin value (120..999) accounts were incorrectly deleted! 

Luckily we had some fail safes in the script but still...

**Comment by besiler** [comment] 2023-04-21 04:08
@HenrikBernhard yes, you should have seen the fixes for those data issues rolling out to your tenant on the 13th and 14th, so if you are still having issues a support case would be very helpful for us. The engineer working on this issue has gone through all the support cases we got so far to ensure the data issues are resolved--based on the cases we got already, everything should look good on your end by now but that doesn't match what you're seeing. We'd love to take a look.  

@jvpenna1975 in my opinion, most customers (who are trying to identify stale accounts) are best served by looking at whichever lastSignInDateTime is later, since either can indicate that a user is not truly stale. I sent this description to you in email, but I hope it is helpful for you/others so posting here as well 

User sign-in log category descriptions
Today, Azure AD has two categories of user sign-in logs: interactive and non-interactive. Both categories are described below. Special cases, where a sign-in that appears non-interactive shows up in the interactive logs or vice versa, are also possible (info about those special cases is below in Finding user sign-ins in the Azure AD interactive and non-interactive logs).
•	Interactive logs represent sign-ins in which the user interacts directly with Azure AD HTML or a helper app, such as Microsoft Authenticator, to provide authentication factors. These are the sign-ins that users and admins are most likely to notice during normal work, since the user is asked to provide a factor or other input. 
•	Non-interactive logs represent sign-ins where a client accesses resources on behalf of a user. Instead of the user providing a factor to Azure AD, the client uses a token or code to authenticate or access a resource on behalf of a user. In general, the user will perceive these sign-ins as happening in the background.
 
Because interactive vs non-interactive is not a hard technical distinction (as opposed to something like the difference between OIDC grant types), customers may sometimes notice logs that seem like they would better fit in the other category. 
 
Finding user sign-ins in the Azure AD interactive and non-interactive logs
Admins sometimes need to find specific user sign-ins in the Azure AD sign-in logs. The following principles can help you find the logs you need:
 
•	Log completeness: All sign-ins performed by or on behalf of a user are captured in Azure AD between the interactive and non-interactive log category. If you don't see a user sign-in at the time you expect to see it, trying the other log category can be helpful.
•	Grandfathered non-interactive logs: some log types, especially those related to older, deprecated, or legacy auth flows, appear in the interactive sign-in logs even if they would otherwise seem interactive. This occurred because those log types were included in the interactive logs before the launch of the non-interactive logs in 2019; Azure AD engineering kept them classified in their original category to avoid breaking changes for customer apps and automation. 
•	Unusual cases: in some types of authentication, such as a QR code based authentication, the user never technically interacts with the Azure AD service directly (the client uses an artifact from the QR code to authenticate in the background, without requiring user input). However, these sign-ins are classified as interactive because users and admins found that more intuitive. 

@JBines Yes, we agree that changing the error was a mistake. We recently completed a post incident report on why our change management process broke down in this case. If you're interested in additional root cause info, can you please email me or engage your support person if you have a case open? Happy to send the root cause info and the additional steps were taking to prevent similar issues in the future to you directly.

**Comment by HenrikBernhard** [comment] 2023-04-28 12:35
Just as an update for anyone following this thread. I was still seeing issues in the data returned on the 26th of april, but the product group fixed whatever bug was affecting my results on the 27th. 

Basically for some percentage of the results returned when doing top=120 in a paged query, the "signInActivity" part would be missing completely from the response - even if included in the query and it would be returned for most users

**Comment by JustinRustin** [comment] 2023-05-04 00:21
We've just done a comparison of the 180k+ user in our tenancy vs the data we had stored in our DB on those users prior to this incident. Pretty much all of the users are reporting the same date or a more recent date than what we have in our database, so it appears the issue is resolved. There is a handful of exceptions but these are users who last signed in back in 2020/2021, so not too concerned. We'll be re-enabling the processes that rely on this API today.

**Closed** 2023-05-07 01:04 UTC
Labels: Service issue, Needs: Author Feedback, no-recent-activity
