### ISSUE TITLE
New-MgUserOutlookMasterCategory NullReference exception in 0.9.1

### ISSUE THREAD

**Issue by sergeyz7** [microsoftgraph/msgraph-sdk-powershell#351] opened 2020-08-27 11:48 UTC
Appears to be a local parsing/validation error, as no request to Graph is actually issued.
Works as expected in version 0.7.0 of the module.

**Comment by peombwa** [comment] 2020-08-27 15:40
This is a duplicate of #337 . A fix has been made and will be available in the next release.

A workaround is set an empty `-additionalProperties @{}` when using expanded properties
``` ps
 New-MgUserOutlookMasterCategory -UserId $userId -Color "preset9" -DisplayName "Project expense" -AdditionalProperties @{}
```
 or use `-BodyParameter`
``` ps
New-MgUserOutlookMasterCategory -UserId $userId -BodyParameter @{Color = "preset9"; DisplayName = "Project expense"; }
```

See discussions here https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/337#issuecomment-674313890

**Closed** 2020-08-27 19:40 UTC
Labels: Bug: Client, duplicate
