### ISSUE TITLE
Unable to request "Presence.Read.All" as part of scope

### ISSUE THREAD

**Issue by leeford** [microsoftgraph/msgraph-sdk-powershell#71] opened 2020-01-02 12:57 UTC
Great work so far!

I am unable to request "Presence.Read.All" as part of the scope requested. I am able to request my own users presence using "Presence.Read", however.

![image](https://user-images.githubusercontent.com/472320/71668061-681b8b00-2d5f-11ea-957a-6b631d28f456.png)

**Comment by Windos** [comment] 2020-01-21 01:53
I can confirm this behaviour. Seeing it on 0.1.1 installed from the PS Gallery. Tried in both Windows PowerShell and PowerShell 7.

![Example from PS7](https://user-images.githubusercontent.com/6955786/72768922-ce5c4500-3c5d-11ea-89a2-35f511fe281a.png)

**Comment by leeford** [comment] 2020-01-23 10:33
Glad it's not just me then. Yep I get the feeling that 'Presence.Read.All' is not deemed a valid permission (even though it is)!

**Comment by peombwa** [comment] 2020-02-20 22:55
This is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/108.

**Closed by peombwa** 2020-02-20 22:55 UTC
Labels: ToTriage
