### ISSUE TITLE
Cmdlets where the first parameter variant has not defined all the mandatory parameters hence returning errors if run as defined.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#707] opened 2021-06-18 06:15 UTC
- New-MgDirectoryRoleMemberByRef
- Set-MgUserLicense 
- New-MgGroup 
- New-MgGroupMemberByRef
- New-MgGroupMemberOfByRef
- New-MgGroupMember 
[AB#9953](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9953)

**Comment by peombwa** [comment] 2021-06-22 16:00
Closing this as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/705 and https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/706

**Closed by peombwa** 2021-06-22 16:00 UTC
Labels: ToTriage
