### ISSUE TITLE
How can I create an OneDrive folder?

### ISSUE THREAD

**Issue by cywang16** [microsoftgraph/msgraph-sdk-powershell#129] opened 2020-03-11 06:36 UTC
I cannot figure out the command creating a folder in OneDrive. Seems to be using New-MgDriveItem, but cannot figure out the right command line options.

Can anyone help? Thanks. 
[AB#7435](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7435)

**Comment by peombwa** [comment] 2020-12-18 18:44
This is a bug on our end. It looks like all navigation properties of a `driveItem` entityType are not being translated into OpenAPI as paths. In this case, `Children` NavigationProperty is missing.

To create a folder, one needs to call `/users/{user-id}/drive/items/{parent-item-id}/children`. See https://docs.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=http

@cywang16 A workaround for this would be to use `Invoke-MgGraphRequest`:
``` powershell
$Folder = @{
    "name" = "New Folder"
    "folder" = @{}
    "@microsoft.graph.conflictBehavior" = "rename"
}
Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/v1.0/users/$UserId/drive/root/children" -Method POST -Body $Folder
```

**Comment by peombwa** [comment] 2022-05-10 23:30
We are tracking the missing `*/children` APIs in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/813, and a fix will be provided in the upcoming release.

Closing as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/813.

**Closed by peombwa** 2022-05-10 23:30 UTC
Labels: OpenApiService-Dependency
