### ISSUE TITLE
Microsoft.Graph.Authentication module missing documentation

### ISSUE THREAD

**Issue by landonpierce** [microsoftgraph/msgraph-sdk-powershell#1406] opened 2022-07-19 19:29 UTC
The Microsoft.Graph.Authentication module does not have any documentation on the Powershell SDK Microsoft Docs page: https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-beta

This module contains several important commands that would be nice to have documentation on. Please let me know if you need any other information. 

![image](https://user-images.githubusercontent.com/93268703/179832643-91d45841-490c-466a-9641-39dba26b3562.png)

@maisarissi FYI for visibility

**Comment by maisarissi** [comment] 2022-07-19 21:55
Hi @landonpierce .

Yes, we have realized we are not generating documentation for the Authentication module, and we have started the work to put in place some content around it.
I will close this issue as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1088

**Closed by maisarissi** 2022-07-19 21:55 UTC
Labels: ToTriage
