### ISSUE TITLE
Using Get-mgAuditSignIn after selecting Beta profile is still using v1.0 profile unexpectedly

### ISSUE THREAD

**Issue by JefTek** [microsoftgraph/msgraph-sdk-powershell#1431] opened 2022-07-28 00:40 UTC
While troubleshooting a script that uses the Get-mgAuditSignIn with a filter that was resulting in an invalid filter, I noticed that in debug mode even after selecting the beta profile, the cmdlet was still using the v1.0 where the filter was not supported.  

Running the same filter with explicitly using beta in URI via Invoke-MgGraphRequest works as expected.

See the example of the cmdlet debug on this thread where the original issue was reported:

https://github.com/AzureAD/MSIdentityTools/issues/9#issuecomment-1197518990

Using the v1.10.0 version of the cmdlets in this example

**Comment by peombwa** [comment] 2022-08-02 21:01
The command is calling beta endpoint as expected (use Fiddler to verify).

The issue is with the `-Debug`. The debug event listener isn't aware of the profile change due how the profiles architecture works. The wrong URL in the debug log will be fixed by #692, when we release version two of the module.

**Comment by peombwa** [comment] 2022-10-18 18:15
Profile support will be dropped in v2. Was fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/692.

**Closed by peombwa** 2022-10-18 18:15 UTC
Labels: Resolved: Awaiting Validation
