### ISSUE TITLE
Unsupported TLS version. Please use TLS 1.2 or above

### ISSUE THREAD

**Issue by SeniorConsulting** [microsoftgraph/msgraph-sdk-powershell#2004] opened 2023-05-10 22:19 UTC
Hi Team,

I'm using the Graph SDK v2 (Preview9), and after signing in, any cmdlet I run produces the message below, within Visual Studio Code **_and_** native PowerShell (version 5.1):

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/262c42fe-2d9e-408b-b76b-08796f7805c7)

I've ensured that my TLS protocol is set to 1.2
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/0fe2eac0-cb49-44e1-8c70-955926d00919)

Here's the same device, same network connection, same environment, different results between v1.x and 2.x
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/f5ef1458-8ed6-4723-8420-082c4e9ac3e9)
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/d7c7f07e-49ef-4f2e-8cfa-2c3a86736842)

It's important to note that this issue has only _**just**_ started appearing recently, and has not been seen previously. I don't believe that it has to do with a recent update between Preview8 and Preview9. My gut feel suggests it might be related to the MFA number matching, but I don't see how this could be related, as the interactive authentication is successfully completed.

Lastly, some further logs for good measure:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/e3f5e7e1-bb8d-4fe6-89d2-7fb086013f79)
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/0962a03c-2e8f-4a14-83d6-e5de908fa793)

Is this happening to anyone else?

**Comment by SeniorConsulting** [comment] 2023-05-10 23:17
Just a note re: my comments about number matching. **_Please disregard it_**. I've created an app registration (which does not use MFA/interactive auth) and connected to MgGraph that way - it still results in the same error message.

**Comment by SeniorConsulting** [comment] 2023-05-10 23:34
Ahh. The cause of the issue was a company/enterprise internet **proxy server**. Interesting that the v1.x seemed to handle this OK, but 2.x didn't?

I'll leave this open for now, just in case there's some proxy handling which needs to be accounted for in the v2.x modules. Happy for this to be prioritised as a low priority and/or closed if it's a known issue (I did search for TLS errors, but couldn't find anything in here).

**Comment by peombwa** [comment] 2023-05-12 20:56
I'm glad you were able to resolve the issue.

I suspect v2 failed as expected due to improvements made around claims processing and HttpClient usage in the core libraries. Proxy settings are handled by the system, not the SDK. The inbuilt HttpClient will use the proxy settings set on the system.

I'll close the issue since the cause was a proxy server.

**Closed by peombwa** 2023-05-12 20:56 UTC
Labels: ToTriage
