### ISSUE TITLE
Remove-MgUserPhoto

### ISSUE THREAD

**Issue by NataliyaVlizko** [microsoftgraph/msgraph-sdk-powershell#2151] opened 2023-07-12 09:04 UTC
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
>Remove-MgUserPhoto throws the error "Method is not allowed". When I checked permissions for this command with Find-MgGraphCommand -command Remove-MgUserPhoto | Select -First 1 -ExpandProperty Permissions, permissions set is empty. 

**To Reproduce**
1. Execute Remove-MgUserPhoto with account/app that has User.ReadWriteAll permissions
2. See error at `...` 

**Expected behavior**
> A clear and concise description of what you expected to happen.

**Debug Output**
> Run the problematic command with `-Debug` and paste the resulting debug stream below.
> ⚠ ATTENTION: Be sure to remove any sensitive information that may be in the logs.

**Module Version**
> Please run `Get-Module Microsoft.Graph*` after cmdlet execution and paste the output below.
> If a module cannot be installed or imported, please run `Get-Module -ListAvailable` and paste the output.

**Environment Data**
> Please run `$PSVersionTable` and paste the output below. If running the Docker container image, indicate the tag of the image used and the version of Docker engine.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by SeniorConsulting** [comment] 2023-07-12 22:26
Gidday,

There are lots of caveats for updating photos. The article for the API itself provides quite a bit more information for you, including permissions:
https://learn.microsoft.com/en-us/graph/api/profilephoto-update

While it's worth also reading the note the section _To update the profile photo of the signed-in user_, though I don't think it's the cause of your issue.

Judging by the error message (`Method is not allowed`), it sounds like it's talking about HTTP Method. In the article I've linked above also suggests that the only two methods available are PATCH or PUT.

When running `Remove-MgUserPhoto -UserId Sample.user@contoso.com -debug`, I can see the request method is DELETE
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/ab5a8473-4b19-4d67-9b71-301042e2c5da)

I could be wrong, but I'll leave it to the experts :)

**Comment by peombwa** [comment] 2023-07-17 15:39
Thanks for bringing this to our attention.

As stated above, the API does not currently support `DELETE` method for a user's photo. Unfortunately, the service metadata, which describes the API, says that the `DELETE` HTTP method is supported on the resource; hence, the wrong command was generated.

I've transferred the issue to https://github.com/microsoftgraph/msgraph-metadata/issues/387 for the metadata to be corrected. In the meantime, do not use the command as the API does not support deleting a user's photo. I'd also recommend you open a service feature request at https://developer.microsoft.com/en-us/graph/support if this is something you'd like to see supported.

**Comment by peombwa** [comment] 2023-07-17 15:39
Transfered to https://github.com/microsoftgraph/msgraph-metadata/issues/387.

**Closed by peombwa** 2023-07-17 15:39 UTC
Labels: ToTriage
