### ISSUE TITLE
access policy creation via powershell examples

### ISSUE THREAD

**Issue by blood-onix** [microsoftgraph/msgraph-sdk-powershell#1628] opened 2022-11-14 13:21 UTC
Hi,
I was trying to use example number 3 for powershell and beta profile without any luck.

First, I've added "Choices" as looks like they are missing in example.
Second was not obvious...I replaced first capital letters to small ones in all options in PrimaryApprovers and Questions sections.
After that it started to work.
The main question, Is it case sensitive? And could you please renew examples? 

```
$params = @{
    AccessPackageId = "xxxxxx-xxxx-xxxx-xxx-xxxxxxxx"
    DisplayName = "Users from connected organizations can request"
    Description = "Allow users from configured connected organizations to request and be approved by their sponsors"
    CanExtend = $false
    DurationInDays = 365
    ExpirationDateTime = $null
    RequestorSettings = @{
        ScopeType = "AllExistingConnectedOrganizationSubjects"
        AcceptRequests = $true
    }
    RequestApprovalSettings = @{
        IsApprovalRequired = $true
        IsApprovalRequiredForExtension = $false
        IsRequestorJustificationRequired = $true
        ApprovalMode = "SingleStage"
        ApprovalStages = @(
            @{
                ApprovalStageTimeOutInDays = 14
                IsApproverJustificationRequired = $true
                IsEscalationEnabled = $false
                EscalationTimeInMinutes = 11520
                PrimaryApprovers = @(
                    @{
                        "@odata.type" = "#microsoft.graph.groupMembers"
                        isBackup = $true
                        id = "xxxxxx-xxxx-xxxx-xxx-xxxxxxxx"
                        description = "group for users from connected organizations which have no external sponsor"
                    }
                    @{
                        "@odata.type" = "#microsoft.graph.externalSponsors"
                        isBackup = $false
                    }
                )
            }
        )
    }
    Questions = @(
        @{
            isRequired = $false
            text = @{
                defaultText = "what state are you from?"
                localizedTexts = @(
                    @{
                        text = "¿De qué estado eres?"
                        languageCode = "es"
                    }
                )
            }
            "@odata.type" = "#microsoft.graph.accessPackageMultipleChoiceQuestion"
            choices = @(
                @(
                    @{
                        actualValue  = "New York"
                        displayValue = @{
                            defaultText    = "New York"
                            localizedTexts = @(
                                @{
                                    text         = "New York"
                                    languageCode = "en-US"
                                }
                                @{
                                    text = "Nueva York"
                                    languageCode = "es-ES"
                                }
                            )
                        }
                    }
                    @{
                        actualValue  = "New Mexico"
                        displayValue = @{
                            defaultText    = "New Mexico"
                            localizedTexts = @(
                                @{
                                    text         = "New Mexico"
                                    languageCode = "en-us"
                                }
                                @{
                                    text = "Nuevo México"
                                    languageCode = "es-ES"
                                }
                            )
                        }
                    }
                )
            )
            allowsMultipleSelection = $false
        }
        @{
            isRequired = $false
            text = @{
                defaultText = "Who is your manager?"
                localizedTexts = @(
                    @{
                        text = "por qué necesita acceso a este paquete"
                        languageCode = "es"
                    }
                )
            }
            "@odata.type" = "#microsoft.graph.accessPackageTextInputQuestion"
            isSingleLineQuestion = $false
        }
    )
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb0e188e-58a7-99f6-4d3c-e348453870d8
* Version Independent ID: e7ecf449-32aa-f5e1-4329-5db547b7bfb6
* Content: [Create accessPackageAssignmentPolicy - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&tabs=powershell)
* Content Source: [api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2022-11-14 15:54
cc @markwahl-msft for visibility.

**Comment by markwahl-msft** [comment] 2022-11-14 19:24
See https://github.com/microsoftgraph/microsoft-graph-docs/pull/17895 "there is currently an issue with the Graph SDK client, seen with PSh but probably affecting others, in generating payloads in which there is a derived type. These are easy to spot as there is usually a mention of @odata.type within the payload. See email thread of Feb 15 2022 with Darrel Miller "RE: named location, Graph case sensitive and generated PSh fragments"..."

**Comment by peombwa** [comment] 2022-11-15 21:32
Yes, the API is case sensitive. I've opened an issue at https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1252 for the casing to be corrected in the PowerShell snippets.

As for the missing choices, this is due to a limitation in the code generator. Please use the workaround in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1376#issuecomment-1179422236. We are tracking the bug in #1376.

Closing as duplicate of #1376.

**Closed by peombwa** 2022-11-15 21:32 UTC
Labels: ToTriage
