### ISSUE TITLE
Confirm-MgServicePrincipalMemberGroup throws Unable to cast object of type JsonObject to JsonArray

### ISSUE THREAD

**Issue by krispenner** [microsoftgraph/msgraph-sdk-powershell#1159] opened 2022-03-18 23:50 UTC
The response from `Confirm-MgServicePrincipalMemberGroup` cannot be parsed by PowerShell.

Microsoft.Graph version is 1.9.3.

```powershell
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Transfer-Encoding             : chunked
Location                      : https://graph.microsoft.com/
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 79cb595a-929b-46ef-8a95-f6f693b116e5
client-request-id             : 79cb595a-929b-46ef-8a95-f6f693b116e5
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"West US 2","Slice":"E","Ring":"1","ScaleUnit":"002","RoleInstance":"MWH0EPF0005DC88"}}
x-ms-resource-unit            : 4
OData-Version                 : 4.0
Date                          : Fri, 18 Mar 2022 23:36:47 GMT

Body:
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(Edm.String)",
  "value": [
    "20000056-400e-4009-a00d-2da8d000000f"
  ]
}


DEBUG: [CmdletException]: Received exception with message 'InvalidCastException - Unable to cast object of type 'Microsoft.Graph.PowerShell.Runtime.Json.JsonObject' to type 'Microsoft.Graph.PowerShell.Runtime.Json.JsonArray'. :    at Microsoft.Graph.PowerShell.Runtime.Json.JsonArray.Parse(String text)
   at Microsoft.Graph.PowerShell.Applications.<>c.<ServicePrincipalsCheckMemberGroups1_Call>b__1062_0(Task`1 body)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Graph.PowerShell.Cmdlets.ConfirmMgServicePrincipalMemberGroup_Check1.onOk(HttpResponseMessage responseMessage, Task`1 response)
   at Microsoft.Graph.PowerShell.Applications.ServicePrincipalsCheckMemberGroups1_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Applications.ServicePrincipalsCheckMemberGroups1_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Applications.ServicePrincipalsCheckMemberGroups1(String servicePrincipalId, IPathsO5Kx2YServiceprincipalsServiceprincipalIdMicrosoftGraphCheckmembergroupsPostRequestbodyContentApplicationJsonSchema body, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Cmdlets.ConfirmMgServicePrincipalMemberGroup_Check1.ProcessRecordAsync()'
Confirm-MgServicePrincipalMemberGroup_Check1: Unable to cast object of type 'Microsoft.Graph.PowerShell.Runtime.Json.JsonObject' to type 'Microsoft.Graph.PowerShell.Runtime.Json.JsonArray'.
```

**Comment by peombwa** [comment] 2022-04-01 20:57
Thanks for bringing this to our attention. We are already tracking this issue in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/665, and a fix should be out soon. We are just waiting for one dependency to surface the fix to us - https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/571.


As a workaround, you can use `Invoke-MgGraphRequest` to check group membership as shown below.
``` powershell
$uri = "https://graph.microsoft.com/v1.0/servicePrincipals/$servicePrincipalId/checkMemberGroups"
$groupIds = @("id1", "id2")
Invoke-MgGraphRequest -Uri $uri -Method POST -Body @{ groupIds = $groupIds }
```

**Comment by peombwa** [comment] 2022-04-01 20:57
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/665.

**Closed by peombwa** 2022-04-01 20:57 UTC
Labels: OpenApiService-Dependency
