### ISSUE TITLE
No MgGraph CMDlets for custom directory role definitions

### ISSUE THREAD

**Issue by lyndon678** [microsoftgraph/msgraph-sdk-powershell#1438] opened 2022-08-04 07:42 UTC
While wanting to add a member to an existing custom directory role I noticed it's not enumerated by Get-MgDirectoryRoleTemplate, also not with the -All switch.
I then realized there are no CMDlet equivalents at all in the MS Graph PowerShell module for manipulating custom Azure AD directory role definitions, e.g.
- New-AzureADMSRoleDefinition
- Remove-AzureADMSRoleDefinition
- Set-AzureADMSRoleDefinition

When are these planned to be implemented?

**Comment by lyndon678** [comment] 2022-08-04 07:51
Via MS Graph docs I now found CMDlets for the sought after functionality. However, they are placed in the Microsoft.Graph.DeviceManagement.Enrolment module. Is this correct/intended?

**Comment by peombwa** [comment] 2022-08-04 15:47
Thanks for following up on this.

We are already tracking the misplaced directory roles commands https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1271. We will address it the next major update (v2) to avoid a breaking change.

Closing as duplicate of #1271.

**Closed by peombwa** 2022-08-04 15:47 UTC
Labels: question
